# -**- mode: org; coding: utf-8 -**-
#+TITLE: Default Autofocus Notebook
#+AUTHOR: Alisha Awen
#+EMAIL: Siren1@disroot.org
#+DATE: <2022-05-13 Fri>
#+TEXT: Created: <2022-05-13 Fri>
#+STARTUP: overview
#+FILETAGS: templates GTD Autofocus 

#+DESCRIPTION: Harmonic Alchemy Modular Emacs - Default Org-Mode Autofocus Notebook TEMPLATE... Copy/Clone this template file into your personal GTD space, and/or all your major projects GTD spaces... (it will help a lot!)

=Ref:= [[http://markforster.squarespace.com/autofocus-system/][The Autofocus Time Management System]]

* Intro:

The Autofocus Notebook Method is a GTD system developed by: *Mark Forster*  
[[http://markforster.squarespace.com/][see his blog here]] *email:* [[mf@markforster.net]]

This *Emacs Org-Mode* file is an implementation of Mark's Autofocus System for folks like me who cannot write in notebooks due to the anxiety of combined dyslexia and dysgraphia... This .org file is not intended to be exported to PDF or other things... It is for working within org-mode /(as your electronic version of a spiral ruled notebook...)/

=Note:= I copied all the instructions in the Meta Section below from the *Main Autofocus Website* /(see link above...)/ I hope I don't get in trouble with Mark for this! This is NOT intended to be a tutorial... It is a Template for folks who use Emacs and would like to try Mark's Method using a keyboard /(no mouse)/...

If you like this system =I strongly suggest you visit the website above= as well as his blog to learn more... /(this file is a template not a tutorial ok?)/ Mark has written many fine books on similar subjects... Also... If you don't have a problem with writing in a paper notebook etc.  I suggest you use Mark's system as he recommends... /(e.g., don't use this on a computer etc...)/

For the rest of us fumbling idiots when it comes to pen and paper, =READ ON!!=

This system is based purely on Mark Forster's experience... After only a few weeks of initial practice /(when he first started out)/ he discovered the following:

- *A greatly increased volume of work* Mark found He was able to process work much faster. This seems to be mainly due to the fact that there is very little friction in the way of resistance or procrastination.

- *A lack of stress* Although obviously one still has to do the work, there are no great barriers of resistance to overcome or feelings of overwhelm. In fact just about all Mark's work became pleasurable. The more he learned to trust the system, the more this became the case.

- *Ability to Focus on what is important* It’s very difficult to focus on what is important with one’s rational mind alone, because what your conscious mind thinks is important may not be what your subconscious mind thinks is important. Looking back on what you’ve done you will see that the focus produced by the system feels “right” - right for you in your current circumstances.

- *Very fast processing of routine actions* Your speed at doing various essential routine tasks will increase exponentially. The sort of things (e.g., replying to emails, answering comments on your blog, returning phone calls, etc. etc.)

- *Thorough processing of major tasks and projects* The system encourages a “little and often” approach to major tasks. The result is that a project, such as setting up this trial, can be dealt with over a period of time in a very methodical way. One other result of the “little and often” approach is that ideas and insights naturally spring up as a result of one’s mind engaging with the task over a period of time.

* [Your Name] Autofocus Notebook: /(Rename This)/
:README:
   This is my first org-mode based autofocus notebook which He am trying out here initially as a test case...  Once I have a nice system set up I will migrate all my autofocus notebooks from Trello to Org-Mode...  

   I will be cloning this TEMPLATE to create Autofocus Notebooks for: Personal, clients, projects, etc... You should do the same...

   =Note:= Page 1 below contains a few rules to follow written as an example of 
          using the notebook itself... Simply remove those and replace them with 
          your own tasks...
:END:
** ACTIVE Autofocus Notebook - Page 1: [2/7]

1) [X] Clone this .org file... Change its name and title to suit your needs
2) [ ] Copy Autofocus Items from your Trello Notebooks if you have them
3) [X] Type ~SHIFT M-RET~ with cursor on a line under the last item in 
       this list to make a new checkbox item...
4) [ ] Keep your item headings one line only (/not like the one above)/
5) [ ] Link Item headings to more info note if needed: [[./meta/sample-todo-item.org][Like This]]
6) [ ] Add up to 25 items per page /(as recommended by Mark)/
7) [ ] When you have more than 25 items, start a new page /(below)/

** NEW Autofocus Notebook - Page 2: [0/3]

1) [ ] placeholder entry -> this is a placeholder for a task not a task itself...
2) [ ] 
3) [ ]

* Meta:
** Quick Start: /(copied from AF web-page reformatted for org-mode)/

The Autofocus system consists of one long list of everything that you have to do, written in a ruled notebook (25-35 lines to a page ideal). As you think of new items, add them to the end of the list. You work through the list one page at a time in the following manner:

- =Read quickly through all= the items on the page without taking action on any of them.

- =Go through the page more slowly= looking at the items in order until one stands out for you.

- =Work= on that item for as long as you feel like doing so

- =Cross the item off the list=, and re-enter it at the end of the list if you haven’t finished it

- =Continue going round the same page= in the same way. Don’t move onto the next page until you complete a pass of the page without any item standing out

- =Move onto the next page= and repeat the process

- =If you go to a page and no item stands out= for you on your first pass through it, then all the outstanding items on that page are dismissed without re-entering them. (N.B. This does not apply to the final page, on which you are still writing items). Use a highlighter to mark dismissed items.

- =Once you’ve finished with the final page=, re-start at the first page that is still active.

Each of these steps is explained in more detail below, but I suggest you get going now and read the rest of the instructions later. Don’t forget to put “Read the rest of the instructions” as one of your tasks. You don’t need a huge number of tasks to start with, just add tasks as you think of them or they come up.

** Full Instructions:  /(copied from AF web-page reformatted for org-mode)/
*** As you think of new items, add them to the end of the list.

One of the characteristics of this system is that you can chuck anything at it. I recommend that you enter everything that comes to mind without trying to evaluate. The system itself will do the evaluation.

*** Read quickly through all the items on the page 

/(without taking action on any of them.)/

A quick read through the page allows your mind to start processing the items without pressure.

*** Go through the page more slowly:

/(looking at the items in order until one stands out for you.)/

This is the heart of the system. Don’t try to prioritise items mentally - this will interfere with the balance between the rational and intuitive parts of your mind. Instead wait for a feeling of release about an item. It’s hard to describe but easy to recognise. You just feel that the item is ready to be done. If you go on down the page, you may find that you feel drawn back to that item. Once you get that feeling about a task all resistance to doing the task vanishes, and it becomes easy to do.

*** Work on that item for as long as you feel like doing so

Don’t force yourself to continue working on the item for longer than you feel right doing so. This system encourages a “little and often” approach. Once you feel you’ve done enough, stop.

*** Cross the item off the list:

/(and re-enter it at the end of the list if you haven’t finished it)/

Actually it’s better to re-enter it first and then cross the item off because then you are less likely to lose your place, but I have to admit I’m not very good at remembering to do it in that order. Re-entry of items is an essential part of the system. You should re-enter everything which is done on a recurring basis (e.g. e-mail, paper, exercise), everything you are still working on (e.g. draft article or report), everything which needs follow up (e.g. Mike replied to email yet?), and extended tasks like reading a book, magazine or journal. You may also need to enter next steps or follow-up items. I find that about half to two-thirds of my tasks require re-entry in one form or another.

*** Continue going round the same page in the same way:

/(Don’t move onto the next page until you complete a pass of the page without any item standing out)/

Treating each page as a unit allows you to get the benefit of “structured procrastination”, which is based on the fact that procrastination is relative. In other words any task becomes easy if it is a choice between doing it or another harder task.

*** Move onto the next page and repeat the process:

You may find that you pass through a page very quickly or spend a considerable time working your way round it. Either way is fine - just let the “standing out” method guide you.

*** If you go to a page and no item stands out:

If no item stands out for you on your first pass through it, then all the outstanding items on that page are dismissed without re-entering them. Use your highlighter to mark dismissed items.

This is where the system finally gets rid of all the items which you entered without evaluation, but which the system has sifted and found wanting. This may happen very quickly (for instance if you have entered a long list of books you are thinking of reading), but more usually quite slowly.

Please take the rule not to re-enter these items seriously. It doesn’t mean you can never re-enter them, but you should let some time pass before you do and consider carefully why they were rejected, whether they really need to be done at all, whether the time is ripe for them to be done, whether they distract from your main goals, and any other factors. When you do re-enter a dismissed item, it is often best to break it down or re-phrase it in some way.

=Highlighting rejected items helps you to review them easily.=

*Remember that this rule does not apply to the page on which you are still writing items (i.e. the last page).*

*** Once you’ve finished with the last page:

*re-start at the first page that is still active.*

I mark pages that are no longer active with a cross at the top outside corner of the page, and put a circle round the cross when there are no active pages before that page. That makes it easy to find the first active page. You may find the number of active pages varies considerably from time to time. At the time of writing I have nine, but it’s varied from three or four up to fifteen.

/This system can be quite addictive (at least that’s what I’ve found) so you may find it a good idea to set strict working hours. Stop dead when the time is up, and start again at the same place when it’s time to start again. I admit I am not very good at following this advice myself!/

*** Backlogs:

You may already have some backlogs of work when you start this system. If you have a backlog of tasks then I recommend you enter all the tasks into the system in one go and let it sift them. If you find some of them end up being rejected then you need to ask serious questions about whether they really need doing at all.

However with backlogs of email and paper there is a danger that a large backlog may get in the way of the efficient processing of newly arriving emails and papers. So I recommend moving your backlog(s) into separate folders and having tasks called “Email Backlog” and/or “Paper Backlog” as well as the standard “Clear Email” and “Clear Intray”.

*** Why it works:

The system works by providing a framework which balances the rational and intuitive parts of the brain.

If we try to run our lives with our rational brain only, we will tend to make plans which are subverted by our own minds because our minds don’t work on purely rational grounds. Most of us have experienced occasions on which we know (with our rational brain) that we would be better served to do certain things, but nevertheless our natural inclination is to reject them.

On the other hand, if we try to run our lives by following our natural inclinations only we will have a strong tendency to drift, become impulsive and act irrationally.

However when these two ways of thinking are in balance we are able to make rational decisions which are fully in accord with our deeper feelings and emotions. The Autofocus system provides a framework which enables this. Although I talk about “the system” making the choices, what I really mean is that the system provides a framework which allows us to make these balanced decisions ourselves in a non-stressful way.

*** Dos and Don’ts:

- =DO= trust the system. Because of the way it is structured it will help you to produce better decisions than you would unaided.

- =DO= use common sense. If something comes up which needs doing immediately, do it immediately.

- =DON’T= try to pre-edit what you put into the system. If you do, you will be using a less efficient means of prioritising than the system itself.

- =DO= expect things to move at different rates. Some things will move fast, some slowly, some will stop for a period, and some will be rejected altogether. This is how it’s supposed to work.

- =DON’T= use this system for things which need to be done at specific times of day. These might include preparing meals, music practice, shutting up shop, etc.

- =DO= read through all the outstanding items on your list when you come back to it after an extended break. This will help your mind to get an overview of what needs to be done.

- =DON’T= forget to put follow-ups and reminders into the system. These are an essential way of keeping track of your work.

DO include plenty of creative tasks such as “Think about…”, “Investigate…”; “Discuss…”; “Review…”

- =DO= put the date next to the first item you add each day. Although not essential to the system, it helps you to monitor progress.

- =DON’T= leave your list without some means of recording ideas and tasks which come into your mind.

- =DO= use some means of bringing forward tasks which can only be done at a future date (Tickler file, Outlook reminders, Calendar, etc.)

- =DO= use a separate notebook and list for each location, e.g. Home, Workplace.


