# -**- mode: org; coding: utf-8 -**-
#+begin_comment
 Setup Files:
   For Cloned Versions of this template, replace file/paths below
   with file/paths to your own custom setup files (which you could 
   convienently clone from the example setup files provided in
   ../org-templates/ directory...

 NOTE: 
   #+CATEGORY: is specified within log-book.org setupfile.
   If you need to change the category do it in log-book.org
   or your cloned version of it...
#+end_comment

#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/simple-log-book.org
#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/default-tags.org

#+TITLE: HAP - Simple LOG Notebook Skeleton
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2022-01-26 Wed>
#+TEXT: Created: <2022-01-26 Wed>
#+FILETAGS: templates logs

#+DESCRIPTION: HAP - Modular Emacs Org Mode Simple Log Notebook Template.  This is a minimalist version of: HAP_General-Log-Book-Skeleton.org (a Full Featured Look Book Skeleton Template).  This log book does not have all the bells and whistles because sometimes you need a simple way to record your time on tasks, etc. but not necessarily for HUGE projects, etc... Use this for quick stuff... You are expected to know what is going on in here... (but if not you have the General Template to learn from)... This simplified log book skeleton is also not set up or intended to be exported to PDF and/or published... 

* Begin Log:
:PROPERTIES:
:CUSTOM_ID: HAP-general-log-notebook-skeleton-1
:END:
** 2022:
*** NEW log: <2021-03-29 Mon> Generic Title /(General Log Entry Template)/
:README:

- Since you created this new log entry you are probably in the middle of a task related to it right now!  Go ahead and punch the clock right now as well, to start recording your time! The following Commands are defined below for you to remember and use to track your time:

  + *C-c C-x C-i* - Start Clock /(Begin OR Resume Clocking Current task)/

      This creates a new :CLOCKING: Time Card Entry that looks like this:

      Do this now... Start recording your time girl!  Be in control of your life!

     After doing the above, you can go away and do some work, leaving this log note to visit other files and work on them etc. The clock will be recording your time all the while... You will see in your mode line the elapsed clock time as you work...

  + *C-c C-x C-j* - Return back to the Heading where you started the clock...
      You do this after you have worked on a task for a while and you need to come back to the time card /(this Log Entry Heading)/ and stop the clock before going off to do something unrelated to the log entry...

  + *C-c C-x C-o* - *Stop the Clock* /(to stop clocking your time on task)/
       This *Finalizes the Time Card Entry* within ~:CLOCKING:~ /(created earlier when you started the clock)/... The completed time card entry looks like this:

       The above entry shows start timestamp, end timestamp, and total time worked during this segment...  As you can see from the example above I left the clock running all day by accident.  If you do something like that you can always come back and directly edit the clock times by hand to amend them...  After changing clock times or dates, etc. type the following to *Update the Time Card Entry*:
            *C-c C-c*
       and the total time will change at the end showing your new calculated time...

       If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

       When you are all done with this Log Entry mark it *DONE*

  + *C-c C-x C-q* - Cancel Current Clock /(in case you accidentally started it)/

       This removes currently running clock and forgets it...

 + *C-c C-x C-d* - Display Clocking Info: /This will show elapsed times to the right of headings.../

- Once all of this has become routine for you, go ahead and remove this ~README~ drawer from this template... That way it does not get copied when you need to clone new log entries...

:END:

This Log Entry is about: Yadda... Yadda... Yadda...

\newpage

**** NEW Reference:

- *Link to Project:* [[][] ]

- [[URL][Link Name] ] *Heading:* /(comment)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] /(_)/

- [[][] ] /(_)/

- [[][] ] /(_)/

\newpage

**** NEW Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW Summary: [0/3]
:README:
   This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

   Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...

   Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...
:END:

Yadda... Yadda... Yadda...

1. [ ] *__:*

2. [ ] *__:*

3. [ ] *__:*

\newpage

**** NEW Details:
***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

* Meta:

This is a *simplified Log Book skeleton* for recording spur-of-the-moment tasks that may or may not be part of a larger project.  For simple tasks that may still need an easy way to record your time... 

- *Note:* /If you do have tasks to record that are part of a much larger project you should probably be using: HAP_General-Log-Book-Skeleton.org /(which is also found within the same directory that this file is in)/

Use this as a quick way to start logging things that may or may not be part of a Large Project, /(or possibly smaller "yak shaving" tasks that you don't want cluttering up your Larger Project's Log Notebook with)/.

There are no instructions in here for how to use this skeleton... Use the *HowTO:* section within HAP_General-Log-Book-Skeleton.org from this same directory if you need help. /(both log book Skeletons work pretty much the same way in that respect)/

In essence, you are expected to know what is going on in here... /(but if not you have the General Template to learn from)/... This simplified log book skeleton is also not set up or intended to be exported to PDF and/or published... It is for internal *Emacs Org-Mode* use only...

\newpage

** Templates:
*** NEW 🗓 LOG: <2021-03-29 Mon> Generic Title /(General Log Entry Template)/
:README:
   - *Go To One of the HEADINGS Below:* /(Summary, Details, or Sub Headings)/

      =Punch the Time Clock= At the heading And then begin working on a task related to that Heading... =Your Time IS being Recorded Now= 

   - =Use These Commands:= /as you work to keep track your time.../

      + *Clock IN:* ~C-c C-x C-i~ 

                    /(Begin OR Resume Clocking Current task)/

                    This creates a new :CLOCKING: Time Card Entry just
                    underneath the HEADING...

                    Do this just before starting work on the task... 
                    Be in control of your life!

                    After doing the above, you can go away and do some 
                    work, leaving this heading, log note, etc. to visit 
                    other files and/or work on them etc. The clock will 
                    be recording your time all the while... You will see 
                    in your mode line the elapsed clock time ticking away 
                    as you work on a task /(hopefully related to this clock!)/
                    and NOT Yac Shaving or being sidetracked!!!

      + *RETURN to Clock Heading:* ~C-c C-x C-j~

                        /Go back to the place where you started the clock.../

                        You do this after you have worked on a task for a 
                        while and you need to come back to update the item's
                        info etc., and/or stop the clock before going off to 
                        do something else unrelated to the log entry...

      + *Clock OUT:* ~C-c C-x C-o~ /(to stop clocking your time on task)/

                      This *Finalizes the Time Card Entry* within:
                      ~:CLOCKING:~ /(created earlier when you started the/ 
                      /clock)/...

                      The Clock Entry changes showing start timestamp, end timestamp, and total time worked during this segment...  

                      =Please DON'T Forget= /Like I often do, LOL.../ i.e.,
                      Leaving a clock running all day by accident, or worse,
                      leave it dangling with the file closed only to open it
                      again and get that nasty *Org-Mode Message:* /"What do/
                      /you want to do with this?"/ If you do something like 
                      that you can always come back and directly edit the 
                      clock times by hand to amend them...  After changing 
                      clock times or dates, etc... Whatever...

                      ="Onward We Row Mates... Through the log jam!"=

      + *Update Time Card Entry:* ~C-c C-c~ 

                  This command will change the total time at the end showing 
                  your new calculated time...

                  If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

      + *Clock Out & Mark Items Done:* ~C-c C-t~

            When you are all done with a Log Entry use the above key 
            command to mark its Heading *TODO* tag to: *DONE* /(Most of the/ 
            /time this will ALSO clock you out if you are still clocked/ 
            /into the item... But not allways in my experience.../  
            So make sure you are also clocked OUT of an Item After 
            marking it DONE... Type: ~C-c C-x C-j~ to check this...
            /(if no running clock it will tell you and place your/
            /cursor at the heading where you LAST CLOCKED OUT)/

      + ~C-c C-x C-q~ *Cancel Current Clock:* /(in case of accident)/

                      This removes currently running clock and forgets 
                      any time accrued or associated with it...

      + ~C-c C-x C-d~ *Display Clocking Info:* 

                      /This will show elapsed times to the right of headings.../
                      =Warning!= Using this command will CLUTTER ALL the headings
                                within your org file with those timestamps!!!

   - Once all of this has become routine for you, =go ahead and remove this= ~README~ =drawer from this template=... That way it does not get copied when you need to clone new log entries...
:END:

This Log Entry is about: Yadda... Yadda... Yadda...

\newpage

**** NEW Reference:

- *Link to Project:* [[][] ]

- [[URL][Link Name] ] *Heading:* /(comment)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] /(_)/

- [[][] ] /(_)/

- [[][] ] /(_)/

\newpage

**** NEW Time Card:

#+BEGIN: clocktable :scope tree3 :maxlevel 6 :tstart "<-1w>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW Summary: [0/3]
:README:
   This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

   Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...

   Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...
:END:

Yadda... Yadda... Yadda...

1. [ ] *__:*

2. [ ] *__:*

3. [ ] *__:*

\newpage

**** NEW Details:
***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@web1:~$ 
       admin@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@web1:~$ 
       admin@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       user@home:~$ 
       user@home:~$ 
      #+end_src

\newpage

***** NEW New Item 2 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@web1:~$ 
       root@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@web1:~$ 
       admin@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       user@home:~$ 
       user@home:~$ 
      #+end_src

\newpage

***** NEW New Item 3 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@web1:~$ 
       root@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@web1:~$ 
       admin@web1:~$ 
      #+end_src

- [ ] *__:* /(__)/
   
      #+begin_src conf
       user@home:~$ 
       user@home:~$ 
      #+end_src

\newpage


