# -**- mode: org; coding: utf-8 -**-
#+TITLE: HAP - Technical Book Project Skeleton
#+EXPORT_FILE_NAME: HAP_Untitled-Tech-Manual.pdf
#+TEXT: Copyright © 2022 Harmonic Alchemy Productions & Others
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2022-10-18 Tue>
#+TEXT: Created: <2020-07-30 Thu>
#+TEXT: Last Published: <Not Published>
#+FILETAGS: templates reference_books @projects unpublished

#+DESCRIPTION: HAP - Tech Manual Book Project Skeleton with generic basics already done. Great for documenting technical projects, large or small... Also great for organizing, handling caveats, trying different methods, etc. All while building a sound outline of support docs, steps, best practices... and publishable as a PDF Book suitable for eBook readers... (easily modified for publishing in other eBook formats or for the web)

#+BEGIN_COMMENT
=Setup Files:=

   For Cloned Versions of this template, the file/paths below will be relative
   to your parent project directory and as such, should be all set to your new: ~.../your-technical-book-project/org-templates/~ directory...

=NOTE:= 

   ~#+CATEGORY:~ is specified within ~ref-book.org~ SETUPFILE.
   If you need to change the category, do it in your cloned version
   of ref-book.org...

   *SETUPFILE:* ~default-tags.org~ is where tags are set for this project...

   *SETUPFILE:* ~latex-tech-pdf.org~ is for LaTeX Export Configurations 
              to produce a PDF version of your Fiction Book...
#+END_COMMENT

#+SETUPFILE: ./org-templates/ref-book.org
#+SETUPFILE: ./org-templates/latex-tech-pdf.org
#+SETUPFILE: ./org-templates/default-tags.org

:READ_ME_FIRST:
☞ =Instructions:= /(How to Install & Use This Template)/

To use *HAP_Technical-Book-Project-Skeleton.org* /(Org-Mode Reference Book Project /Template)/ for your own projects, perform the following steps: 

/Use the org-mode Checkboxes to Help You Keep Track of Progress/

1) [ ] *Clone a Copy of This File:* 

      Put your clone where you normally organize your writing 
      projects. *Place it within its own master folder... It is*
      *Important to keep this file within its OWN enclosing folder!* 

      Name the project's master folder to reflect your Reference book 
      project's title... /(what you renamed this .org file to)/...

      =Other Files/Folders will be placed within this master folder...=

2) [ ] *Create:* ~./media~ *sub folder in your new project's Master Folder:*

      Create this new directory /(in your master folder as a sibling of/
      /this file).../ Any external documents or images referenced by your
      book(s) should be placed within this ~./media/~ directory...

      This single ~./media~ directory will serve media and external attachments 
      for all of the ~.org~ docs within this =MASTER FOLDER= /(parent directory)/...

      =Note:= You DON'T need to create or copy the ~./auto/~ directory...
             That directory will be automatically created the first time
             you export this ~.org~ file to ~.PDF~...

3) [ ] *Copy/Clone:* ~./org-templates~ /(and all contents)/ *to your Master Folder:*

      Copy this directory to your book's MASTER FOLDER,
      /(i.e., as a sibling/ /of this .org file).../ 

      =Note:= The SETUPFILES Within this directory which are called out and 
            included by this .org file /(above)/ must stay within this
            directory...  

            Other SETUPFILES within this directory are used by other book 
            project templates and are not needed for this Technical Book
            Project... You may remove them if you wish...

            However, consider If you clone another ~HAP_<book-template>.org~
            file into this MASTER PROJECT FOLDER it will pick up its
            associated SETUPFILES automatically, so consider that if/when
            you decide to delete other UNUSED SETUPFILES... They are small
            text files not bothering you or your operations...

4) [ ] =Start Sketching Out Your Technical Book NOW Before You Loose It!=

      =NOTE:= You may be doing this because you have technical information that
             needs to be writtin now before you forget!  =Right?=  Therefore...
             as soon as you are done with the first steps above, =STOP= and go immediately to the:

                   ~💡 Ideas Scratchpad Refile / ☞ Start Here!~ 

             section and read the ~:README:~ directly under that heading...  
             Then write your ideas down quickly /(as per the README instructions)/ 
             to get your information recorded before you forget it...  

             Later, After you have all your ideas sketched out and you are 
             ready to be in an ="organized mood"= /(rather than creative mood)/ 
             /This does not imply being organized cannot be a CREATIVE PROCESS/ 
             Then it is time to:

             =Come Back Here And Finish Setting Up Your Project...=

             *This Project Template is HUGE!*

             *Your Muse Can Easily Loose Her Inspiration!*

             =The ☞ Start Here Section is Your Remedy= 

             =Do That first!=

5) [ ] *Finish Setting up this Project LATER...* [0/3]

    - [ ] *Change the* ~#+TITLE:~ *directive at the top of this file:* 

          Change to: /"your Technical Book Project's Title"/

    - [ ] *Change the* ~#+EXPORT_FILE_NAME:~ *directive at the top of this file:*

          Change to: /"your-tehcnical-Book-Project's-Title.pdf"/
          This will be the file name(s) produced during export thence forward
          /(including auto generated files: .tex, etc...)/

    - [ ] *Change the* ~#+TEXT: Copyright © 2022:~ *directive top of this file:*

          Change to: /"Copyright © your info here"/ You are the copyright
          owner of your own documents created from clones of these master
          templates... /(but these MASTER Template Files are to stay under/
          /Harmonic Alchemy Productions copyright. Any Attribution to me/
          /for the template structure of your published docs will be/
          /appreciated... but unnecessary... Thanks! ;-)/

    - [ ] *Change the* ~#+AUTHOR:~ *directive at the top of this file:* 

          Change to: /"your NAME"/

    - [ ] *Change the* ~#+EMAIL:~ *directive at the top of this file:* 

          Change to: /"your EMAIL"/

    - [ ] *Change the* ~#+DATE:~ *TIMESTAMP at the top of this file:* 

          Put your cursor on the TIMESTAMP: /i.e.,/ <2022-10-05 Wed>
          and type: ~C-c . . RETURN~ The TIMESTAMP will update to NOW.
          Do this whenever you update your doc to show last date
          it was changed or modified...

    - [ ] *Change the* ~#+TEXT: Created:~ *TIMESTAMP at the top of this file:* 

          Put your cursor on the TIMESTAMP: /i.e.,/ <2022-10-05 Wed>
          and type: ~C-c . . RETURN~ The TIMESTAMP will update to NOW.

          =LEAVE THIS DATE ALONE after Setting It The FIRST Time=

          This Date reflects the time/date that you first created this
          new document It should NEVER change after that...

    - [ ] *Change the* ~#+TEXT: Last Published:~ *TIMESTAMP at Publish Time:* 

          =Don't Change This UNTIL You Have Actually Exported This File=
          /(as a PDF or HTML, etc. and have PUBLISHED it publically somewhere)/

          Until that publishing time comes leave it alone as: <not-published>
          
          As soon as this is published or re-published, Replace the
          <unpublished> placeholder with a REAL TIMESTAMP by typing:
          ~C-c . . RETURN~ The new Last Published: <TIMESTAMP> will
          appear in place... Do this EVERY time you publish or update
          an existing publishing... /(this will help you keep track)/

    - [ ] *Change the* ~#+FILETAGS:~ *directive at the top of this file:* 

          Add your own tags that match the context of your Log Book...
          
    - [ ] *Change the* ~#+DESCRIPTION:~ *directive at the top of this file:*

          Compose /Your-Technical-Book-Project's Description/ as a short 
          paragraph here...

    - *The* ~./media~ *Directory is ALL Set:* 

         Any external documents or images referenced by ANY book projects
         located within this MASTER FOLDER, should be placed within this
         ~./media/~ directory... This single ~./media~ directory will serve
         media and external attachments for this and any other related
         ~.org~ files you may end up creating here, as well as being
         the media repository used by LaTeX during publishing...

    - *Purpose of the:* ~./auto/~ *Directory:* /(you do not need to copy this)/

         This is or will-be an auto generated folder where your output ~.PDF~ 
         files are created and placed during LaTeX export. You DO NOT need 
         to copy this folder as it is auto generated during org-mode LaTeX 
         processing...

         LaTeX processing will not delete any prior files contained here... 
         Some of them will be updated, but will have backups...  Any files 
         you place within this folder will NOT be lost, unless you delete 
         them... This folder is a good place to store other temporary files 
         you may be creating, generating.. etc...

    - *Purpose of the:* ~./org-templates~  *Directory:*

         The files in here are automatically linked and included within this
         template. You don't need to change those settings unless you wish to
         customize the already customized tags, and export options.

         /They are allready set up correctly for the Technical Book genre, and/
         /the Category is all set as well... But you can and may modify the/
         /SETUPFILES to fit your needs.../

         Other SETUPFILES within this directory are used by other book 
         project templates and are not needed for this Technical Book
         Project... You may remove them if you wish...

         However, consider If you clone another ~HAP_<book-template>.org~
         file into this MASTER PROJECT FOLDER it will pick up its
         associated SETUPFILES automatically, so consider that if/when
         you decide to delete other UNUSED SETUPFILES... They are small
         text files not bothering you or your operations...

6) [ ] =Ongoing Planning / Writing Your Technical Book:= 

      /Change headings and structure to match your project's outline/ 
      /sections-chapters, figures, etc.../

      *Start doing the Tasks within the Tasks section:*

      =Have fun doing this...=

7) [ ] =Export/Publish to PDF File:=

      The *In-Buffer Settings* specified by the SETUPFILES above will 
      get this file looking good when exported as a Standard PDF file.  
      Once you have your project directory all set up as above you are 
      ready to export your first PDF as a test run...

         *Issue the following Emacs command:*

            ~M-x org-latex-export-to-pdf~

         *OR* If You Enabled *Xah-Fly-Keys* /"Command Mode"/ Try Shortcut:

            ~SPACE e p~

         *OR Export to OTHER Formats:*

            ~C-c C-e~

            /(a pop-up will show allowing you to choose export method)/

      After *AucTeX* is done parsing/compiling etc., new files by the name of: ~HAP_Untitled-Tech-Manual.pdf~ -and- ~HAP_Untitled-Tech-Manual.tex~ 
      will appear within the same directory as this file...

      Subsequent repeated calls to the above command will overwrite your existing ~HAP_Untitled-Tech-Manual.pdf~ -and- ~HAP_Untitled-Tech-Manual.tex~ 
      files! /(make backups first if needed!)/
      You should probably copy these files to the ~./auto/~ directory as 
      well for safe keeping as backups...

      =If you chose the last option above= LaTeX will output files with other
      extensions for those other output formats... =NOTE:= SETUPFILES have not
      been created yet for other eBook formats.  /(This is a work in progress)/

      =If YOU EXPERIENCE LaTeX ERRORS:= 

         *Consult Buffer:* ~*Org PDF LaTeX Output*~

=These Instructions Were Last Modified:= <2022-10-18 Tue> 

So far things are pretty basic PDF... We will get fancy with other formats later... 
I promice... I have to do all this documentation first!
/(As you can see, if you been following for the past couple years, things are/ 
 /getting done! Albeit Slowly)/

=Please Open an ISSUE At:= https://github.com/harmonicalchemy/modular-emacs/issues
   
Please use Issues to Ask Questions, Report Problems/Bugs etc., and Suggest Ideas for Improvement... =You guys are my Product Managers=  I am only a User of ONE "seat". 
Other folks UX metrics are sorely needed!! Thanks!

=Enjoy!= - Alisha Awen
:END:

* 💡 Scratchpad Refile:           :noexport:
** ☞ Start Here!
:README:
   This Section is mainly to accommodate "seat-of-pants" writers
          /(Of Which I Have Been Accused Of.../
           /But I Also Crave The Planning Stuff)/. 

   I often come here for my [[https://projects.csail.mit.edu/gsb/old-archive/gsb-archive/gsb2000-02-11.html]["yak shaving"]] adventures...

   Use this: "*💡 Scratchpad Refile ☞ Start Here!*" section as a 
   quick place to document ideas and inspirations as they come 
   along... You can refile them later... 

   Even if your quick inspiration was intended for elsewhere?,
   /(e.g., You become bored documenting tedious technical/ 
   /information when suddenly, out-of-nowhere, an idea for a/ 
   /new sci-fi scene in that screenplay episode you had in the/ 
   /back of your mind all day!, etc.)/

   =Ummm.... Parallel Universe?=

   =Sure!= You can put anything in here! We've got that covered 
         for you in this Start Here spot. %^)

   Use this section to quickly capture inspired at-the-moment 
   ideas =While they are still fresh in mind=

   =How To Use ???= 

      /Simply Come directly here and do what ever you want.../
      /"Your Crazy Daze are Covered!" Yay!/ 

   =The following Shortcuts= Will Help you Get Started as 
   Quickly as Possible:

   - [ ] *Copy/Clone:* =Example Idea= *Heading Below:* 

         =Copy the Heading AND ALL ITS CONTENTS=

         /Change your Clone's Title to Your Own Title/

   - [ ] *Change the timestamp on your Clone Entry:* [0/1]

         =Type:= ~C-c .~ while cursor is sitting on the timestamp

         /i.e., Press: ~Ctrl-c~, let go, and then type a Period/ ~.~

         A date chooser panel will pop up...

     + [ ] *Press* ~ENTER~ *to auto accept today's date and time.*  

            The existing timestamp will change to TODAY...

   - [ ] *Advance your cursor and Start Writing!!!*

          Advance your cursor few more lines down to some fresh 
          empty space and Start Typing Your Story Idea Like Mad!!! 

   - [ ] *Don't stop Writing!* 

          Don't worry about formatting or organizing it until later, 
          after all your inspiration has passed and you are ready 
          to organize...

   - [ ] =TODO After You Are Done Writing:=

        + [ ] *Adjust Space:* 

               Adjust space between your headings and your 
               fantastic ideas below them it to one single 
               blank line...

        + [ ] *Further organize things as needed...*

               If you become inspired to write while organizing... 
               Do that first and come back later... Don't scare 
               away your muses when they beckon! Get your story 
               down first! No matter what state it may be in at 
               first... =GET IT DOWN=

        + [ ] *You Are Free To Go Out And Play Elsewhere Little Grasshopper*

               If after writing... You don't feel like organizing 
               now? =NO PROBLEM=... But come back later and organize 
               things... =OK?= Don't create a swamp in here! 
               /And don't forget to take/ /your bath tonight... ;-)/

   Having done the simple steps above any time you get inspired, you 
   will be able to tell your grand children.. "I got my first spark 
   of an idea for that book back in Year, Month, Day, time, second" 
   /(50 years later!)/ Now that is being organized! LOL
:END:
*** NEW 💡 <2020-06-07 Sun> My New Business Idea! /(example)/ 
/"Yeah We've Heard That One Before"/
:README:
   This is a dummy example of some crazy idea that you may have 
   gotten at the spur of the moment, while you were doing something 
   elsewhere within this project...  After you are done getting as 
   much of the idea as you initally can then you can simply go back 
   to what you were doing before the inspiration segue tore you away... 
   You might want to schedule this as a todo item before leaving though...

   Later when you are free you can come back to file this or place it 
   where it belongs.  In the case of the note below it would probably 
   go in a research folder of a Sci-Fi related project...
:END:

=Copy/Clone this Boilerplate Template NOW= And Change your clone's Title.. 

=Then Quickly Get Started Writing Down your FRESH NEW IDEA=

\newpage

* 🕮 Book: /(Name of Book)/             :export:
** NEW 📃 Synopsis: /(or Introduction:)/
:README:
   =Use this space to write the main synopsis of your technical work=

   You can write anything you want here but it is highly recommended 
   to use the award winning *"Snowflake Method"* created by [[https://www.advancedfictionwriting.com/][Randy Ingermanson]] 
   of Ingermanson Communications, Inc. 

   =YES!= It is a perfectly great idea to use Randy's Snowflake Method for 
        the development of Reference or Technical Books...
        /(Companies spend tons of money sending their top execs off to/ 
        /"Vision Retreats" for this same reason)/ It will Make them Better
        at what they do day-to-day...

   Snowflake concepts apply just as well for real-worlds as they do for  
   make-believe worlds... /(the worlds don't care or notice the difference)/

   The steps within the *⏰ Tasks:* Binder follow guidelines within Randy's
   book... Boilerplate forms have been set up for you to fill out while 
   reading his book to get a deeper understanding behind these dry forms 
   and worksheets...

   - [ ] *Go to the:* =⏰ Tasks:= *Binder and do the:* =📃 Synopsis Tasks:=

   - [ ] *After Completing Tasks Mark Them:* ~DONE~

   - [ ] *Place Resulting Synopsis in Here:*

         Copy the one-page skeleton from: =Step Three= of Synopsis Tasks
         to HERE to serve as this books official Synopsis...

   When you are done with these Synopsis tasks, you will have 
   completed half the battle of writing your technical work! 
   Everything else you write will flow out of that initial seed...

   You will be coming back here to consult these notes for many 
   things as you promote and publish your book.
:END:

=Synopsis Content:= Yadda... Yadda... Yadda...

\newpage

** NEW 📃 Front Matter:
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space for holding all of the Front Matter related 
   content of your book... 

   Add Book Cover Art, Copyright Info, Publishing Info, etc. here... 
   Only these basic elements are included in this Front Matter 
   section which may or may not be exported to published media...
:END:

=Front Matter Content=... yadda... yadda... yadda...

\newpage
** NEW 📃 Preface: /(or Introduction - Optional)/
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space to write the *Preface* / or *Introduction* to your book... 

   Optionally you may wish to include a *Table of Contents*... 
   However there are automatic ways that =Emacs Org-Mode can configure TOCs= 
   as well...
:END:

=Preface or Introduction Content:= 

   yadda... yadda... yadda...

\newpage

** NEW 📖 Chapter: ~1~ Org-Mode Publishing Tricks /(example template)/
:README:
   *📖 Chapters* are the *Top Level Headings* within the *🕮 Book:* Binder 
   of this *Emacs Org-mode* Book Publishing project...

   =Usage:=

   - [ ] =Clone This:= *📖 Chapter/Episode:* ~#~ /(Master Template)/ 
          =Copy ALL its contents= and =paste= it as a child Item 
          in the *🕮 Book:* Binder of this Book Publishing Project... 

          Do this whenever you need to start a new chapter...

   - [ ] =Edit Your New Clone:=
          The structure of this template is all set up for 
          you ahead of time to allow you to immediately begin 
          writing...  

          Replace titles to suit your needs, but keep the 
          structure of *Chapter / Scene (sub-chapter)* intact... 
          /(i.e., change names only...)
:END:

This is a secret Org-Mode Tutorial /(presented here as an EXAMPLE Chapter)/ for a technical book...  Some good tips are in here so you may want to save this somewhere else before removing or re-writing it to use as a chapter within the technical book you have commondeerred this project skeleton for...

*** NEW ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      + To Create a Link Type: ~C-c C-l~ 
         /(then paste: ~link~ & type: "description")/

         =-or-= Simply Fill in the Template Link Placeholders 
              Below & copy/paste more placeholders as 
              needed... ;-)

      + To Open a Link Type: ~C-c C-o~
:END:

- [[https://orgmode.org/worg/org-tutorials/index.html][Org tutorials]] - /WORG/

- [[https://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html#org42aa49f][Pretty Fontification Of Source Code Blocks]] - /WORG/

- [[https://orgmode.org/worg/library-of-babel.html][Org Library of Babel]] - /WORG/

- [[https://orgmode.org/manual/Working-with-Source-Code.html#Working-with-Source-Code][Working with Source Code]] - /Org Manual/

- [[https://www.cheme.engineering.cmu.edu/directory/bios/kitchin-john.html][John Kitchin]] - /John's Home Page @ Carnegie Mellon/

- [[https://github.com/jkitchin/org-ref][ORG-REF]] - ~JKitchin@Github~

- [[https://www.youtube.com/playlist?list=PL0sMmOaE_gs3GbuZV_sNjwMREw9rfElTV][Org-Mode YouTube Presentaions PLAYLIST]] - ~JKitchin@YouTube~

- [[https://youtu.be/fgizHHd7nOo][Org Mode is Awesome!]] - ~JKitchin@YouTube~

- [[https://kitchingroup.cheme.cmu.edu/blog/2017/01/29/ob-ipython-and-inline-figures-in-org-mode/][ob-ipython and Inline Figures in org-mode]] - /The Kitchin Research Group/

- [[https://kitchingroup.cheme.cmu.edu/blog/2017/05/04/An-emacs-lisp-dsl-for-gnuplot/][An emacs-lisp dsl for gnuplot]] - - /The Kitchin Research Group/

- [[https://youtu.be/SzA2YODtgK4][Getting Started with Org Mode]] - ~Harry Schwartz@YouTube~

- [[http://howardism.org/Technical/Emacs/literate-devops.html][Literate DevOps]] -  /Article by: Howard Abrams/

- [[https://youtu.be/dljNabciEGg][Literate DevOps with Emacs]] - ~Howard Abrams@YouTube~

- [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][Beautifying Org Mode in Emacs]] - /Article by:/ ~Diego Zamboni~

- [[https://www.linuxjournal.com/content/org-mode-latex-exporter-latex-non-texers][The org-mode LaTeX exporter: LaTeX for non-TEXers]] - /Article on LINUX Journal/ 

- [[][] ] -

\newpage

*** NEW 📄 Chapter Introduction: /<replace with topic name if needed>/

Here are some *Org-Mode publishing tips and snippits* I have found along the way...  Some of them may get incorporated more formally later /(with docs, etc.),/ but for now... you will have to =discover these treasures below= within this =example chapter=...

\newpage

*** NEW 📄 New Topic <replace with topic name>

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

*** NEW 🗒 Background Notes:
:README:
The *Background Notes* section of a chapter is a place where you can add notes, ideas, instructions, whatever... close at hand within the chapter, and not have to worry about any of it getting exported and or published to the final output product...  

Nothing within this section will be exported... not even the Background Notes Heading itself.  Use this section any way and for any purpose you wish for things related to the chapter heading that contains it...

The example Notes below have been timestamped as a way to suggest organizing TODO items for a particular chapter you may find yourself working on, or researching... *Use / replace the notes below with / for your own schemes*...
:END:
**** 🗒 Note 1: <2020-05-10 Sun>

1. Enumerated List Item A

    * Enumerated List Item B

       + Enumerated List Item C

       + Enumerated List Item D

2. Something New...

- Bullet checkbox Test one...

   + [ ] Checkbox List:

   + [ ] 

\newpage

**** 🗒 Note 2: <2020-05-10 Sun>

Each new note needs to get its own heading and initial timestamp...

****** Quid Novi?

Quid Novi? Lorem Ipsum dolor sit amet,consectetur adipisicing elit, sed doeiusmod tempor incididunt ut laboreet dolore magna aliqua. Ut enim adminim veniam, quis nostrudexercitation ullamco laboris nisi utaliquip ex ea commodo consequat.Duis aute irure dolor inreprehenderit in coluptate velit essecillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatatnon proident, sunt in culpa quiofficia deserunt mollit anim id estlaborum.

\newpage

**** 🗒 Phasellus orci: <2020-05-10 Sun>

Etiam tempor elit auctor magna. Nullam nibh velit, vestibulum ut, eleifend non, pulvinar eget, enim. Classaptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Integer velit mauris, convallis acongue sed, placerat id, odio. Etiam venenatis tortor sed lectus. Nulla non orci. In egestas porttitor quam. Duis nec diameget nibh mattis tempus. Curabitus accumsan pede id odio. Nunc vitae libero. Aenean condimentum diam et turpis.Vestibulum non risus. Ut consectetuer gravida elit. Aenean est nunc, varius sed, alquam eu, feugiat sit amet, metus. Sedvenenatis odio id eros.

|----------+-----------+-----------+-----------+-------------------|
| Inceptos | Venenatis | Convallis | Curabitus | Nunc vitae libero |
|----------+-----------+-----------+-----------+-------------------|
| test 1   | test 2    | test 3    | test 4    | test 5            |
|----------+-----------+-----------+-----------+-------------------|

Yadda, yadda, yadda. etc...

\newpage

* 🔍 Research:                          :noexport:
** 🗓 Log Book:
:README:
   Use this space to add time stamped log note entries for any 
   pourpose you may need while you are planning, writing, or 
   publishing your book...

   =USAGE=

      =Place New:=   *🗓 LOG:* /<timestamp>/ *Entry* /(Log Entry Template)/ 
      =Items From:=  *⎘ Templates:* Binder
      =Into This:=   *🗓 Log Book:* Binder
:END:

=ADD a NEW Items= /(as per :README: above)/ right here in this Log Book Binder whenever you need to create a new Log Entry...

\newpage

** 💡 New Topic Ideas:
:README:
   Use this space to add new topic ideas that come up as you are
   researching ideas.  These topics will eventually get put into
   chapters were they belong.  This Research Binder is where they
   may get initially created...

   =USAGE=

      =Place New:=   *🔖 New Topic Idea:* 
      =Items From:=  *⎘ Templates:* Binder
      =Into This:=   *💡 New Topic Ideas:* Binder
:END:

=ADD a NEW Items= /(as per :README: above)/ right here in this New Topic Ideas Binder whenever you need to write up a new topic. /Even at the spur of the/
/moment while doing something else./ Get the idea down... Come back to finish
later... You will know anything set to ~:ACTIVE:~ within this binder needs to
be worked on.

\newpage

*** NEW 💡 New Topic /(clone this)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

** 📒 Yak Shaving:
:README:
   =What is Yak Shaving doing in your Research Folder?= Just as the name 
   implies, this is a place that may have no business being in your book, 
   but nevertheless may be something you need to research on the side in 
   order to get your book written.. 

   Things to put here may end up in chapters but you don't know which 
   chapters that may be at this point, so you cannot use a Chapter's 
   Background Notes section for these cases...

   Use this section as a place to save and organize new-ideas while you 
   figure out what they may be for, and where they may eventually go...  

   This section is a great place to start if your are importing existing 
   docs written in markdown, or Open Office, or what ever... import the 
   text from those external docs here first... Then you can organize them 
   here while you figure out how they fit in the larger context of a book 
   project...

   The format for this section is anything you like.. And you may put 
   anything you like in here.. There are NO Templates to clone for this...
   =MAKE IT HOW YOU WANT TO MAKE IT HERE... ;-P=

   Some of the things written *seat-of-the-pants* within the *Start Here* 
   section may end up in this *Yak Shaving* section later when you are 
   ready to organize things further... /(after inspiration)/
:END:
*** NEW Yak Shaving Heading One:

Note: This is an example of some documentation or research you need to do, the result of which will not be included in your book but will be used as a resource necessary for the creation and or publishing of your book... Add what you need here... 

Use this section's top level heading outline structure.. Create sub-level headings as needed for your purposes...

\newpage

*** NEW Yak Shaving Heading Two:

Note: This is an example of some documentation or research you need to do, the result of which will not be included in your book but will be used as a resource necessary for the creation and or publishing of your book... Add what you need here... 

Use this section's top level heading outline structure.. Create sub-level headings as needed for your purposes...

\newpage

*** NEW Add more yak shaving headings as needed:

Duplicate the top level Outline above to create more headings here as needed... 

Create sub-level outlines below each heading as needed for your purposes.

Anything goes here... You can make this into what ever you want..

\newpage

* ⏰ Tasks:                               :noexport:
:README:
   This Tasks Section is similar to the Log Book within the 
   Research section of this Book Project...  Log entries
   are research activities...  Tasks are more General and
   relate to this ENTIRE Book Project as a whole...

   - *Use this Section to* =ADD TIME STAMPED TASKS= *for any pourpose*

      Create More *⏰ Tasks:* =Sub Categories= & *⏱ New Task:* =Entries= 
      as needed during the development of your Book Project...

      Use the Supplied: *⏱* <2022-08-25 Thu> *New Task:* /(Master Template)/ 
      from the *⎘ Meta: / ⎘ Templates:* Binder to easily =copy/clone= 
      a new Task Entry into this *⏰ Tasks:* Binder...

   - *Time Stamp Task Entries With:* ~C-c .~ *To Set The* =START DATE=

   - *Use or Create NEW Task Sub Categories as Needed:*

   The Synopsis Tasks provided below are important first steps to take 
   when first starting a book.  They are based on the "Snowflake Method" 
   by Randy Ingermanson...

   These tasks should be started as soon as you create a new project 
   using this: *HAP_Technical-Book-Project-Skeleton* 

   It is hoped that this process will give you a faster, efficient, 
   organized "bootstrapped" head start and teach some guidance about 
   how to properly organize and write your books with a clearer mind, 
   inspired outlook, and renewed motivation...
:END:
** 📃 Synopsis Tasks:
:README:
   =Do These Synopsis Tasks FIRST When Starting a NEW Tech Book Project=

   After completing each Timestamped Step below, Mark its TODO 
   state to ~DONE~ and update the timestamp to the current time as
   well...  Use Command: ~C-c . RET~ while cursor is on the timestamp
   to update it to the current date/time... 

   The Synopsis Tasks below are based on The Award winning Snowflake 
   Method created by [[https://www.advancedfictionwriting.com/][Randy Ingermanson]] of Ingermanson Communications, 
   Inc. You could write anything you want for a synopsis...

   Randy Wrote his book with Novelist /(fiction writers)/ in mind but
   I believe these same principals apply to real-life as well...
   Of course... Right?  Fiction and Real Life are not ALL that
   different at the end of the day... Just be sure not to be writing
   any "fake news" OK? Thanks... We really don't need any more of that.

   =It is HIGHLY Recommended= for you to use the steps below FIRST 
   before doing any other writing! This advise comes from many 
   highly acclaimed authors! Not just Randy...
:END:
*** NEW <2022-08-25 Thu> Do This First: =Important=

=NOTE:= Before you start you need to answer the 
      following questions:

- [ ] *What is your main category or genera?*

       _______________________________________

- [ ] *You write within this genera because?*

       _______________________________________

- [ ] *Readers will be attracted to and enjoy your books because?*

       _______________________________________


After completing above, follow the steps below...

\newpage

*** NEW <2022-08-25 Thu> Step One - Write a Single Sentence Summary:

=Take An Hour And Write A One-Sentence Summary Of Your Book:= 
   
*Something like this:*

   /"A gourmet chef from Boston acedentally falls into a parallel/ 
    /world, almost destroyed by an arch enemy he did not even know/ 
    /he had, then he discovers he is immortal and meets-re-discovers/ 
    /his ancient soul mate of eons. Together they save the universe/ 
    /after all else fails!"/

OK I know... I cheated. The second sentence is a stinger. It needs to stand alone... I often buck the rules... lol

The sentence you end up writing above will serve you forever as a ten-second selling tool. This exercise defines the big picture illustrated by the first simple triangle in the snowflake diagram /(as explained to Goldilocks and/ /classmates by Baby Bear in: Chapter 4 of Randy Ingermanson's Book:/ 
/"How to Write a Novel Using the Snowflake Method")/

Within that same chapter, Baby Bear also pointed out this important fact to keep in mind: 

   /(Illustrated "Radio Drama" Style Just For Fun, Because We Can... ;-)/

#+BEGIN_SRC fountain

            A screenplay adaptation of an excerpt of dialog witin chapter 4 of:
                   "How to Write a Novel Using the Snowflake Method"
                                by: Randy Ingermanson

# Somewhere in the middle of Scene One:

INT. (BABY BEAR'S CLASSROOM - DAY)

_1. SOUND [CREAKING & THUD OF TABLE AS BABY BEAR JUMPS UP ON TOP]_

2.

BABY BEAR
(RECOVERING BALANCE, GRUNT, DEEP ENHALE)
    
This is important, you novelists!
   
You're going to get lots of advice on how to write a novel.  
    
But that's all it is. Advice. If you don't like that advice, 
    
if it doesn't work for you, then ignore it.  
    
If it does work for you, then run with it.

#+END_SRC

I agree... Don't let anybody steer you away from your muses! But at the same time don't ignore the basics!

This synopsis stuff is basic to the bone! It is universal... We cannot buck it!  It's based on human nature... Your sentence above, will serve as a pitch during normal conversations /(to see if there is any interest)/...

=Memorize "your line"= to the point that you can say it in your sleep! Turn it into a "slogan" /(hopefully a "meme" if you are the lucky type)/. Your goal is that others will remember and be able to easily tell all their friends /(word/ /for word)/. Networking is the key! You can't do it alone... Songs are also great help! /(cartoons and songs are killer!)/ Social networks open you up to sky limit possibilities!

=Lead with your story line while engaging with a total stranger= or even your mother. =Remain silent after that=... Wait to see if there is interest before diving deeper... That and your good body language "posture" will take care of everything...

=Important!= Closing rules of sales dictate the law of attraction 
           always applies.. Pushing yields negative results... 
           =If you push people... They push back...= 

           =If you run away from people, they chase you...= 

           To eat, or to be eaten... That's what it all comes down to. 
           lol Wait to see if there is interest... 

           =If NOT, Move On...= 
           =If YES... Do The Next Step...=

When the time comes for you to write your book proposal, this sentence should appear very early in the proposal. It's the hook that will sell your book to your editor, to your committee, to the sales force, to bookstore owners, and ultimately to readers. So make the best one you can!

***** Here are some tips:

- *Shorter is better. Try for fewer than 15 words.*

- *No character names, please!* 

   Better to say "a handicapped trapeze artist" than "Jane Doe".

- *Tie together the big picture and the personal picture.* 

   Which character has the most to lose in this story? 
   Now tell me what he or she wants to win.

- *Read the one-line blurbs on the New York Times Bestseller list* 

   This will teach you how to do it by example. Writing a 
   one-sentence description is an art form. If you become a 
   master at this, marketing firms will want you madly!

- *Check out:* [[yt:feD-dImM4a8][LEGO Star Wars: The Last Jedi in 60 Seconds]] 

   /(and other 60 second movies like it)/ for a completely 
   different audio/visual parallel to this literary concept...
*** NEW <2022-08-25 Thu> Step Two - Expand Summary to Paragraph

=Take another hour and expand your sentence= from step one into a full paragraph describing brief overview, technical requirements or challenges, and ending with your proposed solution in a single sentence.

This step defines the second stage of the snowflake model... as illustrated by further trisections of the triangle producing the snowflake diagram /(as explained to Goldilocks and classmates by Baby Bear in chapter 5, "The Importance of being Disastrous" in Randy Ingermanson's book: "How to Write a Novel Using the Snowflake Method")/

For this step, *visualize the story as having "three disasters plus an ending"* 
In the sense of Reference and Technical Books, Manuals, etc. Think of "disasters" simply as business or technical challenges, which in fact can be real disasters... So there is really no difference... at the end of the day...

Each of the disasters takes a quarter of the book to develop and the ending takes the final quarter. I bet this formula is the same for development and
exposition of your technical material and final solutions or conclusions...

No one claims this to be an absolute ideal structure, but it's the one that Randy Ingermanson uses, and it has a strong basis in psychology.

=If you believe in the Three-Act structure, then:=

- *The first disaster /(challenge)/ would correspond to the end of Act 1*

- *The second disaster /(challenge)/ would be the mid-point of Act 2*

- *The third disaster /(challenge)/ would come at the end of Act 2, and force Act 3*

- *Act 3 wraps everything up* /(and provides a final solution or conclusion for your technical book...)/

\newpage

**** Make 5 Sentences: [0/5]

1. [ ] =Exposition:=

   The first sentence paints the big picture of the problem 
   with a hint of its solution. The purpose of this sentence 
   is to invoke a strong curiosity, desire, and expectation 
   to learn the rest of the book's proposed solution!

2. [ ] =Second Sentence:= - *This Sets Current Playing Field*

   Outline the circumstances of the current playing field that 
   your book will be addressing. This is the key event that 
   motivated you to find a remedy in the first place.  This 
   section must hit home to our readers as well, inspiring 
   them to follow the rest of the book for answers...

3. [ ] =The third sentence:= - *Tells them what NOT to do* 

   =Sharing Personal Blunders Is A Sure Hit For Readers=

   Here is where you get to tell some stories... past experience 
   of failed attempts etc.  Not offering the proper solutions yet, 
   but rather showing the palm face human events that finally lead 
   you to discovery of the proper methods & solutions...
   /(the music changes, new hope emerges out of the fog of your mess)/

4. [ ] =The forth sentence:= - *Where You Git To Hit The Home Run!*

   This sentence reveals your final best solution to all the 
   challenges presented, giving your readers the impression that 
   =reading this book will help them avoid all pitfalls entirely!=

5. [ ] =Summary:= *(conclusion)*

   This last sentence wraps everything up, further supporting 
   the first three sentences with one single statement.  An 
   encouragement and also challenge for your readers to read 
   this book to discover more.

\newpage

**** Using Your One-Paragraph Summary:

You will be using this paragraph in your proposals. It is only for your agents etc.  Not for your readers who need to be kept in the dark about 
too many details until they read the book...

=However=, Some of this paragraph /(written with parts pourposefully left out or with questions put in place)/ may end up back-cover copy for your book's promotion.

\newpage

*** NEW <2022-08-25 Thu> Step Three - Expand Paragraph to Synopsis:

=Take several hours and expand each sentence= of your summary paragraph into a full paragraph. 

*All but the last paragraph should present challenges, pitfalls to overcome.* The final paragraph is your proposed best-practice solution.

By this stage, you should have a good idea of the large-scale structure of your book, and you have only spent a day or two, or at most, a week or two, but all that time will not have been wasted! You will now have a good idea if there are going to be problems that need to be worked out. This is good knowledge to have now, rather than after investing 500 hours in a rambling first draft.

At the end of this exercise, you will have a nice one-page skeleton of your book. It's fine if your skeleton does not fit all on one single-spaced page as long as it does not go beyond that...

Your process now is to grow these ideas as individual chapters and topics.  You have a synopsis "executive summary" suitable for a proposal, and you are well on your way to doing extended promotion...

\newpage

*** NEW <2022-08-25 Thu> Completion:

- [ ] *Copy one-page skeleton from:* =Step Three= above to: *📃 Synopsis:* 
       inside the *🕮 Book:* Binder...

       When you are done with these Synopsis tasks, you will have 
       completed half the battle of writing your technical work! 
       Everything else you write will flow out of that initial seed...

\newpage
** ⏱ Other Tasks:
*** SOMEDAY ⏱ <2022-08-28 Sun> Create Editorial Calendar

=Note:= This is Still Under Construction... I am researching the 
      best way to use agenda, calendar views, and Tables to make 
      an Editorial Calendar work well in Emacs Org-Mode...

Make an *Editorial* for this project! You will need this for quick access during publishing time. Org-Mode excels for this task!  Take advantage of its powerful scheduling, agenda, and filtering capabilities!

Use this space to design your *EC* and then transfer it as a New Section within the main *🕮 Book:* /(binder)/ of this Book Project...

\newpage

* ⎘ Meta: /(templates etc.)/              :noexport:
** 📄 About:

This =Meta= section provides skeleton templates for use within your project(s).  Any sub heading under this Meta: group can be utilized by copy-pasting the collapsed heading into any of your existing project sections (i.e., making a clone anywhere you need to create a new section based on the template's structure)... 

Or... You could try mashing several cloned templates together to create a totally new project heading with a totally different structure... The intent of this is to save lots of time starting up a new custom writing project.  Lets see if it helps. :trollface:

\newpage

** Instructions:

- [ ] *Choose One Of The Templates Below And Copy It:*

       /(Copy the entire template and all of its contents - folded)/  

- [ ] *Paste The Copied Template As A New Clone:* 

       /(Paste it within your project's book, planning,/ 
        /or research section where it would normally belong)/  

- [ ] *Change The Name Of Your Clone:* 

       /(Change the name to a specific title needed to fit/ 
        /in with your project's story-structure.../  
        /In the case of Logs or Tasks, you probably will/ 
        /keep those titles as they are universal.../ 
        /but you may wish to further qualify them by adding/ 
        /a prefixed category word.)/

\newpage

** NEW 📖 Chapter: ~#~ <optional title> /(Master Template)/
:README:
   *📖 Chapters* are the *Top Level Headings* within the 
   *🕮 Book:* Binder of this Book Publishing project...

   =Usage:=

   - [ ] =Clone This:= *📖 Chapter:* ~#~ *<optional title>* /(Master Template)/ 
          =Copy ALL its contents= and =paste= it as a child Item 
          in the *🕮 Book:* Binder of this Emacs Org-Mode Book 
          Publishing Project... 

          Do this whenever you need to start a new chapter...

   - [ ] =Edit Your New Clone:=
          The structure of this template is all set up for 
          you ahead of time to allow you to immediately begin 
          writing...  

          Replace titles to suit your needs, but keep the 
          structure of *Chapter / Topic* etc., intact... 
          /(i.e., change names only...)/
:END:
*** ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/
      To Open a Link Type: ~C-c C-o~

      =-or-= Simply Fill in the Template Link Placeholders Below 
           & copy/paste more placeholders as needed... ;-)
:END:

*Add links to Anything Deemed Important to the Writing of This Chapter:*
/(Links to Websites, Other Stories, Images, Sound, Video, Whatever...)/

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] -

\newpage

*** 🔖 Chapter Introduction: /(optional - remove if not needed)/

*Lorem Ipsum *Lorem Ipsum dolor sit amet*, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, /lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante./

\newpage

*** 🔖 New Topic 1:  /(Replace With Title or Simply Use:/ ~#.1.1~ /etc.)/
:README:
   =Topics= /(Scenes)/ are the DNA that make up the chapters in a  
   book... Each Topic could have its own title or phrase or 
   it could not have a title but instead sub chapter numbering 
   only...

   Chapters may contain several topics... There can be many 
   twisty paths all alike (or all different)... %~)

   This *Topic Template* could ALSO Serve As A 
   =CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
         /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
         /and this could be added with or without inclusion of/
         /the scene name headings.../
:END:

~<insert Topic Content Here>~

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Copy/Clone This Entire Topic Heading and Paste Copy Below it as Needed=

*** 🔖 New Topic 2:  /(Replace With Title or Simply Use:/ ~#.2.1~ /etc.)/
:README:
   =Topics= /(Scenes)/ are the DNA that make up the chapters in a  
   book... Each Topic could have its own title or phrase or 
   it could not have a title but instead sub chapter numbering 
   only...

   Chapters may contain several topics... There can be many 
   twisty paths all alike (or all different)... %~)

   This *Topic Template* could ALSO Serve As A 
   =CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
         /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
         /and this could be added with or without inclusion of/
         /the scene name headings.../
:END:

~<insert Topic Content Here>~

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Copy/Clone This Entire Topic Heading and Paste Copy Below it as Needed=

*** 🗒 Background Notes:
:README:
   *Background Notes* /(unlike Topics, Introductions, Summaries etc.)/
   Should be written in =OUTLINE= form to aid in organization of 
   details, etc... This section is =NOT the place to create NEW ideas=, 
   but rather to =organize EXISTING ideas you have already written=...

   =None of the Content Written Here Should be Added to any= 
   =Chapter/Topics within your Book= 

   =THIS IS A META PLACE=

      /(i.e., Your Books Internal Analyst/
             /Behind the Curtain So-To-Speak... %^)

   Use Background Notes when you need to add notes, ideas, instructions,
   whatever... close at hand within the chapter, and not have to worry 
   about any of it getting exported and or published to the final output 
   product...  

   Nothing within this section will be exported... not even the Background
   Notes Heading itself.  Use this section any way and for any purpose you 
   wish for things related to the chapter heading that contains it...

   The example Notes below have been timestamped as a way to suggest
   organizing TODO items for a particular chapter you may find 
   yourself working on, or researching... 

   =Use/Replace the notes below for your own schemes=
:END:
**** 🗒 Note 1: <2020-05-10 Sun> /(example)/

*Mark each note's timestamp to its initial creation time*. This will enable emerging notes for chapters to be searched chronologically, and to give you an idea of how things evolve over time...

*Add anything you need here under this heading* formatted any way needed to present the data... Sub levels are fine, tables are fine... etc.  This is your chapter's Notebook, Scrapbook, whatever any extra info/metadata you feel is important to record...

- *Use bulleted lists/sublist etc. if needed...*

*1. Or Numbered Lists...*

|----+--------|
| Or | Tables |
|----+--------|
|  1 |    2.3 |
|----+--------|

Do any or all the above to help get the concepts and images of your book clear in mind...

\newpage

**** 🗒 Note 2: <2020-05-10 Sun> /(example)/

Each new note needs to get its own heading and initial timestamp...

****** Quid Novi?

Quid Novi? Lorem Ipsum dolor sit amet,consectetur adipisicing elit, sed doeiusmod tempor incididunt ut laboreet dolore magna aliqua. Ut enim adminim veniam, quis nostrudexercitation ullamco laboris nisi utaliquip ex ea commodo consequat.Duis aute irure dolor inreprehenderit in coluptate velit essecillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatatnon proident, sunt in culpa quiofficia deserunt mollit anim id estlaborum.

\newpage
*** 📝 Chapter Summary: /(Chapter Template)/
:README:
   Chapter Summaries, /(Just Like Background Notes)/ are ALSO =META DATA= 
   Not Intended to be Added back to the Chapters/Topics of your 
   Book... The purpose of Chapter Summaries are to help you during 
   planning stages where you are trying to resolve some technical 
   detail, or work out a best practice method, etc...

   Keeping the above in mind while writing a chapter summary will help 
   you get better organized about how your book is developing, what 
   directions you need to take next, what areas need the most work, 
   and where problems or inconsistencies may arise...

   Most importantly, this will help prevent you from making any grave 
   mistakes causing contradictions within your presentation later... 
   
   In any case you will be better informed by keeping all your figuring 
   here in this summary where you can see and resolve issues quickly...
:END:

=Chapter Summary= /(example)/

In this chapter we are dealing with yadda yadda yadda which must be resolved with yadda yadda yadda.  But be careful about Yadda Yadda Yadda as that does not exist in this book at all!  What?  Nevermind... It never existed... 
IT Only exists when you actually try to observe the results...

\newpage

** ⎘ Templates:
*** NEW 🗓 LOG: <2021-03-29 Mon> Entry /(Log Entry Template)/
:README:
   - *Go To One of the HEADINGS Below:* /(Summary, Details, or Sub Headings)/

      =Punch the Time Clock= At the heading And then begin working on a
      task related to that Heading... =Your Time IS being Recorded Now= 

   - =Use These Commands:= /as you work to keep track your time.../

      + *Clock IN:* ~C-c C-x C-i~ 

           /(Begin OR Resume Clocking Current task)/

           This creates a new :CLOCKING: Time Card Entry just
           underneath the HEADING...

           Do this just before starting work on the task... 
           Be in control of your life!

           After doing the above, you can go away and do some 
           work, leaving this heading, log note, etc. to visit 
           other files and/or work on them etc. The clock will 
           be recording your time all the while... You will see 
           in your mode line the elapsed clock time ticking away 
           as you work on a task /(hopefully related to this clock!)/
           and NOT Yac Shaving or being sidetracked!!!

      + *RETURN to Clock Heading:* ~C-c C-x C-j~

           /Go back to the place where you started the clock.../

           You do this after you have worked on a task for a 
           while and you need to come back to update the item's
           info etc., and/or stop the clock before going off to 
           do something else unrelated to the log entry...

      + *Clock OUT:* ~C-c C-x C-o~ /(to stop clocking your time on task)/

           This *Finalizes the Time Card Entry* within:
           ~:CLOCKING:~ /(created earlier when you started the/ /clock)/

           The Clock Entry changes showing start timestamp, end 
           timestamp, and total time worked during this segment...  

           =Please DON'T Forget= /Like I often do, LOL.../ i.e.,
           Leaving a clock running all day by accident, or worse,
           leave it dangling with the file closed only to open it
           again and get that nasty *Org-Mode Message:* /"What do/
           /you want to do with this?"/ If you do something like 
           that you can always come back and directly edit the 
           clock times by hand to amend them...  After changing 
           clock times or dates, etc... Whatever...

           ="Onward We Row Mates... Through the log jam!"=

      + *Update Time Card Entry:* ~C-c C-c~ 

           This command will change the total time at the end showing 
           your new calculated time...

           If you need to go away and do something else before finishing 
           this task, you can do so after clocking out... When you come 
           back simply clock back in again to start another Time Card 
           Entry just as before... The new time card entry will appear 
           above the earlier one within the ~:CLOCKING:~ drawer... When 
           you clock out of this task it will look just like the entry 
           below it with a total time worked tagged on the end...

      + *Clock Out & Mark Items Done:* ~C-c C-t~

           When you are all done with a Log Entry use the above key 
           command to mark its Heading *TODO* tag to: *DONE* /(Most of the/ 
           /time this will ALSO clock you out if you are still clocked/ 
           /into the item... But not allways in my experience.../  
           So make sure you are also clocked OUT of an Item After 
           marking it DONE... Type: ~C-c C-x C-j~ to check this...
           /(if no running clock it will tell you and place your/
           /cursor at the heading where you LAST CLOCKED OUT)/

      + ~C-c C-x C-q~ *Cancel Current Clock:* /(in case of accident)/

           This removes currently running clock and forgets 
           any time accrued or associated with it...

      + ~C-c C-x C-d~ *Display Clocking Info:*

           /This will show elapsed times to the right of headings.../
           =Warning!= Using this command will CLUTTER ALL the headings
           within your org file with those timestamps!!!

   =Note:= Once all of the above commands become routine for you, you 
          might want to remove this ~:README:~ drawer from this 
          template... That way it won't get copied when you need to 
          clone new log entries...
:END:

=Copy/Clone= This: *🗓 LOG:* <2021-03-29 Mon> *Entry* /(Log Entry Template)/
=Paste As: New Entry= Within: *🗓 Log Book:* Binder
under the *🔍 Research:* section of this Emacs Org-Mode Book Publishing Project...

Replace these instructions with short description of log entry. 
/(if needed)/

\newpage

**** 📚 Reference:

- *Link to Project:* [[][] ]

- [[URL][Link Name] ] *Heading:* /(comment)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] /(_)/

- [[][] ] /(_)/

- [[][] ] /(_)/

\newpage

**** ⏱ Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW ✅ Summary: [0/3]
:README:
   This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

   Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...

   Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...
:END:

Yadda... Yadda... Yadda...

1. [ ] *__:*

2. [ ] *__:*

3. [ ] *__:*

\newpage

**** NEW 📒 Details:
***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       user@home:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
      #+end_src

\newpage


***** NEW New Item 2 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       user@home:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
      #+end_src

\newpage

***** NEW New Item 3 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       user@home:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
      #+end_src

\newpage

*** NEW ⏱ <2022-08-25 Thu> New Task: /(Master Template)/
:README:
  =Copy/Clone= This Template as a *NEW TASK* within a 
             sub-category of your: *⏰ Tasks:* Binder... 
             Create New Sub Categories as needed...
:END:

=NOTE:= *Create Your New Task Below...* 
      The Timestamp above should be set as this
      Tasks Start date...  You may also create
      another timestamp for the completion date
      of this milestone as well...

      More Project Management elements may be
      added in future versions of this template...

- [ ] *Item One?*

       Do Item One...

- [ ] *Item Two?*

       Do Item Two...

- [ ] *Item Three?*

       Do Item Three...

\newpage

*** NEW 💡 New Topic Idea:  /(Replace With Title or Simply Use:/ ~#.1.1~ /etc.)/
:README:
   =Topics= /(Scenes)/ are the DNA that make up the chapters in a  
   book... Each Topic could have its own title or phrase or 
   it could not have a title but instead sub chapter numbering 
   only...

   Chapters may contain several topics... There can be many 
   twisty paths all alike (or all different)... %~)

   This *Topic Template* could ALSO Serve As A 
   =CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
         /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
         /and this could be added with or without inclusion of/
         /the scene name headings.../
:END:

~<insert Topic Content Here>~

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Copy/Clone This Entire Topic Heading and Paste Copy Below it as Needed=

