# -**- mode: org; coding: utf-8 -**-
#+LATEX_HEADER: \usepackage{parskip}
#+LaTeX_HEADER: \usepackage{paralist}
#+LATEX_HEADER: \usepackage[hyperref,x11names]{xcolor}
#+LATEX_HEADER: \usepackage[colorlinks=true,urlcolor=SteelBlue4,linkcolor=Firebrick4]{hyperref}

#+begin_comment
 Setup Files:
   For Cloned Versions of this template, replace file/paths below
   with file/paths to your own custom setup files (which you could 
   convienently clone from the example setup files provided in
   ../org-templates/ directory...

 NOTE: 
   #+CATEGORY: is specified within log-book.org setupfile.
   If you need to change the category do it in log-book.org
   or your cloned version of it...
#+end_comment

#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/fiction-book.org
#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/default-tags.org

#+TITLE: HAP - Fiction Book Project Skeleton
#+EXPORT_FILE_NAME: HAP_Untitled-Fiction-Book.pdf
#+KEYWORDS:
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2021-03-25 Thu>
#+TEXT: Created: <2020-07-30 Thu>
#+TEXT: Last Published: <2021-03-25 Thu>
#+FILETAGS: templates fiction_books

#+DESCRIPTION: HAP - Fiction Book Project Skeleton with generic basics already done.  Great for Authors to use when starting a new fiction book project from scratch... Publishable as a PDF Book suitable for eBook readers... (easily modified for publishing in other eBook formats or for the web)

#+begin_comment
 Don't mess with these unless you have good reason, (e.g., testing).
 Use Setup Tag File above to specify tags for this file...

# #+STARTUP: noptag
# #+TAGS:
#+end_comment

:README:

To use this *Fiction Book Project Skeleton* /(template)/ for your own projects, perform the following three steps:

1. *Clone a Copy of this File:* Put it where you normally organize your writing projects.  *Place it within its own folder* named after your intended project title...

2. *Change the* ~#+TITLE:~ *directive at the top of this file* to: /"your Fiction Book Project's Title"/

3. *Change the* ~#+EXPORT_FILE_NAME:~ *directive at the top of this file* to: /"your-Fiction-Book-Project's-Title.pdf"/ That will be the file name produced thence forward...

4. *Change the* ~#+DESCRIPTION:~ *directive at the top of this file* to /your Fiction Book Project's Description/ etc...

2. *Copy/Clone ./media* /(and all its contents):/ To your new project's folder /(where you copied this file).../  Any external documents or images referenced by your book project should be placed within this ~./media/~ directory... All of the external links, images, within the boilerplate examples may be used as examples for getting your own images, and external attachments linked properly...  This single *./media* directory serves media and external attachments for all of the *.org* files contained within: ~.emacs.d/Docs/pubOps~ directory... Cloning any of the other *.org* files will also require copy/cloning the ./media directory relative to them...

4. You don't need to copy the ~./auto/~ directory...  That will be created for you automacally the first time you export this ~.org~ file to ~.PDF~.

5. You also don't need to copy the ~./org-templates~ directory /(That is... If you have installed and are using Harmonic Alchemy Modular Emacs, and it is properly configured for publishing this file)/... The files in there are automatically linked and included within this template. You don't need to change those settings unless you wish to customize the already customized tags, and export options. /They are allready set up correctly for the Fiction Book genre, and the category is all set as well... But if you must, you can modify the original files to make your changes rather than cloning to your project directory.../  

   Realize when you make any changes to your ~.emacs.d~ Configuration files while on the ~MASTER~ branch of your cloned repository, it will get out of sync with origin! To avoid this problem, check out a local branch for your own custom changes to make it easier to get back to defaults if you change your mind later. %^)

6. *Start Planning / Writing Your Fiction Book:* /Change headings and structure to match your project's outline sections-chapters-scenes-plots-characters, etc./ Start doing the Tasks within the Tasks section... Have fun doing this...

The *In-Buffer Settings* and *KEYWORDS* specified above are configured to get this file looking good when exported as a Standard PDF file.  Once you have your project directory all set up as above you are ready to export your first PDF as a test run...  To make a PDF out of this file issue the following Emacs command:

   #+begin_src conf
      M-x org-latex-export-to-pdf
   #+end_src

   *-or-* If You Enabled *Xah-Fly-Keys* /"Command Mode"/ Try:

   #+begin_src conf
      SPACE e p
   #+end_src

After *AucTeX* is done parsing/compiling etc., a new *PDF* by the name of ~New-Untitled-Fiction-book.pdf~ -and- ~New-Untitled-Fiction-book.tex~ will appear within the same directory as this file...

Subsequent repeated calls to the above command will overwrite your existing ~New-Untitled-Fiction-book.pdf~ -and- ~New-Untitled-Fiction-book.tex~ files! You should probably copy these files to the ~./auto/~ directory as well for safe keeping as backups...

*Last Modified: <2021-03-25 Thu>* So far things are pretty basic PDF... We will get fancy with other formats later... I promice... I have to do all this documentation first! /(As you can see, if you been following for the past couple years, things are getting done! Albeit Slowly)/

Enjoy! - Alisha Awen
:END:

* 💡 Scratchpad Refile:       :noexport:
** ☞ Start Here!
:README:
   This Section is mainly to accommodate "seat-of-pants" writers
   /(of which I have been accused of... But I also crave the planning stuff)/.  I often come here for my [[https://projects.csail.mit.edu/gsb/old-archive/gsb-archive/gsb2000-02-11.html]["yak shaving"]] adventures...

   Use this: "*💡 Scratchpad Refile ☞ Start Here!*" section as a quick
   place to document ideas and inspirations as they come along...
   You can refile them later... 

   Even if your quick inspiration was intended for elsewhere?,
   /(e.g., You become bored documenting tedious technical information/
   /when suddenly, out-of-nowhere, an idea for a new sci-fi scene in/
   /that screenplay episode you had in the back of your mind all day!,/
   /etc.)/

   =Ummm.... Parallel Universe?=

   =Sure!= You can put anything in here! We've got that covered for you
         in this Start Here spot. %^)

   Use this section to quickly capture inspired at-the-moment ideas
   =While they are still fresh in mind=

   =How To Use ???= 

      /Simply Come directly here and do what ever you want.../
      /"Your Crazy Daze are Covered!" Yay!/ 

   The following Shortcuts will Help you get started as quickly 
   as possible:

   - [ ] *Copy/Clone:* =Example Idea= *Heading Below:* 

         =Copy the Heading AND ALL ITS CONTENTS=

         /Change your Clone's Title to Your Own Title/

   - [ ] *Change the timestamp on your Clone Entry:* [0/1]

         =Type:= ~C-c .~ while cursor is sitting on the timestamp

         /i.e., Press: ~Ctrl-c~, let go, and then type a Period/ ~.~

         A date chooser panel will pop up...

     + [ ] *Press* ~ENTER~ *to auto accept today's date and time.*  

            The existing timestamp will change to TODAY...

   - [ ] *Advance your cursor and Start Writing!!!*

          Advance your cursor few more lines down to some fresh 
          empty space and Start Typing Your Story Idea Like Mad!!! 

   - [ ] *Don't stop Writing!* 

          Don't worry about formatting or organizing it until later, 
          after all your inspiration has passed and you are ready 
          to organize...

   - [ ] =TODO After You Are Done Writing:=

        + [ ] *Adjust Space:* 

               Adjust space between your headings and your fantastic ideas
               below them it to one single blank line...

        + [ ] *Further organize things as needed...*

               If you become inspired to write while organizing.... 
               Do that first and come back later... Don't scare away your 
               muses when they beckon! Get your story down first! No matter 
               what state it may be in at first... GET IT DOWN

        + [ ] *You Are Free To Go Out And Play Elsewhere Little Grasshopper*

               If after writing... You don't feel like organizing now?
               NO PROBLEM... But come back later and organize things... 
               OK? Don't create a swamp in here! /And don't forget to take/  
               /your bath tonight... ;-)/

   Having done the simple steps above any time you get inspired, you will be able to tell your grand children.. "I got my first spark of an idea for that book back in Year, Month, Day, time, second" (50 years later!) Now that is being organized! LOL
:END:
*** 💡 <2022-08-20 Sat> Example Idea /(clone this)/
:README:
   This is a dummy example of some crazy idea that you may have gotten at the spur of the moment, while you were doing something elsewhere within this project...  After you are done getting as much of the idea as you initally can then you can simply go back to what you were doing before the inspiration segue tore you away... you might want to schedule this as a todo item before leaving though...

   Later when you are free you can come back to file this or place it where it belongs.  In the case of the note below it would probably go in a research folder of a Sci-Fi related project...
:END:

=Copy/Clone this Boilerplate Template NOW= And Change your clone's Title.. 

=Then Quickly Get Started Writing Down your FRESH NEW IDEA=

\newpage

*** 💡 <2020-06-07 Sun> Visisonar - Object from Asimov's Foundation Series
:README:
   This is a dummy example of some crazy idea that you may have gotten at the spur of the moment, while you were doing something elsewhere within this project...  After you are done getting as much of the idea as you initally can then you can simply go back to what you were doing before the inspiration segue tore you away... you might want to schedule this as a todo item before leaving though...

   Later when you are free you can come back to file this or place it where it belongs.  In the case of the note below it would probably go in a research folder of a Sci-Fi related project...
:END:

From Isaac Asimov's science fiction series 'Foundation', specifically the section of 'Foundation and Empire' entitled 'The Mule', the visisonar is considered a musical instrument.

Unlike most instruments, this one does not achieve its effect by using sonic effects but, instead, directly stimulates the listeners' mental well-being. The number of people and level of effect depends on the skill level of the player. As this was a device from the First Empire, there were not that many people around with any skill at all. However, the Mule's clown, Magnifico, had some skill with the instrument and was asked to play for select parties on the Foundation and for large groups of workers on Haven. This may not have been a good idea...

\newpage

* 🕮 Book:
** NEW 📃 Synopsis:
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space to write the main synopsis of your work... You can write anything you want here but it is recommended to use the award winning *"Snowflake Method"* created by [[https://www.advancedfictionwriting.com/][Randy Ingermanson]] of Ingermanson Communications, Inc. These steps have been provided for you in the main *"Tasks:"* section...

   - [ ] *Go to the:* =⏰ Tasks:= *Section and do the:* =📃 Synopsis Tasks:=

   - [ ] *After Completing Tasks Mark Them:* ~DONE~

   - [ ] *Place Resulting Synopsis Notes in Here:*

          You will be coming back here to consult these notes for many 
          things as you promote and publish your book.
:END:

=Synopsis Content:= Yadda... Yadda... Yadda...

\newpage

** NEW 📃 Front Matter:
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space for holding all of the Front Matter related content of your book... 

   Add Book Cover Art, Copyright Info, Publishing Info, etc. here... Only these basic elements are included in this Front Matter section which may or may not be exported to published media...
:END:

=Front Matter Content:= yadda... yadda... yadda...

\newpage

** NEW 📃 Preface: /(or Introduction - Optional)/
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space to write the *Preface* / or *Introduction* to your book... 

   Optionally you may wish to include a *Table of Contents*... However
   there are automatic ways that =Emacs Org-Mode can configure TOCs= as well...
:END:

=Preface or Introduction Content:= 

   yadda... yadda... yadda...

\newpage
** NEW 📖 Chapter: ~1~ /(Master Template)/
:README:
   *Chapters/Episodes* are the *Top Level Headings* within the =Book:= Section of this Org Book Publishing project...  Clone this *New Chapter/Episode #:* Master Template and paste it as a child under your =Book:= outline heading... Do this whenever you need to start a new chapter...

   The structure of this template is all set up for you ahead of time to allow you to immediately begin writing...  Replace titles to suit your needs, but keep the structure of *Chapter / Scene (sub-chapter)* intact... i.e., change names only...
:END:
*** ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/
      To Open a Link Type: ~C-c C-o~

      =-or-= Simply Fill in the Template Link Placeholders Below 
           & copy/paste more placeholders as needed... ;-)
:END:

*Add links to Anything Deemed Important to the Writing of This Chapter:*
/(Links to Websites, Other Stories, Images, Sound, Video, Whatever...)/

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] -

\newpage

*** 🔖 Scene  1: /(Replace With Title or Simply Use:/ ~1.1.1~ /etc.)/
:README:
   Scenes are the DNA that make up the chapters in a novel or episodes in a production... Each Scene could have its own title or phrase or it could not have a title but instead sub chapter numbering only...

   Chapters may contain several scenes... There can be many twisty paths all alike (or all different)... %~)

   This *Scene Template* could =ALSO Serve As A CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
          /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
          /and this could be added with or without inclusion of/
          /the scene name headings.../
:END:

~<insert Scene Content Here>~

Lorem Ipsum Lorem Ipsum dolor sit amet, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante.

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Add More Scene Headings Below as Needed for Chapter=

*** 🔖 Scene  2: /(Replace With Title or Simply Use:/ ~1.2.1~ /etc.)/
:README:
   Scenes are the DNA that make up the chapters in a novel or episodes in a production... Each Scene could have its own title or phrase or it could not have a title but instead sub chapter numbering only...

   Chapters may contain several scenes... There can be many twisty paths all alike (or all different)... %~)

   This *Scene Template* could =ALSO Serve As A CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
          /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
          /and this could be added with or without inclusion of/
          /the scene name headings.../
:END:

~<insert Scene Content Here>~

Lorem Ipsum Lorem Ipsum dolor sit amet, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante.

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Add More Scene Headings Below as Needed for Chapter=

*** 🗒 Background Notes: /(Chapter Template)/
:README:
   *Background Notes*, /(unlike Scenes, Back Stories, Summaries etc.)/ Should be written in =OUTLINE= form to aid in organization of events, etc... This section is =NOT the place to create NEW ideas=, but rather to =organize EXISTING ideas you have already written=...

   =None of the Content Written Here Should be Added to any Chapter/Scenes within your Book= =(THIS IS A META PLACE)= 

   /i.e., Your Books Internal Analyst Behind the Curtain So-To-Speak... %^)/
:END:
**** 🗒 Note 1: <2020-05-10 Sun>

+ Mark each note's timestamp to its initial creation time. This will enable emerging notes for chapters to be searched chronologically, and to give you an idea of how things evolve over time...

+ Add anything you need here under this heading formatted any way needed to present the data... Sub levels are fine, tables are fine... etc.  This is your chapter's Notebook, Scrapbook, whatever any extra info/metadata you feel is important to record...

  + Use bulleted lists/sublist etc. if needed...

1. Or Numbered Lists...

|----+--------|
| Or | Tables |
|----+--------|
|  1 |    2.3 |
|----+--------|

Do any or all the above to help get the concepts and images of your book clear in mind...

**** 🗒 Note 2: <2020-05-10 Sun>

Each new note needs to get its own heading and initial timestamp...

****** Quid Novi?

Quid Novi? Lorem Ipsum dolor sit amet,consectetur adipisicing elit, sed doeiusmod tempor incididunt ut laboreet dolore magna aliqua. Ut enim adminim veniam, quis nostrudexercitation ullamco laboris nisi utaliquip ex ea commodo consequat.Duis aute irure dolor inreprehenderit in coluptate velit essecillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatatnon proident, sunt in culpa quiofficia deserunt mollit anim id estlaborum.

**** 🗒 Phasellus orci: <2022-08-20 Sat>

Etiam tempor elit auctor magna. Nullam nibh velit, vestibulum ut, eleifend non, pulvinar eget, enim. Classaptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Integer velit mauris, convallis acongue sed, placerat id, odio. Etiam venenatis tortor sed lectus. Nulla non orci. In egestas porttitor quam. Duis nec diameget nibh mattis tempus. Curabitus accumsan pede id odio. Nunc vitae libero. Aenean condimentum diam et turpis.Vestibulum non risus. Ut consectetuer gravida elit. Aenean est nunc, varius sed, alquam eu, feugiat sit amet, metus. Sedvenenatis odio id eros.

|----------+-----------+-----------+-----------+-------------------|
| Inceptos | Venenatis | Convallis | Curabitus | Nunc vitae libero |
|----------+-----------+-----------+-----------+-------------------|
| test 1   | test 2    | test 3    | test 4    | test 5            |
|----------+-----------+-----------+-----------+-------------------|

Yadda, yadda, yadda. etc...

\newpage

*** 📒 Back Stories: /(Chapter Template)/
:README:
   This section is for a chapter's Back Story development... The following tips will help you manage development of your back stories and how they will best fit into your evolving story... 

   - =Keep Things Organized:=

      + *Add Time Stamped Background Notes:* /(within the Background Notes/
          /section above)/ about new content added to this Back Stories
          section as you progress over time...

      + *Add Time Stamps to:* Sub-headings within the Background Notes 
          Section that reflect back to paragraphs written within 
          this section...

      + *Add TODO Keywords* to sub-headings within the Background Notes 
          Section reflecting back to paragraphs written within 
          this section...

   Doing the above steps will help you keep track of back story development and get better organized about how your book is developing, what areas need the most work, seeing problems that need to be resolved, etc.  Most importantly, this will help prevent you from making any grave mistakes causing contradictions within your story later... /(unless that was your intention "Alfred Hitchcock")/... In any case you will be better informed by keeping things organized here where you can see them and resolve them quickly...

   =The Content Written Within This Section May or May Not be Added to actual Chapters/Scenes of your Book...=
:END:
**** 📒 Back Story Example One: <2020-05-10 Sun>

=Note:= This is an example of a back story related to this chapter, 
       or possibly connecting to another chapter in your book... 

Write it down in the rough here and then later you can develop it further as needed. Keep Background Notes about this back story as well, AND keep them up to date as this story develops!

\newpage

**** 📒 Phasellus orci: <2022-08-20 Sat>

=Note:= This is an example of a back story /(with an actual title)/ 
       which has a companion Background Note /(by the same title)/ 
       associated with it. Keep the companion Background Note up 
       to date with developments happening in here...

The following Back Story is related to this chapter, but ALSO possibly connecting with other chapters within this book... 

Write it down in the rough here and then later you can develop it further as needed. Keep your Background Notes about this back story up to date as well...

\newpage

*** 🗡 Plot Summary: /(Chapter Template)/
:README:
   Plot Summaries, /(Just Like Background Notes)/ are ALSO =META DATA= Not Intended to be Added back to the Chapters/Scenes of your Book... The purpose of Plot Summaries are to help you during planning stages where you are trying to resolve that twisty mess you created... OMG!

   Keeping the above in mind while writing the plot summary of a chapter, will help you get better organized about how your book is developing, what directions it is taking, what areas need the most work, where problems or inconsistencies may arise, etc.  

   Most importantly, this will help prevent you from making any grave mistakes causing contradictions within your story later... /(unless that was your intention "Alfred Hitchcock")/... In any case you will be better informed by keeping all your plot tasks here where you can see them and resolve them quickly...
:END:

=Plot Summary= /(example)/

In this chapter we are dealing with yadda yadda yadda which must be resolved with yadda yadda yadda.  But be careful about Yadda Yadda Yadda as she does not exist in this book at all!  What?  Nevermind... She never existed... Only in your dreams...

\newpage

* 🔍 Research:                      :noexport:
** 🗓 Log Book:

=Place New LOG Items= /(From Templates)/ =Here:=

\newpage

** 👤 Characters:

=Place= *👤 New Character:* =Items= /(From Templates)/ =Here:=

\newpage

** ♾ Worlds:

=Place= *♾ New World:* =Items= /(From Templates)/ =Here:=

\newpage

** ✨ Regions:

=Place= *✨ New Region:* =Items= /(From Templates)/ =Here:=

\newpage

** ∅ Planets - Satellites:

=Place= *∅ New Planet or Satellite:* =Items= /(From Templates)/ =Here:=

\newpage

** 👥 Groups - Factions:

=Place= *👥 New Group or Faction:* =Items:= /(From Templates)/ =Here:=

\newpage

** 🗡 Plots:
:README:
   This Research/Plots section is for documenting or planning out plots that may or may not be related to the actual plots you are developing within the books chapters... This is for Research purposes... NOT for story development... But as research goes it will influence and or help you make your real plots more believable and/or accurate...
:END:
*** 🗡 Plot Idea: /(Or Research of Classic Plot - Clone This and Re-Purpose your copy)/
:README:
   This is All =META DATA= Not Intended to be Added to ANY Chapters/Scenes of your Book... This section is purely for research purposes... To help you while you are writing your book... You may have some classic plot outlined here that relates to your book, or it may be some general plot idea that you may wish to employ later...  These are general plots usually relating to the ENTIRE book, rather than any individual chapter...
:END:

=Plot IDEA= /(example to commendeer for your purposes)/

I found this classic Plot... /(see details below...)/ dealing with yadda yadda yadda which could be modified and used to: yadda yadda yadda.... To be continued...

\newpage

** ❝ Quotations:

\newpage

** 🖍 Styles:

\newpage

* ⏰ Tasks:                    :noexport:
:README:
   - Use this space to add time stamped Tasks below for any pourpose you may need...

   - To create a time stamped task entry, use key command:

      + "C-c ."

      + Make your new entry an outline sub-heading of this project's general "Tasks:" section heading above (or optionally you could create another more specific Tasks: section wherever else you may need a collection of task entries...

   - Keep your Tasks in Decending Chronological Order.
      (i.e., put your newest tasks on top)

   - The three provided tasks below are important first steps to take when first starting a novel.  They are based on the "Snowflake Method" by Randy Ingermanson. 

   - These tasks should be started as soon as you create a new project using this HAP-Book-Project-Skeleton... 

   - It is hoped that this process will give you a faster, efficient, organized "bootstrapped" head start and teach some guidance about how to properly organize and write your books with a clearer mind, inspired outlook, and renewed motivation...
:END:
** DONE 📃 Synopsis Tasks:
CLOSED: [2020-07-04 Sat 15:58]
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2020-07-04 Sat 15:58]
- State "ACTIVE"     from "DONE"       [2020-07-02 Thu 17:36]
- State "DONE"       from "NEXT"       [2020-06-20 Sat 17:19]
:END:

:README:
The Synopsis Tasks below are based on The Award winning Snowflake Method created by [[https://www.advancedfictionwriting.com/][Randy Ingermanson]] of Ingermanson Communications, Inc. You could write anything you want for a synopsis, but it is recommended to use the steps below first before doing any other writing!  This advise comes from many highly acclaimed master authors! (including Mark Twain himself!)
:END:

*** DONE Important Before you start!
CLOSED: [2020-07-02 Thu 17:40]
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2020-07-02 Thu 17:40]
:END:

NOTE: Before you start you need to answer the following questions:

- What is your main category or genera? ______________...

- You write within this genera because? ______________...

- Readers will be attracted to and enjoy your stories because? _____________________...

After completing above, follow the steps below... 

when you are done with these Synopsis tasks, you will have completed half the battle of writing your novel! The other half is getting to know your characters... Plots and chapters will flow from that effortlessly...

*** DONE Step One - Write a Single Sentence Summary:
CLOSED: [2020-07-03 Fri 19:44]
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2020-07-03 Fri 19:44]
- State "NEW"        from "DONE"       [2020-07-02 Thu 17:37]
- State "DONE"       from "ACTIVE"     [2020-05-25 Mon 10:04]
- State "ACTIVE"     from "DONE"       [2020-05-24 Sun 22:23]
:END:

Take an hour and write a one-sentence summary of your novel:   
   
Something like this:

    "A gourmet chef from Boston acedentally falls into a parallel world, almost destroyed by an arch enemy he did not even know he had, then he discovers he is immortal and meets-re-discovers his ancient soul mate of eons. Together they save the universe after all else fails!"

OK I know... I cheated. The second sentence is a stinger. It needs to stand alone... I often buck the rules... lol

The sentence you end up writing above will serve you forever as a ten-second selling tool. This exercise defines the big picture illustrated by the first simple triangle in the snowflake diagram (as explained to Goldilocks and classmates by Baby Bear in chapter 4 of Randy Ingermanson's book: "How to Write a Novel Using the Snowflake Method"

Within that same chapter, Baby Bear also pointed out this important fact to keep in mind:

(illustrated "Radio Drama" style" just for fun, Because we can!)

#+BEGIN_SRC fountain

            A screenplay adaptation of an excerpt of dialog witin chapter 4 of:
                   "How to Write a Novel Using the Snowflake Method"
                                by: Randy Ingermanson

# Somewhere in the middle of Scene One:

INT. (BABY BEAR'S CLASSROOM - DAY)

_1. SOUND [CREAKING & THUD OF TABLE AS BABY BEAR JUMPS UP ON TOP]_

2.

BABY BEAR
(RECOVERING BALANCE, GRUNT, DEEP ENHALE)
    
This is important, you novelists!
   
You're going to get lots of advice on how to write a novel.  
    
But that's all it is. Advice. If you don't like that advice, 
    
if it doesn't work for you, then ignore it.  
    
If it does work for you, then run with it.

#+END_SRC

I agree... Don't let anybody steer you away from your muses! But at the same time don't ignore the basics!

This synopsis stuff is basic to the bone! It is universal... We cannot buck it!  It's based on human nature... Your sentence above, will serve as a pitch during normal conversations (to see if there is any interest)...

Memorize "your line" to the point that you can say it in your sleep! Turn it into a "slogan" (hopefully a "meme" if you are the lucky type). Your goal is that others will remember and be able to easily tell all their friends (word for word). Networking is the key! You can't do it alone... (songs are also great help) (cartoons and songs are killer!) Social networks open you up to sky limit possibilities!

Lead with your story line when opening a dialog with a total stranger or even your mother. Remain silent after that... Wait to see if there is interest before diving deeper... That and your good body language "posture" will take care of everything...

Important! Closing rules of sales dictate the law of attraction always applies.. Pushing yields negative results... If you push people, they push back.  If you run away from people, they chase you... To eat, or to be eaten... That's what it all comes down to. lol Wait to see if there is interest, if not, move on... If yes, do the next step...

When you later write your book proposal, this sentence should appear very early in the proposal. It's the hook that will sell your book to your editor, to your committee, to the sales force, to bookstore owners, and ultimately to readers. So make the best one you can!

***** Here are some tips:

- Shorter is better. Try for fewer than 15 words.

- No character names, please! Better to say "a handicapped trapeze artist" than "Jane Doe".

- Tie together the big picture and the personal picture. Which character has the most to lose in this story? Now tell me what he or she wants to win.

- Read the one-line blurbs on the New York Times Bestseller list to learn how to do this. Writing a one-sentence description is an art form. If you become a master at this marketing firms will want you madly!

- Check out [[yt:feD-dImM4a8][LEGO Star Wars: The Last Jedi in 60 Seconds]] (and other 60 second movies like it) for a completely different audio/visual parallel to this literary concept...

*** DONE Step Two - Expand Summary to Paragraph
CLOSED: [2020-07-04 Sat 15:31]
:LOGBOOK:
- State "DONE"       from "NEW"        [2020-07-04 Sat 15:31]
- State "NEW"        from "DONE"       [2020-07-02 Thu 17:38]
- State "DONE"       from "ACTIVE"     [2020-05-25 Mon 10:21]
:END:

Take another hour and expand your sentence from step one into a full paragraph describing the story setup, major disasters, and ending of the novel.

This step defines the second stage of the snowflake model... as illustrated by further trisections of the triangle producing the snowflake diagram (as explained to Goldilocks and classmates by Baby Bear in chapter 5, "The Importance of being Disastrous" in Randy Ingermanson's book: "How to Write a Novel Using the Snowflake Method"

For this step, visualize the story as having "three disasters plus an ending". Each of the disasters takes a quarter of the book to develop and the ending takes the final quarter. 

No one claims this to be an absolute ideal structure, but it's the one that Randy Ingermanson uses, and it has a strong basis in psychology.

If you believe in the Three-Act structure, then:

- The first disaster would correspond to the end of Act 1.

- The second disaster would be the mid-point of Act 2.

- The third disaster would come at the end of Act 2, and force Act 3,

- Act 4 wraps everything up.

**** Make 5 Sentences:

1. Exposition: 

   This sentence's purpose is to paint the story setting, backdrop and mention leading characters within a descriptive role... The mood is set here briefly, dripping with consentrated visions of expectation!

2. Act One - First Disaster Summary:

   The first disaster emerges out of circumstance. This is the key event that motivates our lead character (hero) to find a remedy.  This disaster must hit home to our readers as well, inspiring them along side our hero as faithful evangelists... 

3. First Half of Act Two - Second Disaster Summary:

   The second disaster is the result of our budding hero's attempt to "fix things" after the first disaster in Act One. But things keep getting worse, not better.  As a result, our hero experiences an epiphany, realizing the errors of her ways, and resolves to do things the correct way from that moment on... (the music changes, new hope emerges)

4. Second Half of Act Two - Third Disaster & Standoff Summary:

   The last half of Act 2 is the standoff between your hero and villain or obstacle... Here is where your hero's new resolve to doing the right thing begins to pay off.  However this act ends with the third disaster...  Act 3 will determine the final outcome.

5. Act 3 Summary: (conclusion)

   This is where it all previous conflicts are finally resolved, one way or the other... Whether or not the lead character (hero) whatever succeeds or fails.  The story once resolved ends as a comedy, tragedy, or mellowdrama.  you decide on that...

**** Using Your One-Paragraph Summary:

You will be using this paragraph in your proposals. It is only for your agents etc.  Not for your readers who need to be kept in the dark about how the story develops before reading the book! Spoilers!

However, Some of this paragraph (written with parts pourposefully left out or with questions put in place) may end up back-cover copy for your book's promotion.

*** DONE Step Three - Expand Paragraph to Synopsis:
CLOSED: [2020-07-04 Sat 15:54]
:LOGBOOK:
- State "DONE"       from "NEW"        [2020-07-04 Sat 15:54]
- State "NEW"        from "DONE"       [2020-07-02 Thu 17:38]
- State "DONE"       from "ACTIVE"     [2020-06-08 Mon 11:36]
:END:

Take several hours and expand each sentence of your summary paragraph into a full paragraph. All but the last paragraph should end in a disaster. The final paragraph is the final conclusion to those disasters bringing your book to a close.

You can employ the snowflake method at finer levels here... Breaking each paragraph into mini disasters or turning points within the main disaster, etc.

By this stage, you should have a good idea of the large-scale structure of your novel, and you have only spent a day or two, or at most, a week or two, but all that time will not have been wasted! You will now have a good idea if there are problems with your story. This is good knowledge to have now, rather than after investing 500 hours in a rambling first draft.

At the end of this exercise, you will have a nice one-page skeleton of your novel. It's fine if your skeleton does not fit all on one single-spaced page as long as it does not go beyond that... 

Your process now is to grow these ideas as chapters of your story. You are expanding the conflict. You have a synopsis suitable for a proposal, and you are well on your way to doing extended promotion...
** ACTIVE 👤 Character Tasks:
:LOGBOOK:
- State "ACTIVE"     from "DONE"       [2020-07-04 Sat 15:59]
- State "DONE"       from "ACTIVE"     [2020-07-01 Wed 11:17]
- State "ACTIVE"     from "DONE"       [2020-07-01 Wed 10:59]
- State "DONE"       from "NEW"        [2020-06-30 Tue 05:38]
:END:

:README:
Some of these Character tasks are based on the Snowflake Method as outlined in Randy Ingermanson's book: [[https://www.advancedfictionwriting.com/articles/snowflake-method/]["How to Write a Novel Using the Snowflake Method"]].  Other tasks are based on concepts outlined within the book: [[https://www.kmweiland.com/wp-content/uploads/crafting-unforgettable-characters.pdf]["Crafting Unforgettable Characters" by; K.M. Weiland]]... The second book is a free download from: [[https://www.kmweiland.com/][K.M. Weilands Website]] where you can find other great books and writers resources... 

Much of what you will be filling in below is based on the above two books but no more instruction is given here as to the why or how... Only the dry forms are included here to make it convenient for you to complete this process...  You are strongly encouraged to purchase and read the above two books so that you will have a deeper understanding while you do this process...

The tasks within this section will be used to produce a *"Character Bible"* for each character in your story.

A character bible is the private lifetime personell file of that character...  Containing scrapbook items of importance throughout the character's life...  There is a new TV show on Amazon called: "Hanna" where this concept has been illustrated perfectly! In this CIA black ops thriller, Babies DNA are enhanced with wolf genes to make them grow up into super soldiers...  When they get deployed (looking as normal youths in high school, they each get a scrap-book containing all of their *"character's"* vital details.  There are pictures of family, best friends, past events, etc.  Their photo is on the front cover...

All of it is fake, but as these secret CIA teens carry out roll play _(within their fake role as normal high school students)_, they begin to believe more and more that they actually "are" who their profiles say they are and not trained CIA agents anymore!  This TV series illustrates the power of getting immersed emphatically with your characters!
:END:

*** ACTIVE 📒 Create Character Bible for Each Character:

**** DONE 📒 Prepare Character Summary Sheet:
CLOSED: [2020-07-07 Tue 15:31]
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2020-07-07 Tue 15:31]
:END:

Take an hour to produce the following summary sheet.  This sheet will provide all the vital essentials for this character for easy reference later... This sheet will show up in the beginning of the "Character Bible" binder.

|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Name:*             |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Role:*             | (hero, heroine, villain, mentor, sidekick, friend, etc.) |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Goal:*             |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Ambition:*         |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Values:*           |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Attracted To:*     |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Empathetic With:*  |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Has Vendetta For:* |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Fears:*            |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Conflicts:*        |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|
| *Epiphany:*         |                                                          |
|                   |                                                          |
|-------------------+----------------------------------------------------------|


**** DONE 👤 Detailed Character Interview:
CLOSED: [2020-07-07 Tue 21:58]
:LOGBOOK:
- State "DONE"       from "ACTIVE"     [2020-07-07 Tue 21:58]
:END:

:README:
Perform a Detailed Character Interview.  This is best done as a "role play" exercise where you become "the character" who is having an interview with a doctor, or lawyer, or someone qualified to keep secrets confidential etc. Some of the information below would be provided via written examination... Other things would be done face to face... You will know the context when you get to those points...

Doing it this way will put you in the right emotional framework.  You will adopt this character's normal anxiety, expectations, assumptions, prejustice etc. You will end up feeling this character's impressions of the various questions on the forms, and you will feel this persons emotions and expectations going into a face to face interview... The results will be more authentic about the character and less, if anything at all about you the author...
:END:

***** *Name:*

Put full name here.  Names are important! If you name your character incorrectly based on your desired personality type you will get into trouble!  Names must match the personality! It makes a big difference... Do your names research... Unless of course you need that "Boy named Sue" effect...

***** *Background:*

****** Birth:
- Birthday:

- Place of Birth:

****** Parents:

- What was important to the character's parents?

****** Siblings:

<add information about siblings here>

****** Economic/Social Status Growing Up?

<info>

****** Ethnic Background:

<info>

****** Places Lived:

- Previous Places Lived:

- Current Address:

****** Education:

- Favourite Subject:

- Special Training:

****** Jobs:
- Salary:

****** Travel:

<info>

***** Friends:

- How do people view this character?

- Lives with:

- Fights with:

- Spends time with:

- Wishes to spend time with:

- Who depends on this character?

- Who does this character most admire?

***** Enemies:

<Add information about this characters enemies, etc.>

***** Dating, Marriage:

<Add information about this characters love life>

***** Children:

<Add information about this characters children>

***** Relationship with God:

<Add Information here>

***** Overall Outlook on Life:

- Self Like/love?

- Things this Character would like to Improve about their life:

- Personal Demons:

- Delusions, Denials:

- Optimistic or Pessimistic?

- Real or Feigned?

- Morality Level:

- Confidence Level:

***** How Character is Viewed by Others:

<Add Information here>

***** A Typical Day:

<Add Information here>

***** Physical Appearance:

+ Body Type:

+ Posture:
  
+ Head Shape:

+ Eyes:

+ Nose:

+ Mouth:

+ Hair:

+ Skin:

+ Tattoos/Piercings/Scars:

+ Voice:

+ What People Notice First:

+ Clothing:

+ How the Character Describes Themsel:

***** Health/Disabilities/Handicaps:

<Add information here>

***** Characteristics:
****** General:

+ Personality Type:

    (choleric, sanguine, phlegmatic, melancholy) 

+ Strongest Character Trait:

    (How can flip side of strong point be a weakness)

+ Weakest Character Trait:

+ Self Control:

+ Self Discipline:

+ what makes this person cry?

+ Fears:

+ Talents:

+ What People Like about this character:

****** Interests and Favorites:

- Political Leaning:

- Collections:

- Food, Drink:

- Music:

- Books:

- Movies:

- Sports, Recreation:

  + Did this character play in school?

- Colour:

- Best way to spend a weekend:

- A great gift for this person:

- Pets:

- Vehicles:

  + What large possessions does this person own?
     (car, home, furnishings, boat, etc.)

****** Typical Expressions:

- When Happy:

- When Angry:

- When Frustrated:

- When Sad:

****** Idiosyncrasies:

<Add information here>

****** Laughs or Jeers At:

<Add information here>

****** Ways to Cheer this Person Up:

<Add information here>

****** Ways to Annoy this Person:

<Add information here>

****** Hopes and Dreams:

- What are this character's life-long dreams?

- How do they see themselves accomplishing these dreams?

****** Greatest Success:

<Add information here>

****** Biggest Trauma:

<Add information here>

****** Most Embarrassing Thing:

<Add embarrassing story here>

****** What this Character Cares About the Most:

<Add most important cares in the world here>

****** Any Secrets?

- Does this character have a big secret?

- Are we allowed to know what that secret is on this private interview?

****** If Allowed to do One Thing and Succeed,  What is That?

<Add one thing to do to succeed here>

****** This is the kind of person who:

<put what they would do here>

****** The most loveable thing about this person:

<remark about the things you love the most about this character>

****** Why the Reader will Sympathize with this Character Immediately?

<put reasons here>

***** Ordinary or Extraordinary?:

- How is this Character is Ordinary or Extraordinary?

- Is this character's situation ordinary or extraordinary?

***** Core Need:

- List corresponding psychological evaluation: (delusions, obsessions, compulsions, addictions, denials, hysterical ailments, hypochondria, illnesses, behaviours harming the self, behaviours harming others, manias, and phobias):

***** Anecdote: (Defining Moment or Epiphany)

<Add information here>

***** History:

<Add history here>



**** ACTIVE 📃 Write Character Synopsis:

***** Write a One Sentence Character Summary:

Write a Short Character Synopsis in 3rd person for each character: 

(*Warning!* This is all about the character on a monologue, talking about themselves)

Each Character Synopsis is to be written in first person, (i.e., The character is talking about "themselves", telling the story from their individual point of view, life experiences, emotions, words, as opposed to how others may view them).

Our character is on a rant, talking all about herself..., always bringing the subject back to personal perspective and personal truths. Soap Box time!

****** Examples:

******* 📃 Huckleberry Finn (example character synopsis - replace name and content)

Hi! My name is Huckleberry Finn... you can call me "Huck" for short if you like...  Don't pay no attention to anything that famous man behind the curtain may have said about me... That man Samuel Langhorne Clemens, who calls himself Mark Twain... He may know some things about me but he ain't never walked in my shoes!  That's for sure!  Rich author riverboat caption and all... Let me tell you a few things he don't know about me!

For instance... Yadda yadda yadda...  Folks may call me a vagabond, but they don't know the truth of my story... If they knew about the time I had to... blah, blah, blah, ... They would change their minds and see me in a completely different light...  etc...

*(On and On... Huck goes on a personal rant all about himself!)*

******* 📃 Your Next Character Name Here: (add more character headings below until all are done)

Add your character's personal dialog in this space... Rename title above to your character's name...

*** NEW 👥 Major Characters Summary:

:README:
Write a one page synopsis (or 600 words) about the major characters in your story...
:END:

*** NEW 👥 Minor Characters Summary:

:README:
Write a half page synopsis (or 300 words) about the minor characters in your story...
:END:



** SOMEDAY 🗓 Editorial Calendar /(Master Template)/

Make an editorial Calendar for this project right here where it belongs!  You won't loose it! and you can access it quickly without having to search for it elsewhere. Org-Mode excels for this task!  Take advantage of its powerful scheduling, agenda, and filtering capabilities!

\newpage
* ⎘ Meta: /(templates etc.)/   :noexport:
** 📄 Introduction:

This =Meta= section provides skeleton templates for use within your project(s).  Any sub heading under this Meta: group can be utilized by copy-pasting the collapsed heading into any of your existing project sections (i.e., making a clone anywhere you need to create a new section based on the template's structure)... 

Or... You could try mashing several cloned templates together to create a totally new project heading with a totally different structure... The intent of this is to save lots of time starting up a new custom writing project.  Lets see if it helps. :trollface:

\newpage

** 📄 Instructions:

- Choose one of the templates below and copy it (folded).  

- Paste the copied template as a new clone within your project's book, planning, or research section...  

- Change the name of your copied template to a specific title needed to fit in with your project's story-structure...  In the case of Logs or Tasks, you probably will keep those titles as they are universal... but you may wish to further qualify them by adding a prefixed category word.

\newpage
** NEW 📖 Chapter/Episode: ~#~ /(Master Template)/
:README:
   *Chapters/Episodes* are the *Top Level Headings* within the =Book:= Section of this Org Book Publishing project...  Clone this *New Chapter/Episode #:* Master Template and paste it as a child under your =Book:= outline heading... Do this whenever you need to start a new chapter...

   The structure of this template is all set up for you ahead of time to allow you to immediately begin writing...  Replace titles to suit your needs, but keep the structure of *Chapter / Scene (sub-chapter)* intact... i.e., change names only...
:END:
*** ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/
      To Open a Link Type: ~C-c C-o~

      =-or-= Simply Fill in the Template Link Placeholders Below 
           & copy/paste more placeholders as needed... ;-)
:END:

*Add links to Anything Deemed Important to the Writing of This Chapter:*
/(Links to Websites, Other Stories, Images, Sound, Video, Whatever...)/

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] -

\newpage

*** 🔖 Scene  1: /(Replace With Title or Simply Use:/ ~#.1.1~ /etc.)/
:README:
   Scenes are the DNA that make up the chapters in a novel or episodes in a production... Each Scene could have its own title or phrase or it could not have a title but instead sub chapter numbering only...

   Chapters may contain several scenes... There can be many twisty paths all alike (or all different)... %~)

   This *Scene Template* could =ALSO Serve As A CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
          /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
          /and this could be added with or without inclusion of/
          /the scene name headings.../
:END:

~<insert Scene Content Here>~

Lorem Ipsum Lorem Ipsum dolor sit amet, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante.

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Add More Scene Headings Below as Needed for Chapter=

*** 🔖 Scene  2: /(Replace With Title or Simply Use:/ ~#.2.1~ /etc.)/
:README:
   Scenes are the DNA that make up the chapters in a novel or episodes in a production... Each Scene could have its own title or phrase or it could not have a title but instead sub chapter numbering only...

   Chapters may contain several scenes... There can be many twisty paths all alike (or all different)... %~)

   This *Scene Template* could =ALSO Serve As A CHAPTER INTRODUCTION= if you need one...

   =Note:= /You also have options to export with TeX directives/ 
          /to add sub chapter numbering e.g., ~1.1.1...~ etc.../
          /and this could be added with or without inclusion of/
          /the scene name headings.../
:END:

~<insert Scene Content Here>~

Lorem Ipsum Lorem Ipsum dolor sit amet, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante.

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

=Add More Scene Headings Below as Needed for Chapter=

*** 🗒 Background Notes: /(Chapter Template)/
:README:
   *Background Notes*, /(unlike Scenes, Back Stories, Summaries etc.)/ Should be written in =OUTLINE= form to aid in organization of events, etc... This section is =NOT the place to create NEW ideas=, but rather to =organize EXISTING ideas you have already written=...

   =None of the Content Written Here Should be Added to any Chapter/Scenes within your Book= =(THIS IS A META PLACE)= 

   /i.e., Your Books Internal Analyst Behind the Curtain So-To-Speak... %^)/
:END:
**** 🗒 Note 1: <2020-05-10 Sun>

+ Mark each note's timestamp to its initial creation time. This will enable emerging notes for chapters to be searched chronologically, and to give you an idea of how things evolve over time...

+ Add anything you need here under this heading formatted any way needed to present the data... Sub levels are fine, tables are fine... etc.  This is your chapter's Notebook, Scrapbook, whatever any extra info/metadata you feel is important to record...

  + Use bulleted lists/sublist etc. if needed...

1. Or Numbered Lists...

|----+--------|
| Or | Tables |
|----+--------|
|  1 |    2.3 |
|----+--------|

Do any or all the above to help get the concepts and images of your book clear in mind...

**** 🗒 Note 2: <2020-05-10 Sun>

Each new note needs to get its own heading and initial timestamp...

****** Quid Novi?

Quid Novi? Lorem Ipsum dolor sit amet,consectetur adipisicing elit, sed doeiusmod tempor incididunt ut laboreet dolore magna aliqua. Ut enim adminim veniam, quis nostrudexercitation ullamco laboris nisi utaliquip ex ea commodo consequat.Duis aute irure dolor inreprehenderit in coluptate velit essecillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatatnon proident, sunt in culpa quiofficia deserunt mollit anim id estlaborum.

**** 🗒 Phasellus orci: <2022-08-20 Sat>

Etiam tempor elit auctor magna. Nullam nibh velit, vestibulum ut, eleifend non, pulvinar eget, enim. Classaptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Integer velit mauris, convallis acongue sed, placerat id, odio. Etiam venenatis tortor sed lectus. Nulla non orci. In egestas porttitor quam. Duis nec diameget nibh mattis tempus. Curabitus accumsan pede id odio. Nunc vitae libero. Aenean condimentum diam et turpis.Vestibulum non risus. Ut consectetuer gravida elit. Aenean est nunc, varius sed, alquam eu, feugiat sit amet, metus. Sedvenenatis odio id eros.

|----------+-----------+-----------+-----------+-------------------|
| Inceptos | Venenatis | Convallis | Curabitus | Nunc vitae libero |
|----------+-----------+-----------+-----------+-------------------|
| test 1   | test 2    | test 3    | test 4    | test 5            |
|----------+-----------+-----------+-----------+-------------------|

Yadda, yadda, yadda. etc...

\newpage

*** 📒 Back Stories: /(Chapter Template)/
:README:
   This section is for a chapter's Back Story development... The following tips will help you manage development of your back stories and how they will best fit into your evolving story... 

   - =Keep Things Organized:=

      + *Add Time Stamped Background Notes:* /(within the Background Notes/
          /section above)/ about new content added to this Back Stories
          section as you progress over time...

      + *Add Time Stamps to:* Sub-headings within the Background Notes 
          Section that reflect back to paragraphs written within 
          this section...

      + *Add TODO Keywords* to sub-headings within the Background Notes 
          Section reflecting back to paragraphs written within 
          this section...

   Doing the above steps will help you keep track of back story development and get better organized about how your book is developing, what areas need the most work, seeing problems that need to be resolved, etc.  Most importantly, this will help prevent you from making any grave mistakes causing contradictions within your story later... /(unless that was your intention "Alfred Hitchcock")/... In any case you will be better informed by keeping things organized here where you can see them and resolve them quickly...

   =The Content Written Within This Section May or May Not be Added to actual Chapters/Scenes of your Book...=
:END:
**** 📒 Back Story Example One: <2020-05-10 Sun>

=Note:= This is an example of a back story related to this chapter, 
       or possibly connecting to another chapter in your book... 

Write it down in the rough here and then later you can develop it further as needed. Keep Background Notes about this back story as well, AND keep them up to date as this story develops!

\newpage

**** 📒 Phasellus orci: <2022-08-20 Sat>

=Note:= This is an example of a back story /(with an actual title)/ 
       which has a companion Background Note /(by the same title)/ 
       associated with it. Keep the companion Background Note up 
       to date with developments happening in here...

The following Back Story is related to this chapter, but ALSO possibly connecting with other chapters within this book... 

Write it down in the rough here and then later you can develop it further as needed. Keep your Background Notes about this back story up to date as well...

\newpage

*** 🗡 Plot Summary: /(Chapter Template)/
:README:
   Plot Summaries, /(Just Like Background Notes)/ are ALSO =META DATA= Not Intended to be Added back to the Chapters/Scenes of your Book... The purpose of Plot Summaries are to help you during planning stages where you are trying to resolve that twisty mess you created... OMG!

   Keeping the above in mind while writing the plot summary of a chapter, will help you get better organized about how your book is developing, what directions it is taking, what areas need the most work, where problems or inconsistencies may arise, etc.  

   Most importantly, this will help prevent you from making any grave mistakes causing contradictions within your story later... /(unless that was your intention "Alfred Hitchcock")/... In any case you will be better informed by keeping all your plot tasks here where you can see them and resolve them quickly...
:END:

=Plot Summary= /(example)/

In this chapter we are dealing with yadda yadda yadda which must be resolved with yadda yadda yadda.  But be careful about Yadda Yadda Yadda as she does not exist in this book at all!  What?  Nevermind... She never existed... Only in your dreams...

\newpage


** ⎘ Templates:
:README:
   Use this space to add time stamped log note entries for any pourpose you may need...

   *To create a Time Stamped Entry, Use Key Command:* ~C-c .~

   Make your new entry a =sub-heading under a Log section= heading /(as above but, wherever else you may need a collection of log entries)/.

   Keep your Log Entries in Decending Chronological Order. /(i.e., put your newest entries on top)/

   This serves as a replacement for my Scrivener planning Logs /(Currently implemented as markdown files outside of Scrivener)/... Each ~Org-based~ Writing project will have one or more of these logs right inside of it close to the things the logs are actually about...  No more fumbling and guessing which log was I useing for what? Now, not only can I find them, I can make them into tasks, TODOS, and prioritize them to boot! Consider this my new official general template for logs going forward...

   ="Onward We Row Mates... Through the log jam!"=
:END:
*** NEW 🗓 LOG: <2021-03-29 Mon> Generic Title /(General Log Entry Template)/
:README:
   - *Go To One of the HEADINGS Below:* /(Summary, Details, or Sub Headings)/

      =Punch the Time Clock= At the heading And then begin working on a task related to that Heading... =Your Time IS being Recorded Now= 

   - =Use These Commands:= /as you work to keep track your time.../

      + *Clock IN:* ~C-c C-x C-i~ 

                    /(Begin OR Resume Clocking Current task)/

                    This creates a new :CLOCKING: Time Card Entry just
                    underneath the HEADING...

                    Do this just before starting work on the task... 
                    Be in control of your life!

                    After doing the above, you can go away and do some 
                    work, leaving this heading, log note, etc. to visit 
                    other files and/or work on them etc. The clock will 
                    be recording your time all the while... You will see 
                    in your mode line the elapsed clock time ticking away 
                    as you work on a task /(hopefully related to this clock!)/
                    and NOT Yac Shaving or being sidetracked!!!

      + *RETURN to Clock Heading:* ~C-c C-x C-j~

                        /Go back to the place where you started the clock.../

                        You do this after you have worked on a task for a 
                        while and you need to come back to update the item's
                        info etc., and/or stop the clock before going off to 
                        do something else unrelated to the log entry...

      + *Clock OUT:* ~C-c C-x C-o~ /(to stop clocking your time on task)/

                      This *Finalizes the Time Card Entry* within:
                      ~:CLOCKING:~ /(created earlier when you started the/ 
                      /clock)/...

                      The Clock Entry changes showing start timestamp, end timestamp, and total time worked during this segment...  

                      =Please DON'T Forget= /Like I often do, LOL.../ i.e.,
                      Leaving a clock running all day by accident, or worse,
                      leave it dangling with the file closed only to open it
                      again and get that nasty *Org-Mode Message:* /"What do/
                      /you want to do with this?"/ If you do something like 
                      that you can always come back and directly edit the 
                      clock times by hand to amend them...  After changing 
                      clock times or dates, etc... Whatever...

                      ="Onward We Row Mates... Through the log jam!"=

      + *Update Time Card Entry:* ~C-c C-c~ 

                  This command will change the total time at the end showing 
                  your new calculated time...

                  If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

      + *Clock Out & Mark Items Done:* ~C-c C-t~

            When you are all done with a Log Entry use the above key 
            command to mark its Heading *TODO* tag to: *DONE* /(Most of the/ 
            /time this will ALSO clock you out if you are still clocked/ 
            /into the item... But not allways in my experience.../  
            So make sure you are also clocked OUT of an Item After 
            marking it DONE... Type: ~C-c C-x C-j~ to check this...
            /(if no running clock it will tell you and place your/
            /cursor at the heading where you LAST CLOCKED OUT)/

      + ~C-c C-x C-q~ *Cancel Current Clock:* /(in case of accident)/

                      This removes currently running clock and forgets 
                      any time accrued or associated with it...

      + ~C-c C-x C-d~ *Display Clocking Info:* 

                      /This will show elapsed times to the right of headings.../
                      =Warning!= Using this command will CLUTTER ALL the headings
                                within your org file with those timestamps!!!

   - Once all of this has become routine for you, =go ahead and remove this= ~README~ =drawer from this template=... That way it does not get copied when you need to clone new log entries...
:END:

This Log Entry is about: Yadda... Yadda... Yadda...

\newpage

**** 📚 Reference:

- *Link to Project:* [[][] ]

- [[URL][Link Name] ] *Heading:* /(comment)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] /(_)/

- [[][] ] /(_)/

- [[][] ] /(_)/

\newpage

**** ⏰ Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW ✅ Summary: [0/3]
:README:
   This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

   Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...

   Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...
:END:

Yadda... Yadda... Yadda...

1. [ ] *__:*

2. [ ] *__:*

3. [ ] *__:*

\newpage

**** NEW 📒 Details:
***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

- [ ] *__:* /(__)/

\newpage

*** NEW 👤 New Character: /(Master Template)/
**** 💬 Profile:
***** 🗂 Name, Rank, S/N:

|--------+----------------|
| Name:  | put name here  |
|--------+----------------|
| AKA:   | put alias here |
|--------+----------------|
| Title: | put title here |
|--------+----------------|
| Rank:  | put rank here  |
|--------+----------------|

\newpage

***** 📄 Summary (Sentence):  
:README:
   Put a single sentence summary of the character's storyline here.
:END:

\newpage

***** 📃 Summary (Paragraph):  
:README:
   Put a single paragraph summary of the character's storyline, motivation and description. Loosely based on what you will write from the snowflake steps.
:END:

\newpage

***** 🍦 Motivation
:README:
   The character's motivation /(what does he/she want abstractly?)/
:END:

\newpage

***** 🥇 Goal
:README:
   The character's goal (what does he/she want concretely?)
:END:

\newpage

***** 🤺 Conflict
:README:
   The character's conflict (what prevents him/her from reaching this goal?)
:END:

\newpage

***** 💡 Epiphany
:README:
   The character's epiphany (what will he/she learn, how will he/she change?
:END:

\newpage

***** 🔤 Basics:

|-----+--------+---------+--------+--------+------------+-------------|
| Age | Gender | Species | Height | Hair   | Complexion | Nationality |
|-----+--------+---------+--------+--------+------------+-------------|
|     |        |         |        | color, |            |             |
|     |        |         |        | etc... |            |             |
|-----+--------+---------+--------+--------+------------+-------------|

|-----+------------+------+--------+------+------------+-----------|
| DOB | Birthplace | Race | Weight | Eyes | Handedness | Ethnicity |
|-----+------------+------+--------+------+------------+-----------|
|     |            |      |        |      | right      |           |
|     |            |      |        |      | left etc.  |           |
|-----+------------+------+--------+------+------------+-----------|

\newpage

***** 👪 Family

|----------------+----------------------+----------+------------+------------+----------|
| Marital status | Spouse(s)/Partner(s) | Children | Bio Father | Bio Mother | Siblings |
|----------------+----------------------+----------+------------+------------+----------|
|                |                      |          |            |            |          |
|                |                      |          |            |            |          |
|----------------+----------------------+----------+------------+------------+----------|

\newpage

***** 🥂 Social

|-------------+------------------------+------------+---------------+------|
| Citizenship | Social status          | Job/career | Position/role | Rank |
|-------------+------------------------+------------+---------------+------|
|             | Fugitive, criminal,    |            |               |      |
|             | up-standing            |            |               |      |
|             | member of public, etc. |            |               |      |
|-------------+------------------------+------------+---------------+------|

\newpage

***** 🏹 Skills Etc.

|--------+---------+-----------------+-----------|
| Skills | Hobbies | Talents / Gifts | Languages |
|--------+---------+-----------------+-----------|
|        |         |                 |           |
|        |         |                 |           |
|--------+---------+-----------------+-----------|

\newpage

***** 💪 Physical Attributes
:README:
   The Character's Physical description.... 
:END:

\newpage

***** 😇 Personality
:README:
   The Character's Personality... yadda yadda yadda
:END:

\newpage

****** Likes / Dislikes

:README:
The Character's Likes / dislikes, yadda yadda yadda...
:END:

***** 📈 Personal History
:README:
   Character’s personal history. Yadda yadda yadda...
:END:

\newpage

**** 📃 Character Synopsis:
:README:
   - Add the Character Synopsis you wrote about this character in your project's main "Tasks:" section, which was a Snowflake Method step you completed if you are using this Project Skeleton the way it was designed to be used...

      + Each Character Synopsis has been written in first person, (i.e., from the character's own life experiences, emotions, words). This is about the character on a rant, talking all about herself, bringing the subject always back to personal perspective and personal truths... Soap Box time!
:END:

\newpage

**** 🗒 Worksheet:
:README:
   This is your scratch pad worksheet for loosely drafting up new characters before organizing all the information into a Character Profile and Character Synopsis... Free form in here... Let the muses take complete control in this space...
:END:

\newpage

*** NEW ♾ New World: /(Master Template)/
:README:
   - *DEFINITION:*

      =From Wikipedia:= "In its most general sense, the term "world" refers 
      to the totality of entities, to the whole of reality or to everything 
      that is. The nature of the world has been conceptualized differently 
      in different fields."

      *For Our Purposes as Fiction Authors:* Our Definition shall be a
      *"plurality of worlds"* Worlds which are Still =ALL encompassing BUT=
      =Not Encompassing ALL= so-to-speak...

      Worlds are Different than Regions because Worlds simply "exist" 
      without the influence of any outside artificial influence... 
      Worlds can be quite "nebulous" ♾ creatures! Regions are based on 
      defined formalized constraints...

   - *World Creation can be Tricky:*

      If you fall into a black rabbit hole through the centre of the earth,
      /(Like Alice).../ What happens when you come out the other side?  
      Will everyone in China be upside down?

      Expanding on the confusing =ALL Encompassing= statement from our 
      *World* definition above, The following ideas are assumed for:
      *New Worlds Created Here:*

      =A= *♾ New World* =May-Or-May-Not Contain One-Or-Many= *Locations/Regions* 

      =A= *♾ New World* =May-Or-May-Not Contain One-Or-Many= *Planets or Satellites*

      =A= *♾ New World* =May Be Something OTHER than:= *Planet or Satellite*

      =A= *♾ New World* =May-Or-May-Not be BASED on= *Classical Euclidean Space*

      =A= *♾ New World* =May CONTAIN or BE CONTAINED by OTHER WORLDS or THINGS!!!=

      =And For-that-matter...= 

      Worlds, Regions, Locations, Planets, Satellites, COULD 
      ALL contain One or MORE New Worlds within them!

      *New Worlds Containing Guess what?*

      =OMG Girl! Do The Math! %^)=

      /(If you write Sci-Fi, the possibilities are mind boggling!)/

      /"Eat just a wee bit of the proper side of that mushroom and you/ 
       /will be too big to be a dog's meal but small enough to follow/
       /the rabbit through/ /that small door..."/

      =For Most Cases= *♾ New World:* Items will be created in conjunction 
      with corresponding Regions, Planets, Groups, etc... /(no matter what/
      /their hierarchical relationship may be...)/

   - [ ] *Usage:* [0/4]

      For most common cases, you will need to create a New World as 
      a container for any defined Regions, Planets, Groups, etc., 
      Which... in turn were created because they are the reference 
      source for elements within your evolving story (book)...

      However, you may be inspired to create much more interesting Worlds
      /(all by themselves unique jewels)/ that end up becoming Bizarr Cases 
      that Do NOT Contain any of the classical kinds of things you might 
      find normally within Euclidean space, depending on the nature of 
      your story...

      =Add:= As Many *♾ New World:* Headings As Needed And Are 
           Important To Include As Reference For The Writing 
           Of Your Book...

      To Add More: *♾ New World* Entries to this Book Project:

      + [ ] =COPY/CLONE This= *♾ New World* /(Master Template)/

             =Include All Sub-Headings And Content= 

      + [ ] =PASTE CLONE:= as: =New Entry= Under: *♾ Worlds:*

             Paste directly under any Existing *♾ New World:* headings
             already in place Under the general: *♾ Worlds:* Heading 
             within the: *🔍 Research:* Section of this Book Project...

      + [ ] =Edit Content to Fit Your Use Case=

             Some Worlds may Contain Regions but NO Planets or 
             Satellites... Other Possibilities abound... 
             Included Templates cover the most general cases... 

             /You are encouraged to customize these templates/
             /for your own needs!/

      + [ ] =Fill In Details Periodically:=

             Add details as you are writing your book, or come back 
             to fill in details later /as your Muses may be inspiring/ 
             /you with visions about some new aspect of this new world/ 
             /while you were off doing something completely different!/  

             IF your muses reveal new ideas/concepts/visions not 
             covered by an existing item below? *Fantastic!* You have 
             a new category to add to this Template and that item will 
             jog your imagination the next time you are describing a 
             NEW WORLD in another Book!

:END:

This Section Defines a Particular & Unique *♾ New World*

*Worlds* and *Regions* are more of an abstract concept than Geographical Planets, Satellites, Nebula, Gas Giants, etc., OR Sociological Groups, Factions, etc...

\newpage

**** 📃 Summary
:README:
   =Usage:= Don't go into too much Detail here...  

           Drill Down into Details using sub-headings 
           Under: *Region Details:* 

           This Space Is For A Short Summary ONLY...
:END:

=Write A Short One Or Two Paragraph Synopsis for a Single:= *Region* 

\newpage

**** 🗒 World Details:
***** ⛮ Type-Class:
:README:

:END:

\newpage

***** ⦝ Origin:
:README:

:END:

\newpage
***** ⚛ Physics:
:README:

:END:

\newpage

***** 📍 Location:
:README:

:END:

\newpage

***** 📐 Dimensions:
:README:

:END:

\newpage

***** ⌬ Shape:
:README:

:END:

\newpage

***** ✨ Regions:
:README:

:END:

\newpage

***** ⌛ Timeline(s):
:README:

:END:

\newpage

***** 🦋 Dominant Species:
:README:

:END:

\newpage

***** 👥 Groups:
:README:

:END:

\newpage

*** NEW ✨ New Region: /(Master Template)/
:README:
   - *DEFINITION:*

      A Region Is Defined As: An "area" or "space" which is broadly 
      divided by physical characteristics /(physical geography)/, any 
      impact characteristics of inhabitants /(bio geography)/, and the 
      interaction of inhabitants with the area's environment 
      /(environmental geography)/. 

      The word *"region"* is taken from the Latin *regio* /(derived from/ 
      /regere, 'to rule')/ In mathematics the term: *"domain"* is a similar 
      concept to the generalized idea of *"regions"* as defined within 
      various geographical sciences: /(e.g., physical geography, ecology,/ 
      /biogeography, zoogeography, environmental geography, ethnography,/ 
      /etc.)/ And of course all of the *Exo-* versions of these as well...

      Geographic regions and sub-regions are mostly described by their 
      imprecisely defined, and sometimes transitory boundaries, except 
      in the case where some governing body has defined artificial borders.

      Apart from geographic regions, there are also hydrospheric and 
      atmospheric regions. /(e.g., oceans, lakes, rivers, discrete/ 
      /climates of elevations above sea level)/... Add to this the 
      infinite possibilities of *"exo-regions"* which are not even 
      defined yet!

            /That is... Until your Muses Inspire you to/
                       /Define a NEW Exotic "exo-region"!/

      Regions are Different than Worlds because they are defined by
      consensus of some governing body or artificial principal...
      Worlds simply "exist" without the influence of any outside 
      artificial constraints... Worlds are "nebulous" creatures!

   - *This Region Business Can Be Tricky:* 

      =A Region Can Exist Such As:= *The French Quarter of New Orleans* 
      which exists inside a *city* located within *yet another defined* 
      *region* called: *"South LA Delta Region"* which could also be called 
      part of the *"Deep South Region"* etc. etc. etc...

      OK... =How About a Region Defined by a Street Intersection?=
      *Times Square* region of *NYC*, /(which is a city but also a region/
      /containing many regions which also contain regions)/...

      If you are a Sci-Fi author the concept of a Location and/or region
      can become even more convoluted... Interdimensional regions may
      exist in fractal permutations all of them suspended in flux within
      the space of a single but fancy space ship...  A space ship which 
      also travels through multidimensional regions of space at the same
      time in parallel with other instances of itself... =OMG!=

      =And For-that-matter...= 

      Worlds, Regions, Locations, Planets, Satellites, COULD 
      ALL contain One or MORE New Worlds within them!

      /(If you write Sci-Fi, the possibilities are mind boggling!)/

      =For Most Cases:= Any *✨ New Region:* Items defined will have 
      corresponding and related Items defined somewhere in the 
      *🔍 Research:* Section as well...

   - [ ] *Usage:* [0/4]

      For most common cases, you will need to create a New Region 
      as a container for a defined Planet, or Group, etc... 
      Which... in turn were created because they are the reference 
      source for elements within your evolving story (book)...

      However, you may be inspired to create a smaller Region 
      which may be contained within a special World, or localized 
      to a planet or other body in space, or even some small 
      microscopic region inside a single drop of water!  
      All of the above depending on the nature of your story...

      =Add:= As Many *✨ New Region:* Headings As Needed And Are 
           Important To Include As Reference For The Writing 
           Of Your Book...

      To Add More: *✨ New Region:* Entries to this Book Project:

      + [ ] =COPY/CLONE This= *✨ New Region:* /(Master Template)/

             =Include All Sub-Headings And Content=

      + [ ] =PASTE CLONE:= as: =NEW Entry= Under: *✨ Regions:*

             Paste directly under any Existing *✨ New Region:* headings
             already in place Under the general: *✨ Regions:* Heading 
             within the: *🔍 Research:* Section of this Book Project...

      + [ ] =Edit Content of:= *📃 Summary* =and:= *🗒 Location Details:*

             Begin Filling in specific Details that fit your book's needs
             and remove other things that do not apply... Generalized items 
             exist for your use and/or modifications... 

             Other Possibilities  be added if needed...
             /(You are encouraged to customize these templates for your/ 
             /own needs!)/

      + [ ] =Fill In Details Periodically:=

             Add details as you are writing your book, or come back 
             to fill in details later /as your Muses may be inspiring/ 
             /you with visions about some new aspect of this new world/ 
             /while you were off doing something completely different!/  

             IF your muses reveal new ideas/concepts/visions not 
             covered by an existing item below? *Fantastic!* You have 
             a new category to add to this Template and that item will 
             jog your imagination the next time you are describing a 
             NEW WORLD in another Book!
:END:

This Section Defines a Particular & Unique *✨ Region*

*Worlds* and *Regions* are more of an abstract concept than Geographical Planets, Satellites, Nebula, Gas Giants, etc., OR Sociological Groups, Factions, etc...

\newpage

**** 📃 Summary
:README:
   =Usage:= Don't go into too much Detail here...  

           Drill Down into Details using sub-headings 
           Under: *Region Details:* 

           This Space Is For A Short Summary ONLY...
:END:

=Write A Short One Or Two Paragraph Synopsis for a Single:= *Region* 

\newpage

**** 🗒 Region Details:
***** 🌪 Overall Feeling:
:README:
   =Write About The General Mood Of This Region:= 
   Climate? 
   Seasons? /(if any)/ 
   Day/Night Cycles? /(if any)/ 
   Jungle? Desert? Mountains? Farm Land? 
   Ocean? Islands? Atmosphere? Sky? 
   Moons? /(if itself is not a moon)/
:END:

=Include details= /(as described in README above)/ =that relate to this specific Region=

\newpage

***** 🗻 Sights:
:README:
   =Note:= Only mention things that make this place truly unique 
          compared to other neighboring regions... 
          /(if a feature is common to a larger location than that/ 
          /is where the description for that feature should be../ 
          /Not here...  We are drilling down to more unique/ 
          /situations here...)/
:END:

Include: =Prominant Features, Sights, Monuments, Artifacts, Geological Anomalies, Whatever!= in this section...

\newpage

***** 📢 Sounds:
:README:
   =Note:= Only mention the kinds of sound events that would make this 
          place truly unique compared to other neighboring regions... 
          /(if a feature is common to a larger location than that/ 
           /is where the description for that feature should be../
           /Not here... We are drilling down to more unique/ 
           /situations here...)/

   If there are no distinguishing sounds about this location that make it unique compared to other neighboring regions, than simply give lip service to the normal kinds of sounds that are commonly found here... One paragraph should be enough...  
:END:

*Include:* =Prominant Sounds from ANY Source!= Natural, Unnatural, or 
Otherwise, within this section...

\newpage

***** 👃 Smells:
:README:
   =Note:= Only mention the kinds of smell that would make this place
          truly unique compared to other neighboring regions... 
          /(if a feature is common to a larger location than that/ 
           /is where the description for that feature should be.../ 
           /Not here... We are drilling down to more unique/ 
           /situations here...)/

   If there are no distinguishing "smells" about this location that make it unique compared to other neighboring regions, than simply give lip service to the normal kinds of "smells" that are commonly found here... One paragraph should be enough...  
:END:

*Include:* =Prominant Scents / Smells from ANY Source!= Natural, Unnatural, or Otherwise, within this section...

\newpage

*** NEW ∅ New Planet or Satellite: /(Master Template)/
:README:

- =Note:= This can be a tricky thing because a Planet or Satellite may 
          contain many "Locations" or "Regions" and of course the 
          reverse is true as well...  

          =And For-that-matter...= 

          Either a Location/Region or a Planet/Satellite COULD 
          contain One or MORE New Worlds within them as well!

          =OMG Girl! Do The Math! %^)= 

          /(If you write Sci-Fi, the permutations are mind boggling!)/
 
          =For Our Purposes Here: Consider:= *∅ New Planet - Satellite:*   
          Entries to be autonomous... /(i.e., They Stand Alone...)/

          There may or may not be any connections between items defined
          here and items defined in other sections...

          For most Use-Cases any *Planet - Satellite* defined here will have
          its corresponding *Region* defined within this same
          *♾ New World* item as well...

          =Add:= as many *∅ New Planet - Satellite:* headings here as needed and
                are important to include for the writing of your Book...

   =Usage:=

          =If You Need To Add Another:=  *∅ New Planet - Satellite:* 
          Heading to this: *♾ New World* Section: =COPY/CLONE= This Entire:
          *🏞 Region:* Heading, and
          =INCLUDE ALL SUB-HEADINGS and CONTENTS= 

          =PASTE Your CLONE Directly Under this One...=

          =THEN:= Fill in details under: *📃 Summary* and *🗒 Region Details:* 
                 below... periodically... as you are writing your book, or 
                 come back to fill in details later /as your Muses may be/ 
                 /inspiring you with visions about some new aspect of this/
                 /new location while you were off doing something completely/ /different!/

          IF your muses reveal new ideas/concepts/visions not covered by 
          an existing item below? *Fantastic!* You have a new category to 
          add to this Template and that item will jog your imagination 
          the next time you are describing a NEW WORLD in another Book!
:END:

- [ ] *Write A short Synopsis for a* =SINGLE Planet/Satellite= *here:*

- [ ] *Use the following Headings within this* =Planet/Satellite= *section:* 

       /drill down into details under the headings.../

This Section Defines a Particular & Unique *Planet* or *Satellite*

\newpage

**** System, Sector/quadrant
:README:
   Rename System, Sector/quadrant heading above with the actual name of your system, with its specific sector and quadrant coordinates...
:END:

\newpage

***** Controlling party/faction
:README:
  Rename Controlling party/faction heading above with the actual name of your party/or faction...  Fill in key facts in the tables below...
:END:

|-------+------+-------------+----------------+------------|
| Class | Type | Satellites  | Native species | Population |
|-------+------+-------------+----------------+------------|
|       |      | Moons, etc. |                |            |
|       |      |             |                |            |
|-------+------+-------------+----------------+------------|

|--------------+--------------+-------------+------------------+----------------|
| Capital city | Colours      | Symbol      | Government       | Affiliation(s) |
|--------------+--------------+-------------+------------------+----------------|
|              | Example:     | Example:    | Example:         |                |
|              | red, white   | stars,      | Feudal system,   |                |
|              | & blue, etc. | and stripes | caste system,    |                |
|              |              |             | oligarchy,       |                |
|              |              |             | parliament,      |                |
|              |              |             | democracy,       |                |
|              |              |             | plutocracy, etc. |                |
|--------------+--------------+-------------+------------------+----------------|

**** Major cities

\newpage

***** City (continent/region)
:README:
   Change Heading City (continent/region) above to the name of your specific city, continent, or region...

   Then add a detailed description below...  

   Do this to get a feel for the areas the characters will be visiting.
:END:

\newpage

****** Description:

Add Description Here:

\newpage

**** Population
***** Races:
:README:
List all the races that inhabit the area, whether or not they’re native.
:END:

\newpage

***** Predominant religion(s):
:README:
Monotheism?  Pantheism?  Atheism? Name and describe them as needed.
:END:

\newpage

***** Common physical characteristics:
:README:
List the common physical characteristics of long-term inhabitants and native peoples: skin colour, hair colour, build, dress
:END:

\newpage

**** Culture
***** Mannerisms:
:README:
Use this space to illustrate the likely way someone behaves if they’re from this place. Because believe me, a fur-wrapped barbarian behaves in a very different way than a Greek statesman.
:END:

\newpage

***** Cuisine:
:README:
Write about what most people on this planet eat every day?  On festival days?  As delicacies? Taboo?
:END:

\newpage

***** Leisure:
:README:
What do people here do in their spare time?  For fun?
:END:

\newpage

***** Greetings:
:README:
What is considered an acceptable greeting?  In formal setting?  Among friends? Family?
:END:

\newpage

***** Customs:
:README:
The habits of a people that make them unique.  Google it if you’re confused.
:END:

\newpage

***** Quotes:
:README:
Write about how someone from this planet would talk like, or talk about.
:END:

\newpage

***** Superstitions:
:README:
Knowing the power irrational explanations have over a populace can sometimes be good story material.
:END:

\newpage

***** Magic:
:README:
How it is treated by the country.  Whether hated and feared, harnessed for industry, or nonexistent within it’s borders, if magic has a presence in your story you ought to look at how it affects the larger picture than just your heroes and their journey.
:END:

\newpage

***** Beliefs:
:README:
Do I really have to explain this one?  This alone can be your story.
:END:

\newpage

***** Rituals:
:README:
Birth? Coming-of-age?  Marriage?  Death?  Justice?
:END:

\newpage

***** Festivals:
:README:
What do people celebrate?  What are considered holidays?  Why?
:END:

\newpage

**** Transport
:README:
How do people move things?  Armies?  Crowds?  Goods?  Animals?
:END:

\newpage

**** Weather patterns
:README:
Tropical?  Stormy?  Cold?  Earthquakes?  Climate in general?
:END:

\newpage

**** Resources
:README:
What does the planet export?  Import?  Make?  Is famous for?
:END:

\newpage

**** History
:README:
Everyone comes from somewhere.  People just don’t up and appear on islands and such.  I mean, even Native Americans walked across a land bridge way back in the day. Europeans came from Romans and Greeks and Celts and Gauls and more.  Very few people bother to look at this aspect of world-building, and they really should.  Even if a civilization has been around for two thousand years and are elven dragon riders, they came from somewhere.  Even if their mythology says they crawled out of the earth: they came from somewhere.  Examine it here in this space!
:END:

\newpage
*** NEW 👥 New Group or Faction: /(Master Template)/
:README:
   =Note:= This section is for describing the social and government
          aspects of a group which may be located in one single
          place as a primitive society or a more advanced civilization 
          living on one single planet, without space travel, to a HUGE 
          Interstellar Nation spanning one or more systems, possibly 
          an entire Galaxy!

          If you need to add a NEW Group or Faction to your book:
          =COPY/CLONE= This Entire *New Group or Faction* /(Master Template)/
          =INCLUDE ALL SUB-HEADING and CONTENTS= 

          =PASTE Your CLONE as a Sub-Heading Of:= *👥 Groups - Factions:* 
          under the: *🔍 Research:* Section of this Project...

          =THEN:= Adjust sub-headings of your clone to match your needs...
              /i.e., Use Either/ *⚛ Interstellar Nation* /or/ *🛡 Nation*
          =BUT NOT BOTH of THEM!=
:END:

This Section Defines a Particular & Unique *Group* or *Faction* 
within a *♾ New World* ...

\newpage

**** ⚛ Interstellar Nation /(Master Template)/
:README:
   =Definition:=

      /A Galactic Nation/

      A Spacefaring kingdom, empire, country, etc (like Asimov's Galactic Empire, or the Romulan Empire etc.) This type of nation may extend out through a galactic cluster or quadrant, etc.
:END:
***** 📃 Summary:
:README:
   Write executive summary /(abstract)/ here, based on details within all the other sub-headings under this *Interstellar Nation* section...

   This abstract, is a short historical and present summary only... It should include the major goals, motivations... who they’re at war with, etc. i.e., It should include the news headlines, and ledelines...  but not the full story... Results of your research below this summary should be as rich and detailed as you can make it... /(but also indexed!)/
:END:

\newpage

***** 🔤 Basics:
:README:
   Fill in the tables below... Pretty much self explanatory...  Do your research first!
:END:

|------------+---------+--------+----------+----------------+----------------|
| Home World | Colours | Symbol | Currency | Official Langs | Galactic Scope |
|------------+---------+--------+----------+----------------+----------------|
|            |         |        |          |                | number of      |
|            |         |        |          |                | systems, etc.  |
|            |         |        |          |                |                |
|            |         |        |          |                |                |
|------------+---------+--------+----------+----------------+----------------|

|------------------+------------------+----------------+-----------+------------|
| Government       | Current Gov Body | Cur State Head | Military  | Affiliates |
|------------------+------------------+----------------+-----------+------------|
| <fudal, castle,  | <party name>     |                | What's it |            |
| democracy, etc.> |                  |                | called?   |            |
|                  |                  |                |           |            |
|                  |                  |                |           |            |
|------------------+------------------+----------------+-----------+------------|

\newpage

***** 🥂 Social Structure:
:README:
   Who holds power, and how does it affect the way the society works? Is there an aristocracy? If so, how are its ranks structured?
:END:

\newpage

***** 🏛 Government:
:README:
   Describe the Structure and general procedures here...
:END:

\newpage

***** ⚖ Taxation:
:README:
   Write a brief overview of how the people are taxed, and where that money goes.
:END:

\newpage

***** 💵 Currency:
:README:
   What is the currency? What are its sub-denominations?
:END:

\newpage

***** 👥 Population:
****** 🎨 Races
:README:
   Describe the races that inhabit the area, and whether or not they’re native, etc...
:END:

\newpage

****** 𐇑 Common Physical Characteristics
:README:
   Describe the common physical characteristics of long-term inhabitants and native peoples: skin colour, hair colour, build, dress, etc...
:END:

\newpage

****** 🛐 Predominant religion(s)
:README:
   Describe the perdominant religion here... Is it Monotheism?  Pantheism?  Atheism? Name and describe them as needed.)
:END:

\newpage

***** ⛩ Culture:
:README:
   =Definition:=

     That which encompasses the social behaviour, institutions, and norms found within societies of sentient beings, as well as the knowledge, beliefs, arts, laws, customs, capabilities, and habits of the individuals in these groups. Culture is often originated from or attributed to a specific region or location...

     People /(Intelligent social beings living together within a region on any world)/ acquire culture through the learning processes of *Enculturation* & *Socialization*, which is shown by the diversity of cultures across societies throughout the galaxy... 
:END:
****** ✋ Mannerisms
:README:
   Use this space to illustrate the typical way individuals or groups from this place behave... (e.g, A fur-wrapped barbarian behaves in a very different way than a Greek statesman.)
:END:

\newpage

****** 🤝 Greetings
:README:
   Provide some examples of typical greetings here... (e.g, What is considered an acceptable greeting? In formal setting? Among friends? Family?, etc.)
:END:

\newpage

****** 💍 Customs
:README:
   List the habits of a people that make them unique...
:END:

\newpage

****** 👽 Superstitions
:README:
   Knowing the power that =Irrational Explanations= may have over a populace can provide great story material...
:END:

\newpage

****** 🛐 Beliefs
:README:
   =This Item is HUGE...= Completing this section could end up turning into an entire story...
:END:

\newpage

****** 𝌵 Rituals
:README:
   *Add details about:* Births? Coming-of-age?  Marriage?  Death?  Justice?
:END:

\newpage

****** 🎪 Festivals
:README:
   What Do People Celebrate? What Are Considered Holidays? Why? Etc...
:END:

\newpage

***** 🕉 Language
:README:
   This is kind of a big one! Be very careful to point how and why your characters can understand each other, especially if they are from different countries. Language in the real world is a hell of a barrier, but even if you have a Chinese dragon, an Arabian unicorn, a French knight, a Mayan princess, and a Japanese ninja, they can all talk to and understand each other without explanation. Double I-call-BS-points for someone from another world or time!  Anyone who has ever toured Europe can tell you why this is complete bull.  Take a closer look, especially if you’re modeling anything after medieval Europe; only the Church had a universal language: Latin.
:END:

\newpage

***** 🎓 Education
:README:
   How are children taught?  
   Skilled workers? 
   Architects Or Brewers?  
   Is there public education?  
   Higher education?
:END:

\newpage

***** 🚉 Transportation - Shipping
:README:
   Here is where you talk about, how people and things are moved/transported from one place to another. /(e.g., The logistics... Armies? Crowds? Goods? Animals? etc.)/
:END:

\newpage

***** ⚔ Military
:README:
   Write about the military is all about here... 
   What real world military is/can it be based upon? 
   What’s it’s structure?
:END:

\newpage

***** ✨ Major Sectors and Systems :README: This Table Structure may be changed if it is not working well... It may be better to simply create a sub heading for each Major Sector/Quadrant/System... /(of significance to the story)/ =To Be Determined...= :END:

|--------+----------+--------+--------------|
| Sector | Quadrant | System | Description: |
|--------+----------+--------+--------------|
|        |          |        | [[link to Doc]]  |
|        |          |        | [[link to Doc]]  |
|        |          |        | [[link to Doc]]  |
|--------+----------+--------+--------------|

\newpage

***** 📚 History
:README:
   =Everyone Comes From Somewhere...= People just don’t up and appear on islands and such.  The Native Americans walked across a land bridge way back in the day... Europeans came from Romans and Greeks and Celts and Gauls and more... Very few people bother to look at this aspect of world-building, and they really should.  Even if a civilization has been around for two thousand years and are Elven Dragon Riders, they came from somewhere.  Even if their mythology says they crawled out of the earth: they came from somewhere. 

   =Do the research!=
:END:

\newpage

**** 🛡 Nation /(Master Template)/
:README:
   =Definition:=

      /A Non-spacefaring kingdom, empire, country, etc./

      =e.g., The Roman Empire, etc.=

   A Continent, Country, Nomadic Diaspora or Clan... (e.g., Asia, Europe, The Roman Empire, The Gypsies, The Isle of Mann, or the Ba Aka Pygmys, etc.) not to be limited to groups living on Planet Earth only of course...
:END:
***** 📃 Summary:
:README:
   Write executive summary /(abstract)/ here, based on details within all the other sub-headings under this *Nation* section...

   This abstract, is a short historical and present summary only... It should include the major goals, motivations... who they’re at war with, etc. i.e., It should include the news headlines, and ledelines...  but not the full story... Results of your research below this summary should be as rich and detailed as you can make it... /(but also indexed!)/
:END:

\newpage

***** 🔤 Basics:
:README:
   Fill in the tables below... Do your research first!

   =Note:= This Table Structure may be changed if
          it is not working well...  It may be better
          to simply create a sub heading for each
          Major Country with details for each contained
          within... 

          =To Be Determined...=
:END:

|---------+---------+--------+----------+----------------|
| Country | Colours | Symbol | Currency | Official Langs |
|---------+---------+--------+----------+----------------|
| <name>  |         |        |          |                |
|         |         |        |          |                |
|---------+---------+--------+----------+----------------|

|-------------------+------------------+--------------------|
| Gov type          | Current Gov Body | Current State Head |
|-------------------+------------------+--------------------|
| Feudal, caste,    | Party name.      |                    |
| democracy, etc... |                  |                    |
|                   |                  |                    |
|-------------------+------------------+--------------------|

|-------------------+----------------+-----------------------|
| Military          | Affiliation(s) | Number of territories |
|-------------------+----------------+-----------------------|
| What’s it called? |                |                       |
|                   |                |                       |
|-------------------+----------------+-----------------------|

\newpage

***** 🥂 Social Structure
:README:
   Who holds power, and how does it affect the way the society works? Is there an aristocracy? If so, how are its ranks structured?
:END:

\newpage

***** 🏛 Government
:README:
   Structure and general procedures 
:END:

\newpage

***** ⚖ Taxation
:README:
   A brief overview of how the people are taxed, and where that money goes.
:END:

\newpage

***** 💵 Currency
:README:
   What is the currency? What are its sub-denominations?
:END:

\newpage

***** 👥 Population
****** 🎨 Races 
:README:
   Describe the races that inhabit the area, and whether or not they’re native, etc...
:END:

\newpage

****** 𐇑 Common physical characteristics
:README:
   Describe the common physical characteristics of long-term inhabitants and native peoples: skin colour, hair colour, build, dress, etc...
:END:

\newpage

****** 🛐 Predominant religion(s)
:README:
   Describe the perdominant religion here... Is it Monotheism?  Pantheism?  Atheism? Name and describe them as needed.)
:END:

\newpage

***** ⛩ Culture
:README:
   =Definition:=

     That which encompasses the social behaviour, institutions, and norms found within societies of sentient beings, as well as the knowledge, beliefs, arts, laws, customs, capabilities, and habits of the individuals in these groups. Culture is often originated from or attributed to a specific region or location...

     People /(Intelligent social beings living together within a region)/ acquire culture through the learning processes of *Enculturation* & *Socialization*...
:END:
****** ✋ Mannerisms
:README:
   Use this space to illustrate the typical way individuals or groups from this place behave... (e.g, A fur-wrapped barbarian behaves in a very different way than a Greek statesman.)
:END:

\newpage

****** 🤝 Greetings
:README:
   Provide some examples of typical greetings here... (e.g, What is considered an acceptable greeting? In formal setting? Among friends? Family?, etc.)
:END:

\newpage

****** 💍 Customs
:README:
   List the habits of a people that make them unique...
:END:

\newpage

****** 👽 Superstitions
:README:
   Knowing the power that =Irrational Explanations= may have over a populace can provide great story material...
:END:

\newpage

****** 🛐 Beliefs
:README:
   =This Item is HUGE...= Completing this section could end up turning into an entire story...
:END:

\newpage

****** 𝌵 Rituals
:README:
   *Add details about:* Births? Coming-of-age?  Marriage?  Death?  Justice?
:END:

\newpage

****** 🎪 Festivals
:README:
   What Do People Celebrate? What Are Considered Holidays? Why? Etc...
:END:

\newpage

***** 🕉 Language
:README:
This is kind of a big one for me, because I’m always very careful to point how and why my characters can understand each other, especially if they are from different countries. Language in the real world is a hell of a barrier, but even if you have a Chinese dragon, an Arabian unicorn, a French knight, a Mayan princess, and a Japanese ninja, they can all talk to and understand each other without explanation. Double I-call-BS-points for someone from another world or time!  Anyone who has ever toured Europe can tell you why this is complete bull.  Take a closer look, especially if you’re modeling anything after medieval Europe; only the Church had a universal language: Latin.
:END:

\newpage

***** 🎓 Education
:README:
   How are children taught?  
   Skilled workers? 
   Architects Or Brewers?  
   Is there public education?  
   Higher education?
:END:

\newpage

***** 🚉 Transportation
:README:
   Here is where you talk about, how people and things are moved/transported from one place to another. /(e.g., The logistics... Armies? Crowds? Goods? Animals? etc.)/
:END:

\newpage

***** ⚔ Military
:README:
   Write about the military is all about here... 
   What real world military is/can it be based upon? 
   What’s it’s structure?
:END:

\newpage

***** 🏞 Major Territories:
****** 🏞 Territory or Region:
******* 🏰 Major City /(Name Of Major City Within Region)/
:README:
   Write Description of this Major City here...
:END:

\newpage

******* 🏘 Minor City /(Name Of Minor City Within Region)/
:README:
   Write Description of this Minor City here...
:END:

\newpage

***** 📚 History
:README:
   =Everyone Comes From Somewhere...= People just don’t up and appear on islands and such.  The Native Americans walked across a land bridge way back in the day... Europeans came from Romans and Greeks and Celts and Gauls and more... Very few people bother to look at this aspect of world-building, and they really should.  Even if a civilization has been around for two thousand years and are Elven Dragon Riders, they came from somewhere.  Even if their mythology says they crawled out of the earth: they came from somewhere. 

   =Do the research!=
:END:

\newpage

