# -**- mode: org; coding: utf-8 -**-
#+LATEX_HEADER: \usepackage{parskip}
#+LaTeX_HEADER: \usepackage{paralist}
#+LATEX_HEADER: \usepackage[hyperref,x11names]{xcolor}
#+LATEX_HEADER: \usepackage[colorlinks=true,urlcolor=SteelBlue4,linkcolor=Firebrick4]{hyperref}

#+begin_comment
 Setup Files:
   For Cloned Versions of this template, replace file/paths below
   with file/paths to your own custom setup files (which you could 
   convienently clone from the example setup files provided in
   ../org-templates/ directory...

 NOTE: 
   #+CATEGORY: is specified within log-book.org setupfile.
   If you need to change the category do it in log-book.org
   or your cloned version of it...
#+end_comment

#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/ref-book.org
#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/default-tags.org

#+TITLE: HAP - Technical Book Project Skeleton
#+EXPORT_FILE_NAME: HAP_Untitled-Tech-Manual.pdf
#+KEYWORDS:
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2021-03-25 Thu>
#+TEXT: Created: <2020-07-30 Thu>
#+TEXT: Last Published: <2021-03-25 Thu>
#+FILETAGS: templates reference_books

#+DESCRIPTION: HAP - Tech Manual Book Project Skeleton with generic basics already done. Great for documenting technical projects, large or small... Also great for organizing, handling caveats, trying different methods, etc. All while building a sound outline of support docs, steps, best practices... and publishable as a PDF Book suitable for eBook readers... (easily modified for publishing in other eBook formats or for the web)

#+begin_comment
 Don't mess with these unless you have good reason, (e.g., testing).
 Use Setup Tag File above to specify tags for this file...

# #+STARTUP: noptag
# #+TAGS:
#+end_comment

:README:

To use this Technical Book Project Skeleton /(template)/ for your own projects, perform the following steps:

1. *Clone a Copy of this File:* Put it where you normally organize your writing projects.  *Place it within its own folder* named after your intended project title...

2. *Change the* ~#+TITLE:~ *directive at the top of this file* to: /"your Technical Book Project's Title"/

3. *Change the* ~#+EXPORT_FILE_NAME:~ *directive at the top of this file* to: /"your-Technical-Book-Project's-Title.pdf"/ That will be the file name produced thence forward...

4. *Change the* ~#+DESCRIPTION:~ *directive at the top of this file* to /your Technical Book Project's Description/ etc...

2. *Copy/Clone ./media* /(and all its contents):/ To your new project's folder /(where you copied this file).../  Any external documents or images referenced by your book project should be placed within this ~./media/~ directory... All of the external links, images, within the boilerplate examples may be used as examples for getting your own images, and external attachments linked properly...  This single *./media* directory serves media and external attachments for all of the *.org* files contained within: ~.emacs.d/Docs/pubOps~ directory... Cloning any of the other *.org* files will also require copy/cloning the ./media directory relative to them...

4. You don't need to copy the ~./auto/~ directory...  That will be created for you automacally the first time you export this ~.org~ file to ~.PDF~.

5. You also don't need to copy the ~./org-templates~ directory... The files in there are automatically linked and included within this template. You don't need to change those settings unless you wish to customize the already customized tags, and export options. /They are set up correctly for the Tech Book genre already and the category is all set as well... But if you must, you can modify the original files to make your changes rather than cloning to your project directory.../  Realize that if you do that while on the master branch it will get out of sync with origin, check out a local branch to make it easier to get back to defaults if you change your mind later. %^)

6. *Start Planning / Writing Your Technical Book:* /Change headings and structure to match your project's outline sections-chapters-scenes-plots-characters, etc./ Start doing the Tasks within the Tasks section... Have fun doing this...

The *In-Buffer Settings* and *KEYWORDS* specified above are configured to get this file looking good when exported as a Standard PDF file.  Once you have your project directory all set up as above you are ready to export your first PDF as a test run...  To make a PDF out of this file issue the following Emacs command:

   #+begin_src conf
      M-x org-latex-export-to-pdf
   #+end_src

   *-or-* If You Enabled *Xah-Fly-Keys* /"Command Mode"/ Try:

   #+begin_src conf
      SPACE e p
   #+end_src

After *AucTeX* is done parsing/compiling etc., a new *PDF* by the name of ~New-Untitled-Tech-Manual.pdf~ -and- ~New-Untitled-Tech-Manual.tex~ will appear within the same directory as this file...

Subsequent repeated calls to the above command will overwrite your existing ~New-Untitled-Tech-Manual.pdf~ -and- ~New-Untitled-Tech-Manual.tex~ files! You should probably copy these files to the ~./auto/~ directory as well for safe keeping as backups...

*Last Modified: <2021-03-25 Thu>* So far things are pretty basic PDF... We will get fancy with other formats later... I promice... I have to do all this documentation first! /(As you can see, if you been following for the past couple years, things are getting done! Albeit Slowly)/

Enjoy! - Alisha Awen

:END:
* 💡 Scratchpad Refile:           :noexport:
** ☞ Start Here!
:README:
   This Section is mainly to accommodate "seat-of-pants" writers
   /(of which I have been accused of... But I also crave the planning stuff)/.  I often come here for my [[https://projects.csail.mit.edu/gsb/old-archive/gsb-archive/gsb2000-02-11.html]["yak shaving"]] adventures...

   Use this: "*💡 Scratchpad Refile ☞ Start Here!*" section as a quick
   place to document ideas and inspirations as they come along...
   You can refile them later... 

   Even if your quick inspiration was intended for elsewhere?,
   /(e.g., You become bored documenting tedious technical information/
   /when suddenly, out-of-nowhere, an idea for a new sci-fi scene in/
   /that screenplay episode you had in the back of your mind all day!,/
   /etc.)/

   =Ummm.... Parallel Universe?=

   =Sure!= You can put anything in here! We've got that covered for you
         in this Start Here spot. %^)

   Use this section to quickly capture inspired at-the-moment ideas
   =While they are still fresh in mind=

- =How to use?= /Simply Come directly here and do what ever you want.../
                /"Your Crazy Daze are Covered!" Yay!/

  + *Advance your cursor* a few newlines below this README drawer on a
         fresh clean line with some extra space below it as well...
         /(above any previously time stamped entries you may already/
         /have placed).../ If this is the first time, get rid of the
         *"New Business Idea!"* heading example entry below... That
         is only for the template to illustrate these instructions
         by example.

  + *You are now at the top of the list*, /(a few lines below this/
         ~README~ /drawer)/. The time is the present. -and- You are all
         fired up with an idea to write about!

  + *Enter a new timestamp with* ~C-c .~, /(that's: Press ~Ctrl-c~, let go,/
                                       /and then type a Period .)/  A
                                       date chooser panel will pop up...

  + *Press* ~ENTER~ *to auto accept today's date and time.*  A new timestamped
         line will appear with your cursor blinking on the right of it...
         There won't be any future entries above you...
         /(maybe next decade? time travel? %^)/

  + *Advance your cursor a few more lines down* to some fresh empty
         space and Start Typing Your Idea Like Mad!!! 

  + *Don't stop* and don't worry about formatting or organizing it
         until later, after all your inspiration has passed and you are
         ready to organize...

- =After You are Done Writing:=

  + *Come back to the timestamp line where you first started*

          Make sure the timestamp has at least one empty line above
          and below it.

  + *Give the timestamp line a title to the right of the timestamp.*

  + *Make this timestamped line an outline heading*

          =Use:= ~C-c ENTER~ /(that's Press/ ~Ctrl-c~ /let go, and/
                          /then press ~ENTER~)/
          =Note:= make sure this new heading has empty lines above
                and below it...

  + *Adjust this new outline heading level with:* ~M-▷~
          /(this will make it a child of ☞ Start Here! heading above,/
          /rather than a sibling)./

  + *Adjust the space* between your heading and your fantastic idea
          below it to one single blank line.

  + *You can organize everything else later...*

          Don't scare away the muses! Get your story down now!

  + *Then you may go out to play elsewhere little grasshopper...*

          But come back later and organize things... OK? Don't
          create a swamp in here! And don't forget to take your
          bath tonight... ;-)

  Having done the simple steps above any time you get inspired, you will be able to tell your grand children.. "I got my first spark of an idea for that book back in Year, Month, Day, time, second" (50 years later!) Now that is being organized! LOL
:END:
*** NEW 💡 <2020-06-07 Sun> My New Business Idea! /"yeah we've heard that one before"/
:README:
   This is a dummy example of some crazy idea that you may have gotten at the spur of the moment, while you were doing something elsewhere within this project...  After you are done getting as much of the idea as you initally can then you can simply go back to what you were doing before the inspiration segue tore you away... you might want to schedule this as a todo item before leaving though...

   Later when you are free you can come back to file this or place it where it belongs.  In the case of the note below it would probably go in a research folder of a Sci-Fi related project...
:END:
**** Heading 4:

This is a Heading 4 test...

***** Heading 5:

This is a Heading 5 test...

****** Heading 6:

This is a Heading 6 test...

******* Heading 7:

This is a Heading 7 test...

******** Heading 8:

This is a Heading 8 test...

\newpage

* 📖 Book: /(Name of Book)/
** NEW 📃 Synopsis: /(or Introduction:)/
:README:
   This section has been purposefully left blank for you to fill in...

   Use this space to write the main synopsis of your technical work... You can write anything you want here but it is recommended to use the award winning *"Snowflake Method"* created by [[https://www.advancedfictionwriting.com/][Randy Ingermanson]] of Ingermanson Communications, Inc. YES use this method even for Reference or Tech Books.  The same ideas apply except you will be summarizing Real World things rather than make-believe... 

   These steps have been provided for you in the main *"Tasks:"* section...

   - [ ] *Go to the:* =⏰ Tasks:= *Section and do the:* =📃 Synopsis Tasks:=

   - [ ] *After Completing Tasks Mark Them:* ~DONE~

   - [ ] *Place Resulting Synopsis Notes in Here:*

          You will be coming back here to consult these notes for many 
          things as you promote and publish your book.
:END:

\newpage

** NEW 📃 Front Matter:                    :noexport:

Front Matter... yadda... yadda... yadda...

\newpage

** NEW 🔖 Chapter 1: Org-Mode Publishing Tricks
:README:
   Chapters are the *Top Level Headings* within the *Book: Section* of this Org Book Publishing project...  Clone this *Chapter #* Template and paste it under your Book: outline heading whenever you need to start a new chapter...

   The structure of this template is all set up for you ahead of time to allow you to immediately begin writing...  Replace titles to suit your needs, but keep the structure of *Chapter / Topic (sub-chapter)* intact... i.e., change names only...

   You may create any structure you need under the Topic Headings beginning at the next outline level below it...  This will ensure your book gets properly set up for LaTeX exporting to PDF and / or eBook formats with proper table of contents and book structure. 

   *Topics* or (sub-chapters) are the *DNA* that make up the chapters in a book... Chapters may contain several Topics. Topics may contain sub headings, tables, figures, examples, etc...
:END:
*** NEW 📄 Chapter Introduction: /<replace with topic name if needed>/

Here are some *Org-Mode publishing tips and snippits* I have found along the way...  Some of them may get incorporated more formally later /(with docs, etc.),/ but for now... you will have to =discover these treasures below= within this =example chapter=...

\newpage

*** NEW ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/
      To Open a Link Type: ~C-c C-o~

      =-or-= Simply Fill in the Template Link Placeholders Below 
           & copy/paste more placeholders as needed... ;-)
:END:

- [[https://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html#org42aa49f][Pretty fontification of source code blocks]] - *WORG*

- [[https://orgmode.org/manual/Working-with-Source-Code.html#Working-with-Source-Code][Working with Source Code]] - *Org Manual*

- [[https://orgmode.org/worg/library-of-babel.html][Org Library of Babel]]

- [[https://github.com/jkitchin/org-ref][ORG-REF]] - ~JKitchin@Github~

- [[https://youtu.be/fgizHHd7nOo][Org Mode is Awesome!]] - ~JKitchin@YouTube~

- [[https://youtu.be/SzA2YODtgK4][Getting Started with Org Mode]] - ~Harry Schwartz@YouTube~

- [[http://howardism.org/Technical/Emacs/literate-devops.html][Literate DevOps]] -  /Article by: Howard Abrams/

- [[https://youtu.be/dljNabciEGg][Literate DevOps with Emacs]] - ~Howard Abrams@YouTube~

- [[https://zzamboni.org/post/beautifying-org-mode-in-emacs/][Beautifying Org Mode in Emacs]] - /Article by: Diego Zamboni/

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] -

\newpage

*** NEW 📄 New Topic <replace with topic name>

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

*** NEW 🗒 Background Notes:
:README:
The *Background Notes* section of a chapter is a place where you can add notes, ideas, instructions, whatever... close at hand within the chapter, and not have to worry about any of it getting exported and or published to the final output product...  

Nothing within this section will be exported... not even the Background Notes Heading itself.  Use this section any way and for any purpose you wish for things related to the chapter heading that contains it...

The example Notes below have been timestamped as a way to suggest organizing TODO items for a particular chapter you may find yourself working on, or researching... *Use / replace the notes below with / for your own schemes*...
:END:
**** 🗒 Note 1: <2020-05-10 Sun>

1. Enumerated List Item A

    * Enumerated List Item B

       + Enumerated List Item C

       + Enumerated List Item D

2. Something New...

- Bullet checkbox Test one...

   + [ ] Checkbox List:

   + [ ] 

\newpage

**** 🗒 Note 2: <2020-05-10 Sun>

Each new note needs to get its own heading and initial timestamp...

****** Quid Novi?

Quid Novi? Lorem Ipsum dolor sit amet,consectetur adipisicing elit, sed doeiusmod tempor incididunt ut laboreet dolore magna aliqua. Ut enim adminim veniam, quis nostrudexercitation ullamco laboris nisi utaliquip ex ea commodo consequat.Duis aute irure dolor inreprehenderit in coluptate velit essecillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatatnon proident, sunt in culpa quiofficia deserunt mollit anim id estlaborum.

\newpage

**** 🗒 Phasellus orci: <2020-05-10 Sun>

Etiam tempor elit auctor magna. Nullam nibh velit, vestibulum ut, eleifend non, pulvinar eget, enim. Classaptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Integer velit mauris, convallis acongue sed, placerat id, odio. Etiam venenatis tortor sed lectus. Nulla non orci. In egestas porttitor quam. Duis nec diameget nibh mattis tempus. Curabitus accumsan pede id odio. Nunc vitae libero. Aenean condimentum diam et turpis.Vestibulum non risus. Ut consectetuer gravida elit. Aenean est nunc, varius sed, alquam eu, feugiat sit amet, metus. Sedvenenatis odio id eros.

|----------+-----------+-----------+-----------+-------------------|
| Inceptos | Venenatis | Convallis | Curabitus | Nunc vitae libero |
|----------+-----------+-----------+-----------+-------------------|
| test 1   | test 2    | test 3    | test 4    | test 5            |
|----------+-----------+-----------+-----------+-------------------|

Yadda, yadda, yadda. etc...

\newpage

* 📒 Research:                          :noexport:
** 💡 New Topic Ideas:
*** NEW 📄 New Topic /(clone this)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

** 📒 Yak Shaving:
:README:
What is Yak Shaving doing in your Research Folder?  Just as the name implies, this is a place that may have no business being in your book, but nevertheless may be something you need to research on the side in order to get your book written.. 

Things to put here may end up in chapters but you don't know which chapters that may be at this point, so you cannot use a Chapter's Background Notes section for these cases...

Use this section as a place to save and organize new-ideas while you figur out what they may be for, and where they may eventually go...  This section is a great place to start if your are importing existing docs written in markdown, or Open Office, or what ever... import the text from those external docs here first... Then you can organize them here while you figure out how they fit in the larger context of a book project...

The format for this section is anything you like.. And you may put anything you like in here.. (unlike the Start Here section above for seat-of-the-pants writing, this section should be much more organized... Some of the things written seat-of-the-pants within the Start Here section may end up in this Yak Shaving section later when you are ready to structure them further... (after inspiration)
:END:
*** NEW Yak Shaving Heading One:

Note: This is an example of some documentation or research you need to do, the result of which will not be included in your book but will be used as a resource necessary for the creation and or publishing of your book... Add what you need here... 

Use this section's top level heading outline structure.. Create sub-level headings as needed for your purposes...

\newpage

*** NEW Yak Shaving Heading Two:

Note: This is an example of some documentation or research you need to do, the result of which will not be included in your book but will be used as a resource necessary for the creation and or publishing of your book... Add what you need here... 

Use this section's top level heading outline structure.. Create sub-level headings as needed for your purposes...

\newpage

*** NEW Add more yak shaving headings as needed:

Duplicate the top level Outline above to create more headings here as needed... 

Create sub-level outlines below each heading as needed for your purposes.

Anything goes here... You can make this into what ever you want..

\newpage

* ⏰ Tasks:                               :noexport:
:README:
   - Use this space to add time stamped Tasks below for any pourpose you may need...

   - To create a time stamped task entry, use key command: ~C-c .~

   - Make your new entry an outline sub-heading of this project's general *Tasks:* section heading above /(or optionally you could create another more specific Tasks: section wherever else you may need a collection of task entries)/...

   - Keep your Tasks in Decending Chronological Order. /(i.e., put your newest/ 
      /tasks on top)/

   - The three provided tasks below are important first steps to take when first starting a book.  They are based on the "Snowflake Method" by Randy Ingermanson. 

   - These tasks should be started as soon as you create a new project...

   - It is hoped that this process will give you a faster, efficient, organized "bootstrapped" head start and teach some guidance about how to properly organize and write your books with a clearer mind, inspired outlook, and renewed motivation...
:END:

*** 📃 Synopsis Tasks:
**** NEW Important Before you start!

NOTE: Before you start you need to answer the following questions:

- What is your main category or genera? ______________...

- You write within this genera because? ______________...

- Readers will be attracted to your books because? _____________________...

After completing above, follow the steps below... 

when you are done with these Synopsis tasks, you will have completed half the battle of writing a book! 
Chapters and topics will flow effortlessly from that...

\newpage

**** NEW Step One - Write a Single Sentence Summary:

Take an hour and write a one-sentence summary of your book:   
   
Something like this:

    "A gourmet chef from Boston acedentally falls into a parallel world, almost destroyed by an arch enemy he did not even know he had, then he discovers he is immortal and meets-re-discovers his ancient soul mate of eons. Together they save the universe after all else fails!"

OK I know... I cheated. The second sentence is a stinger. It needs to stand alone... I often buck the rules... lol

The sentence you end up writing above will serve you forever as a ten-second selling tool.

This synopsis stuff is basic to the bone! It is universal... We cannot buck it!  It's based on human nature... Your sentence above, will serve as a pitch during normal conversations (to see if there is any interest)...

Memorize "your line" to the point that you can say it in your sleep! Turn it into a "slogan" (hopefully a "meme" if you are the lucky type). Your goal is that others will remember and be able to easily tell all their friends (word for word). Networking is the key! You can't do it alone... (songs are also great help) (cartoons and songs are killer!) Social networks open you up to sky limit possibilities!

Lead with your story line when opening a dialog with a total stranger or even your mother. Remain silent after that... Wait to see if there is interest before diving deeper... That and your good body language "posture" will take care of everything...

Important! Closing rules of sales dictate the law of attraction always applies.. Pushing yields negative results... If you push people, they push back.  If you run away from people, they chase you... To eat, or to be eaten... That's what it all comes down to. LOL! Wait to see if there is interest, if not, move on... If yes, do the next step...

When you later write your book proposal, this sentence should appear very early in the proposal. It's the hook that will sell your book to your editor, to your committee, to the sales force, to bookstore owners, and ultimately to readers. So make the best one you can!

\newpage

****** Here are some tips:

- Shorter is better. Try for fewer than 15 words.

- No character names, please! Better to say "a handicapped trapeze artist" than "Jane Doe".

- Tie together the big picture and the personal picture. Which character has the most to lose in this story? Now tell me what he or she wants to win.

- Read the one-line blurbs on the New York Times Bestseller list to learn how to do this. Writing a one-sentence description is an art form. If you become a master at this marketing firms will want you madly!

- Check out [[yt:feD-dImM4a8][LEGO Star Wars: The Last Jedi in 60 Seconds]] (and other 60 second movies like it) for a completely different audio/visual parallel to this literary concept...

\newpage

**** NEW Step Two - Expand Summary to Paragraph

Take another hour and expand your sentence from step one into a full paragraph describing brief overview, technical requirements or challenges, and ending with your proposed solution in a single sentence.

\newpage

***** Make 5 Sentences:

1. Exposition: 

   The first sentence paints the big picture of the problem with a hint of its solution. The purpose of this sentence is to invoke a strong curiosity, desire, and expectation to learn the rest of the book's proposed solution!

2. Second Sentence sets current playing field:

   Outline the circumstances of the current playing field that your book will be addressing. This is the key event that motivated you to find a remedy in the first place.  This section must hit home to our readers as well, inspiring them to follow the rest of the book for answers... 

3. The third sentence tells them what NOT to do by sharing personal blunders sure to hit home with readers...

   Here is where you get to tell some stories... past experience of failed attempts etc.  Not offering the proper solutions yet, but rather showing the palm face human events that finally lead you to discovery of the proper methods & solutions...

4. The forth sentence is where you git to hit the home run!

   This sentence reveals your final best solution to all the challenges presented, giving your readers the impression that reading this book will help them avoid all pitfalls entirely...

5. Summary: (conclusion)

   This last sentence wraps everything up, further supporting the first three sentences with one single statement.  An encouragement and also challenge for your readers to read this book to discover more.

\newpage

***** Using Your One-Paragraph Summary:

You will be using this paragraph in your proposals. It is only for your agents etc.  Not for your readers who need to be kept in the dark about too many details until they read the book...

However, Some of this paragraph (written with parts pourposefully left out or with questions put in place) may end up back-cover copy for your book's promotion.

\newpage

**** NEW Step Three - Expand Paragraph to Synopsis:

Take several hours and expand each sentence of your summary paragraph into a full paragraph. All but the last paragraph should present challenges, pitfalls to overcome. The final paragraph is your proposed best-practice solution.

By this stage, you should have a good idea of the large-scale structure of your book, and you have only spent a day or two, or at most, a week or two, but all that time will not have been wasted! You will now have a good idea if there are going to be problems that need to be worked out. This is good knowledge to have now, rather than after investing 500 hours in a rambling first draft.

At the end of this exercise, you will have a nice one-page skeleton of your book. It's fine if your skeleton does not fit all on one single-spaced page as long as it does not go beyond that... 

Your process now is to grow these ideas as individual chapters and topics.  You have a synopsis "executive summary" suitable for a proposal, and you are well on your way to doing extended promotion...

\newpage

* ⎘ Meta: /(templates etc.)/              :noexport:
** Introduction:

This =Meta= section provides skeleton templates for use within your project(s).  Any sub heading under this Meta: group can be utilized by copy-pasting the collapsed heading into any of your existing project sections (i.e., making a clone anywhere you need to create a new section based on the template's structure)... 

Or... You could try mashing several cloned templates together to create a totally new project heading with a totally different structure... The intent of this is to save lots of time starting up a new custom writing project.  Lets see if it helps. :trollface:

\newpage

** Instructions:

- Choose one of the templates below and copy it (folded).  

- Paste the copied template as a new clone within your project's book, planning, or research section...  

- Change the name of your copied template to a specific title needed to fit in with your project's story-structure...  In the case of Logs or Tasks, you probably will keep those titles as they are universal... but you may wish to further qualify them by adding a prefixed category word.

\newpage

** ✎ Log Book: /(Master Template)/
:README:
   Use this space to add time stamped log note entries for any pourpose you may need...

   *To create a Time Stamped Entry, Use Key Command:* ~C-c .~

   Make your new entry a =sub-heading under a Log section= heading /(as above but, wherever else you may need a collection of log entries)/.

   Keep your Log Entries in Decending Chronological Order. /(i.e., put your newest entries on top)/

   This serves as a replacement for my Scrivener planning Logs /(Currently implemented as markdown files outside of Scrivener)/... Each ~Org-based~ Writing project will have one or more of these logs right inside of it close to the things the logs are actually about...  No more fumbling and guessing which log was I useing for what? Now, not only can I find them, I can make them into tasks, TODOS, and prioritize them to boot! Consider this my new official general template for logs going forward...

   ="Onward We Row Mates... Through the log jam!"=
:END:
*** NEW log: <2021-03-29 Mon> Generic Title /(General Log Entry Template)/
:README:
   - *Go To One of the HEADINGS Below:* /(Summary, Details, or Sub Headings)/

      =Punch the Time Clock= At the heading And then begin working on a task related to that Heading... =Your Time IS being Recorded Now= 

   - =Use These Commands:= /as you work to keep track your time.../

      + *Clock IN:* ~C-c C-x C-i~ 

                    /(Begin OR Resume Clocking Current task)/

                    This creates a new :CLOCKING: Time Card Entry just
                    underneath the HEADING...

                    Do this just before starting work on the task... 
                    Be in control of your life!

                    After doing the above, you can go away and do some 
                    work, leaving this heading, log note, etc. to visit 
                    other files and/or work on them etc. The clock will 
                    be recording your time all the while... You will see 
                    in your mode line the elapsed clock time ticking away 
                    as you work on a task /(hopefully related to this clock!)/
                    and NOT Yac Shaving or being sidetracked!!!

      + *RETURN to Clock Heading:* ~C-c C-x C-j~

                        /Go back to the place where you started the clock.../

                        You do this after you have worked on a task for a 
                        while and you need to come back to update the item's
                        info etc., and/or stop the clock before going off to 
                        do something else unrelated to the log entry...

      + *Clock OUT:* ~C-c C-x C-o~ /(to stop clocking your time on task)/

                      This *Finalizes the Time Card Entry* within:
                      ~:CLOCKING:~ /(created earlier when you started the/ 
                      /clock)/...

                      The Clock Entry changes showing start timestamp, end timestamp, and total time worked during this segment...  

                      =Please DON'T Forget= /Like I often do, LOL.../ i.e.,
                      Leaving a clock running all day by accident, or worse,
                      leave it dangling with the file closed only to open it
                      again and get that nasty *Org-Mode Message:* /"What do/
                      /you want to do with this?"/ If you do something like 
                      that you can always come back and directly edit the 
                      clock times by hand to amend them...  After changing 
                      clock times or dates, etc... Whatever...

                      ="Onward We Row Mates... Through the log jam!"=

      + *Update Time Card Entry:* ~C-c C-c~ 

                  This command will change the total time at the end showing 
                  your new calculated time...

                  If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

      + *Clock Out & Mark Items Done:* ~C-c C-t~

            When you are all done with a Log Entry use the above key 
            command to mark its Heading *TODO* tag to: *DONE* /(Most of the/ 
            /time this will ALSO clock you out if you are still clocked/ 
            /into the item... But not allways in my experience.../  
            So make sure you are also clocked OUT of an Item After 
            marking it DONE... Type: ~C-c C-x C-j~ to check this...
            /(if no running clock it will tell you and place your/
            /cursor at the heading where you LAST CLOCKED OUT)/

      + ~C-c C-x C-q~ *Cancel Current Clock:* /(in case of accident)/

                      This removes currently running clock and forgets 
                      any time accrued or associated with it...

      + ~C-c C-x C-d~ *Display Clocking Info:* 

                      /This will show elapsed times to the right of headings.../
                      =Warning!= Using this command will CLUTTER ALL the headings
                                within your org file with those timestamps!!!

   - Once all of this has become routine for you, =go ahead and remove this= ~README~ =drawer from this template=... That way it does not get copied when you need to clone new log entries...
:END:

This Log Entry is about: Yadda... Yadda... Yadda...

\newpage

**** NEW Reference:

- *Link to Project:* [[][] ]

- [[URL][Link Name] ] *Heading:* /(comment)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] - *_:* /(yadda...)/

- [[][] ] /(_)/

- [[][] ] /(_)/

- [[][] ] /(_)/

\newpage

**** NEW Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW Summary: [0/3]
:README:
   This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

   Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...

   Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...
:END:

Yadda... Yadda... Yadda...

1. [ ] *__:*

2. [ ] *__:*

3. [ ] *__:*

\newpage

**** NEW Details:
***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

***** NEW New Item 1 /(placeholder)/ [0/3]

- [ ] *__:* /(__)/

      #+begin_src conf
       root@dev1:~$ 
       root@dev1:~$ 
       root@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

- [ ] *__:* /(__)/

      #+begin_src conf
       admin@dev1:~$ 
       admin@dev1:~$ 
       admin@dev1:~$ 
      #+end_src

\newpage

** SOMEDAY 🗓 Editorial Calendar: /(Master Template)/ 

Make an editorial Calendar for this project right here where it belongs!  You won't loose it! and you can access it quickly without having to search for it elsewhere. Org-Mode excels for this task!  Take advantage of its powerful scheduling, agenda, and filtering capabilities!

\newpage

** NEW 🔖 Chapter #:  <chapter name> /(Master Template)/
:README:
   Chapters are the *Top Level Headings* within the *Book: Section* of this Org Book Publishing project...  Clone this *Chapter #* Template and paste it under your Book: outline heading whenever you need to start a new chapter...

   The structure of this template is all set up for you ahead of time to allow you to immediately begin writing...  Replace titles to suit your needs, but keep the structure of *Chapter / Topic (sub-chapter)* intact... i.e., change names only...

   You may create any structure you need under the Topic Headings beginning at the next outline level below it...  This will ensure your book gets properly set up for LaTeX exporting to PDF and / or eBook formats with proper table of contents and book structure. 

   *Topics* or (sub-chapters) are the *DNA* that make up the chapters in a book... Chapters may contain several Topics. Topics may contain sub headings, tables, figures, examples, etc...
:END:
*** NEW 📄 Chapter Introduction: /<replace with topic name if needed>/

*Lorem Ipsum *Lorem Ipsum dolor sit amet*, consectetuer adipiscingelit. Duis tellus. Donec ante dolor, iaculis nec, gravidaac, cursus in, eros. Mauris vestibulum, felis et egestasullamcorper, purus nibh vehicula sem, eu egestas antenisl non justo. Fusce tincidunt, /lorem nev dapibusconsectetuer, leo orci mollis ipsum, eget suscipit erospurus in ante./

\newpage

*** NEW ☞ Chapter References:
:README:
   =Org Mode Links Tip:=

      To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/
      To Open a Link Type: ~C-c C-o~

      =-or-= Simply Fill in the Template Link Placeholders Below 
           & copy/paste more placeholders as needed... ;-)
:END:

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] - 

- [[][] ] -

\newpage

*** NEW 📄 New Topic /(template - clone as needed)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

*** NEW 🗒 Background Notes:
:README:
The *Background Notes* section of a chapter is a place where you can add notes, ideas, instructions, whatever... close at hand within the chapter, and not have to worry about any of it getting exported and or published to the final output product...  

Nothing within this section will be exported... not even the Background Notes Heading itself.  Use this section any way and for any purpose you wish for things related to the chapter heading that contains it...

The example Notes below have been timestamped as a way to suggest organizing TODO items for a particular chapter you may find yourself working on, or researching... *Use / replace the notes below with / for your own schemes*...
:END:
**** 🗒 Note #: <2020-05-10 Sun> /(template- clone this)/

Each new note needs to get its own heading and initial timestamp...

\newpage

**** 🗒 Note #: <2020-05-10 Sun> /(template- clone this)/

Each new note needs to get its own heading and initial timestamp...

\newpage
