# -**- mode: org; coding: utf-8 -**-
#+TITLE: HAP - Generic Document Skeleton
#+EXPORT_FILE_NAME: HAP_Generic-Document-Skeleton.pdf
#+TEXT: Copyright © 2022 Harmonic Alchemy Productions & Others
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2021-05-22 Sat>
#+TEXT: Created: <2021-05-21 Fri>
#+TEXT: Last Published: <Not Published>
#+FILETAGS: templates docs unpublished

#+DESCRIPTION: HAP - Generic Document Skeleton with basic structure for smaller documents that don't require so much planning etc. Great for simple outlines, one page docs, short How-Tos, etc., (easily modified to make reports, charts, etc.)  Publishable as a Simple PDF...

#+BEGIN_COMMENT 
=Setup Files:=

   For Cloned Versions of this template, the file/paths below will be relative
   to your parent project directory and as such, should be all set to your new: ~.../your-fiction-book-project/org-templates/~ directory...

=NOTE:= 

   ~#+CATEGORY:~ is specified within ~gen-doc.org~ SETUPFILE.
   If you need to change the category, do it in your cloned version
   of gen-doc.org...

   *SETUPFILE:* ~default-tags.org~ is where tags are set for this project...

   *SETUPFILE:* ~latex-simple-pdf.org~ is for LaTeX Export Configurations 
              to produce a Simple PDF version of your Document...
#+END_COMMENT

#+SETUPFILE: ./org-templates/gen-doc.org
#+SETUPFILE: ./org-templates/latex-simple-pdf.org
#+SETUPFILE: ./org-templates/default-tags.org

:READ_ME_FIRST:
☞ =Instructions:= /(How to Install & Use This Template)/

To use *HAP_Generic-Document-Skeleton.org* /(Org-Mode Generic Doc Project /Template)/ for your own projects, perform the following steps: 

/Use the org-mode Checkboxes to Help You Keep Track of Progress/

1) [ ] *Clone a Copy of This File:*

      Put your clone where you normally organize your writing 
      projects. *Place it within its own master folder... It is*
      *Important to keep this file within its OWN enclosing folder!* 

      Name the project's master folder to reflect your Document 
      project's title... /(what you renamed this .org file to)/...

      =Other Files/Folders will be placed within this master folder...=

2) [ ] *Copy/Clone:* ~./media~ /(and contents)/ *to your new project's Master Folder:*

      Copy this directory /(into your master folder as a sibling of this file).../ 
      Any external documents or images referenced by your Document should 
      be placed within this ~./media/~ directory...

      All external links, images, within the boilerplate examples of this
      template may be used as examples for getting your own images, and 
      external attachments linked properly...  

      This single ~./media~ directory will serve media and external attachments 
      for all of the ~.org~ doc template files from within: ~.emacs.d/Docs/pubOps~ 
      directory /(if they were also copied here to your Project's Master Folder)/

   =Note:=  You DON'T need to copy the ~./auto/~ directory...  That directory
           will be automatically created the first time you export this ~.org~ 
           file to ~.PDF~...

3) [ ] *Copy/Clone:* ~./org-templates~ /(and all contents)/ *to your Master Folder:*

      Copy this directory to your Document's Master Folder, /(as a sibling/
      /of this .org file).../ 

      =Note:= The SETUPFILES Within this directory which are called out and 
             included by this .org file /(above)/ must stay within this 
             directory...  

             Other SETUPFILES within this directory are used by other book 
             project templates and are not needed for this Simple Document 
             Project... You may remove them if you wish... They are small
             text files not bothering you... If you clone another 
             ~HAP_<book-template>.org~ file into this project folder it will 
             pick up its associated SETUPFILES automatically, so consider 
             that if/when you decide to delete other UNUSED SETUPFILES...

4) [ ] =Start Sketching Out Your Document NOW Before You Loose It!=

      =NOTE:= You may be doing this because you have some new idea brewing in
            your mind and you need to write that down before you forget!
            =Right?=  Therefore... as soon as you are done with the first
            steps above, =STOP= and go immediately to the:

                   ~💡 Ideas Scratchpad Refile / ☞ Start Here!~ 

            section and read the ~:README:~ directly under that heading...  
            Then write your idea down quickly /(as per the README instructions)/ 
            to get your inspiration recorded before you forget it...  

            Later, After you have all your ideas sketched out and you are 
            ready to be in an ="organized mood"= /(rather than creative mood)/ 
            /This does not imply being organized cannot be a CREATIVE PROCESS/ 
            Then it is time to:

            =Come Back Here And Finish Setting Up This Project...=

5) [ ] *Finish Setting up this Project LATER...* [0/3]

    - [ ] *Change the* ~#+TITLE:~ *directive at the top of this file:* 

          Change to: /"your Simple Document Project Title"/

    - [ ] *Change the* ~#+EXPORT_FILE_NAME:~ *directive at the top of this file:*

          Change to: /"your-Document-Title.pdf"/
          This will be the file name(s) produced during export thence forward
          /(including auto generated files: .tex, etc...)/

    - [ ] *Change the* ~#+DESCRIPTION:~ *directive at the top of this file:*

          Compose /Your Document Description/ as a short paragraph here...

    - *The* ~./media~ *Directory is ALL Set:*

         Any external documents or images referenced by this Simple Document
         project should be placed within this ~./media/~ directory... This single 
         ~./media~ directory will serve media and external attachments for this 
         and any other ~.org~ files you may end up creating here, as well as
         being the media repository used by LaTeX during publishing...

    - *Purpose of the:* ~./auto/~ *Directory:* /(you do not need to copy this)/

         This is or will-be an auto generated folder where your output ~.PDF~ 
         files are created and placed during LaTeX export. You DO NOT need 
         to copy this folder as it is auto generated during org-mode LaTeX 
         processing...

         LaTeX processing will not delete any prior files contained here... 
         Some of them will be updated, but will have backups...  Any files 
         you place within this folder will NOT be lost, unless you delete 
         them... This folder is a good place to store other temporary files 
         you may be creating, generating.. etc...

    - *Purpose of the:* ~./org-templates~  *Directory:*

         The files in here are automatically linked and included within this
         template. You don't need to change those settings unless you wish to
         customize the already customized tags, and export options.

         /They are allready set up correctly for the simple document genre,/
         /and the category is all set as well... But you can and may modify/
         /the original files to fit your needs.../

7) [ ] =Export/Publish to PDF File:=

      The *In-Buffer Settings* specified by the SETUPFILES above will 
      get this file looking good when exported as a Simple PDF file.  
      Once you have your project directory all set up as above you are 
      ready to export your first PDF as a test run...

         *Issue the following Emacs command:*

            ~M-x org-latex-export-to-pdf~

         *OR* If You Enabled *Xah-Fly-Keys* /"Command Mode"/ Try Shortcut:

            ~SPACE e p~

         *OR Export to OTHER Formats:* /(not usefull for this template)/

            ~C-c C-e~

            /(a pop-up will show allowing you to choose export method)/

      After *AucTeX* is done parsing/compiling etc., new files by the name of: ~
      ~HAP_Generic-Document-Skeleton.pdf~ -and- ~HAP_Untitled-Fiction-Book.tex~ 
      will appear within the same directory as this file...

      Subsequent repeated calls to the above command will overwrite your existing
      ~HAP_Generic-Document-Skeleton.pdf~ -and- ~HAP_Generic-Document-Skeleton.tex~ 
      files! /(make backups first if needed!)/
      You should probably copy these files to the ~./auto/~ directory as 
      well for safe keeping as backups...

      =If you chose the last option above= LaTeX will output files with other
      extensions for those other output formats...

      =NOTE:= This Generic Document Template is not initially a good
            candidate for other eBook formats, but you possibly may
            use it as a starting point for customizing & creating one...

      =If YOU EXPERIENCE LaTeX ERRORS:= 

         *Consult Buffer:* ~*Org PDF LaTeX Output*~

=These Instructions Were Last Modified:= <2022-10-19 Wed> 

So far things are pretty basic PDF... There are no plans to add any other eBook formats to this *Generic Document* template... However, I am looking into adding EPUB configurations for *HAP_Fiction-Book* and *HAP_Technical-Book* Skeletons, /(templates)/.

=Please Open an ISSUE At:= https://github.com/harmonicalchemy/modular-emacs/issues
   
Please use Issues to Ask Questions, Report Problems/Bugs etc., and Suggest Ideas for Improvement... =You guys are my Product Managers=  I am only a User of ONE "seat". 
Other folks UX metrics are sorely needed!! Thanks!

=Enjoy!= - Alisha Awen
:END:

* NEW 💡 Scratchpad Refile:                        :noexport:

=Note:= /This section is not published!/ 
       /Use this scratch pad for private-notes etc.../

** NEW ☞ Start Here!
:README:
   This Section is mainly to accommodate "seat-of-pants" writers
   /(of which I have been accused of... But I also crave the planning stuff)/.  I often come here for my [[https://projects.csail.mit.edu/gsb/old-archive/gsb-archive/gsb2000-02-11.html]["yak shaving"]] adventures...

   Use this: "*💡 Scratchpad Refile ☞ Start Here!*" section as a quick
   place to document ideas and inspirations as they come alone.
   You can refile them later... 

   Even if your quick inspiration was intended for elsewhere?,
   /(e.g., You become bored documenting tedious technical information/
   /when suddenly, out-of-nowhere, an idea for a new sci-fi scene in/
   /that screenplay episode you had in the back of your mind all day!,/
   /etc.)/

   =Ummm.... Parallel Universe?=

   =Sure!= You can put anything in here! We've got that covered for you
         in this Start Here spot. %^)

   Use this section to quickly capture inspired at-the-moment ideas
   =While they are still fresh in mind=

- =How to use?= /Simply Come directly here and do what ever you want.../
              /"Your Crazy Daze are Covered!" Yay!/

  + *Advance your cursor* a few newlines below this README drawer on a
         fresh clean line with some extra space below it as well...
         /(above any previously time stamped entries you may already/
         /have placed).../ If this is the first time, get rid of the
         *"New Business Idea!"* heading example entry below... That
         is only for the template to illustrate these instructions
         by example.

  + *You are now at the top of the list*, /(a few lines below this/
         ~README~ /drawer)/. The time is the present. -and- You are all
         fired up with an idea to write about!

  + *Enter a new timestamp with* ~C-c .~, /(that's: Press ~Ctrl-c~, let go,/
                                       /and then type a Period .)/  A
                                       date chooser panel will pop up...

  + *Press ENTER to auto accept today's date and time.*  A new timestamped
         line will appear with your cursor blinking on the right of it...
         There won't be any future entries above you...
         /(maybe next decade? time travel? %^)/

  + *Advance your cursor a few more lines down* to some fresh empty
         space -and- Start Typing Your Idea Like Mad! 

  + *Don't stop* and don't worry about formatting or organizing it
         until later, after all your inspiration has passed and you are
         ready to organize...

- =After You are Done Writing:=

  + *Come back to the timestamp line where you first started*

          Make sure the timestamp has at least one empty line above
          and below it.

  + *Give the timestamp line a title to the right of the timestamp.*

  + *Make this timestamped line an outline heading*

          =Use:= ~C-c ENTER~ /(that's Press/ ~Ctrl-c~ /let go, and/
                          /then press ~ENTER~)/
          =Note:= make sure this new heading has empty lines above
                and below it...

  + *Adjust this new outline heading level with:* ~M-▷~
          /(this will make it a child of ☞ Start Here! heading above,/
          /rather than a sibling)./

  + *Adjust the space* between your heading and your fantastic idea
          below it to one single blank line.

  + *You can organize everything else later...*

          Don't scare away the muses! Get your story down now!

  + *Then you may go out to play elsewhere little grasshopper...*

          But come back later and organize things... OK? Don't
          create a swamp in here! And don't forget to take your
          bath tonight... ;-) 

          
  Having done the simple steps above any time you get inspired, you will be able to tell your grand children.. "I got my first spark of an idea for that book back in Year, Month, Day, time, second" (50 years later!) Now that is being organized! LOL

:END:
*** NEW 💡 New Business Idea! <2020-06-07 Sun> /"yeah we've heard that one before"/
:README:
   This is a dummy example of some crazy idea that you may have gotten at the spur of the moment, while you were doing something elsewhere within this project...  After you are done getting as much of the idea as you initally can then you can simply go back to what you were doing before the inspiration segue tore you away... you might want to schedule this as a todo item before leaving though...

   Later when you are free you can come back to file this or place it where it belongs.  In the case of the note below it would probably go in a research folder of a Sci-Fi related project...
:END:

**** Heading 4:

This is a Heading 4 test...

***** Heading 5:

This is a Heading 5 test...

****** Heading 6:

This is a Heading 6 test...

******* Heading 7:

This is a Heading 7 test...

******** Heading 8:

This is a Heading 8 test...

\newpage

* NEW 📖 Main Document Title /(rename this)/   :export:
:README:
   *This is the Main Body of your Document...* Everything under This Main
   heading will be published in your final PDF, or web page, etc.,
   Including the Main Heading itself... 

   =Note:= /The Published Title of your document will NOT be this/
         *Main Heading.* /Your published Title is specified at the top/
         /of this file.../ 

   Sub headings below are simply your first cloned headings from the
   Templates Section... Use them how ever you wish... They also have
   /:README:/ drawers like this to help guide you...

   *btw*, if you Have *Harmonic Alchemy Modular Emacs* fully installed and
   have enabled the ~Xah-Fly-Keys~ module, you can quickly and easily insert
   your own /:README:/ drawers for your own purposes by typing: ~SPACE e r~ on
   an empty line while in command mode... Type those two keys, and the
   drawer is created for you automatically and opened... Go into insert
   mode and start type your README content within the drawer.  Collapse
   it if you like after you are done...
:END:
** NEW 📃 Introduction:                     :README:
   *Use this space to write the main synopsis of your document...* You
   can write anything you want here but it is recommended strongly
   to summarize the main points of your idea broken up in small
   outline if necessary...

   Keep things short and sweet here... The total *BIG picture*...

   If this is a *tutorial* or *how-to*, you might use this section to
   outline the main points of the document as *Heading Questions* and
   then *clone* this *Introduction section* to a *Summary*, *Conclusion*,
   or *What-We-Learned* section where the question headings are changed
   to final answer headings. /(also short and sweet and to the point)/ 

   /Putting the questions here as links to the body of your doc is/
   /sort-of the FAQ model that emerged organically on the Internet/
   /(pre www daze).../
:END:

About this document... Yadda... Yadda... Yadda...

\newpage

** NEW 📄 Reference:
:README:
   Add links to other reference, source docs, requirements, back stories, whatever, here...  

   To Create a Link Type: ~C-c C-l~ /(then paste: ~link~ & type: "description")/

   To Open a Link Type: ~C-c C-o~
:END:

- [ [ ][ ] ]

- [ [ ][ ] ]

- [ [ ][ ] ]

- [ [ ][ ] ]

\newpage

** NEW 📃 Topic /(main topic template - rename clones)/
:README:
   Use this space to write the main body of your document... Here is
   where all the details happen... Your main headings here should
   follow what you have writtin in your Introduction above...

   If this is a *tutorial* or *how-to*, you might use this section to
   write your detailed answers to the Question Headings outlined in
   your Introduction section above...

   Summarize your answers within a new /main section/ titled:
   *"Conclusion"* or *"Summary"*, etc...
:END:

The following Points are ... yadda... yadda... yadda...

*** NEW 📄 Heading X /(rename this)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

*** NEW 📄 Heading Y /(rename clone of this)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

* ⎘ Meta: /(Usage & Templates)/         :noexport:
** 📃 About:

The *Templates:* section provides skeleton templates for use within this document.  These /"meta-sections"/ do not show up in final published docs, /(e.g., .pdf or web etc)/...

Any sub heading under the "*Templates:"* group can be utilized by copy-pasting the collapsed heading into your existing document sections (i.e., making a clone anywhere you need to create a new section based on the template's structure)... 

In some cases you may have to adjust the heading level of your pasted content... To do that place your cursor at the very beginning of the pasted heading /(completely collapsed)/ and type: ~M-S-<right or left arrow>~  Using the Shift key changes the hierarchy level of the cloned heading as well as the relative sub level headings it may contain... if it is not collapsed first you only change the level of the selected heading but none of the headings below /(no matter if they are currently sub headings)/.

The intent of these templates are to save lots of time starting up a new document or to quickly develop a new idea.  Lets see if it helps. :trollface:

\newpage

** 📄 Instructions:

=Treat Anything Found Within This Section as a Potential TEMPLATE= which may be used repeatedly as you write your Document Above within the MAIN Document Section...

Change the Name, titles, and/or headings of Your Cloned Template to a specific title required within your document...

Start writing and finish your new section... /(the basic structure is already/
/set for you/...

\newpage

** NEW 📃 Topic /(main or secondary topic template - rename clones)/
:README:
   Use this space to write the main body of your document... Here is
   where all the details happen... Your main headings here should
   follow what you have writtin in your Introduction above...

   If this is a *tutorial* or *how-to*, you might use this section to
   write your detailed answers to the Question Headings outlined
   in your Introduction section above...

   Summarize your answers within a new /main section/
   titled: *"Conclusion"* or *"Summary"*, etc...
:END:

The following Points are ... yadda... yadda... yadda...

*** NEW 📄 Heading G /(generic template - rename this)/

At ipsum vitae est lacinia tincidunt. Maecenas elit orci,gravida ut, molestie non, venenatis vel, lorem. Sedlacinia. Suspendisse potenti. Sed ultricies cursuslectus. In id magna sit amet nibh suspicit euismod.Integer enim. Donec sapien ante, accumsan ut,sodales commodo, auctor quis, lacus. Maecenas a elitlacinia urna posuere sodales. Curabitur pede pede,molestie id, blandit vitae, varius ac, purus. Mauris atipsum vitae est lacinia tincidunt. Maecenas elit orci, gravida ut, molestie non, venenatis vel,lorem. Sed lacinia. Suspendisse potenti. Sed ultrucies cursus lectus. In id magna sit amet nibhsuspicit euismod. Integer enim. Donec sapien ante, accumsan ut, sodales commodo, auctorquis, lacus. Maecenas a elit lacinia urna posuere sodales. Curabitur pede pede, molestie id,blandit vitae, varius ac, purus.

\newpage

*** NEW 📄 Heading T /(template with tables - rename this)/

**** Basics:

The following are example Tables you can use /(with some instructions)/ Use what you need and Remove the rest...

- *Simple Basic*

   | Item 1 | Item 2 | Item 3 | Item 4 |
   |--------+--------+--------+--------|
   |        |        |        |        |

- *A Bit More than Basic*

  | My Column 1 | My Column 2 | Last Column |
  |-------------+-------------+-------------|
  |          42 | foo         | bar         |
  |          23 | baz         | abcdefg     |
  |-------------+-------------+-------------|
  |          65 |             |             |

\newpage

**** Column Allignment:

- *Columns are automatically aligned by default as such:*

   /Number-rich Columns to the Right/

   /String-rich Columns to the Left/

- *Override Automatic Alignment:*

   /If you want to override the automatic alignment 
   use:/ ~<r>~, ~<c>~ or ~<l>~.

   #+CAPTION: Table with aligned columns
   |              |     <c>      | <l>          |
   | 1            |      2       | 3            |
   | Right        |    Center    | Left         |
   | xxxxxxxxxxxx | xxxxxxxxxxxx | xxxxxxxxxxxx |

\newpage

**** Header row

- *You can create tables with a header row:* 

   /(by using a horizontal line of dashes to separate/ 
    /it from the rest of the table)/ 

   *Like This:*

   #+CAPTION: Table with an header row
   | Name of column 1 | Name of column 2 | Name of column 3 |
   |------------------+------------------+------------------|
   | Top left         | Top middle       |                  |
   |                  |                  | Right            |
   | Bottom left      | Bottom middle    |                  |

\newpage

**** Table placement

- *Align Table Centred:* 
   /(the default)/

   | a | b | c |
   |---+---+---|
   | 1 | 2 | 3 |
   | 4 | 5 | 6 |

- *Do NOT Align Center:*
   /(overrides default)/

   #+ATTR_LATEX: :center nil
   | a | b |
   | 1 | 2 |

- *Align Table to Left Side:*

   #+LATEX: \noindent
   #+ATTR_LATEX: :center nil
   | a | b | c |
   |---+---+---|
   | 1 | 2 | 3 |
   | 4 | 5 | 6 |
   #+LATEX: \hfill

   /The noindent just gets rid of the indentation of the first line of a paragraph which in this case is the table. The hfill adds infinite stretch after the table, so it pushes the table to the left./

- *Align Table to Right Side:*

   #+LATEX: \hfill
   #+ATTR_LATEX: :center nil
   | a | b | c |
   |---+---+---|
   | 1 | 2 | 3 |
   | 4 | 5 | 6 |

   /Here the hfill adds infinite stretch before the table, so it pushes the table to the right./

- *Table size:*

   #+ATTR_HTML: :width 100%
   | Cell in column 1, row 1 | Cell in column 2, row 1 |
   | Cell in column 1, row 2 | Cell in column 2, row 2 |

   *NOTE:* /You can do a whole lot more with org-tables /using/
         /table.el but that information is too much to include/ 
         /in this template.../ 

         /Consult your Org-Mode cheat sheet instead/

\newpage

*** NEW 📄 Heading L /(template with links - rename this)/

- [ [ ][ ] ]

- [ [ ][ ] ]

- [ [ ][ ] ]

\newpage

*** NEW 📄 Heading C /(template with checklists - rename this)/

   - [ ] *yet to be done* /Hit ~C-c~ ~C-c~ to toggle Done/

   - [-] *An item In Process* /Hit ~C-u~ ~C-u~ then ~C-c~ ~C-c~ to set/

   - [X] *An item which is done* /Hit ~C-c~ ~C-c~ to toggle Not-Done/

****** Insert a new item with a checkbox: ~M-S-RET~  

- [ ] *Item One:*
   Type: ~M-S-RET~ to Get Next Item with Checkbox:

- [-] /<-(this is the result)/ [1/2]

   + [-] *Second Level Item:*
      Type: ~M-S-RET~ to Get Next Item with Checkbox:

   + [X] /<-(this is the result)/

\newpage

*** NEW 📄 Heading S /(template with src-code blocks, etc. - rename this)/

- *SysAdmin & Command Prompts:*

   #+begin_src conf
   admin@vps1:~$ sudo apt update
   #+end_src

   #+begin_src conf
   user@home:~$ git status
   #+end_src

- *Evaluate some eLisp code:*

   #+begin_src emacs-lisp
   (defvar test1 "test1 value")
   (defvar test2 "test2 value")
   test2
   #+end_src

   #+results:
   : test2 value

   #+begin_src emacs-lisp
   (defvar test1 "test1 value")
   (defvar test2 "test2 value")
   test1
   #+end_src

   #+results:
   : test1 value

\newpage

**** Additional Admonitions
***** Attention:

#+begin_attention
Attention
#+end_attention

***** Hint:

#+begin_hint
Hint
#+end_hint

***** Error:

#+begin_error
Error
#+end_error

***** Danger:

#+begin_danger
Danger!!!
#+end_danger

\newpage

*** NEW 📄 Heading G /(drama script snippit template - rename this)/

#+begin_src fountain
  MARY
  = This is a fountain formatted script snippit example / template

  EXT. (JUNKYARD) (NIGHT) 

  MARY
  (LAUGHING)
    
  I Can't believe you are writing a screenplay
   
  on that crappy dog chewed notebook...
    
  what a geeky thing to do!
    
  (LAUGHS EVEN LOUDER)

  >*THE END*<
#+end_src

\newpage
