# -**- mode: org; coding: utf-8 -**-
#+LATEX_HEADER: \usepackage{parskip}
#+LaTeX_HEADER: \usepackage{paralist}
#+LATEX_HEADER: \usepackage[hyperref,x11names]{xcolor}
#+LATEX_HEADER: \usepackage[colorlinks=true,urlcolor=SteelBlue4,linkcolor=Firebrick4]{hyperref}

#+begin_comment
 Setup Files:
   For Cloned Versions of this template, replace file/paths below
   with file/paths to your own custom setup files (which you could 
   convienently clone from the example setup files provided in
   ../org-templates/ directory...

 NOTE: 
   #+CATEGORY: is specified within log-book.org setupfile.
   If you need to change the category do it in log-book.org
   or your cloned version of it...
#+end_comment

#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/log-book.org
#+SETUPFILE: ~/.emacs.d/Docs/pubOps/org-templates/default-tags.org

#+TITLE: HAP - General LOG Notebook Skeleton
#+EXPORT_FILE_NAME: HAP_General-Log-Notebook-Skeleton.pdf
#+KEYWORDS:
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+DATE: <2021-03-26 Fri>
#+TEXT: Created: <2021-02-11 Thu>
#+TEXT: Last Published: <2021-03-26 Fri>
#+FILETAGS: templates logs

#+DESCRIPTION: HAP - Modular Emacs Org Mode General Log Notebook Template.  This is the replacement for the Markdown Mode templates I was using previously, which were in turn replacements for even older templates I made originally for Evernote/Trello/Scrivener...

#+begin_comment
 Don't mess with these unless you have good reason, (e.g., testing).
 Use Setup Tag File above to specify tags for this file...

# #+STARTUP: noptag
# #+TAGS:
#+end_comment

* NEW About:

:README:
Use this section as Front Matter for your Log Book...
:END:

This Log Book was created for...  Yadda Yadda... Yadda...

** References:

Add links to other reference, source docs, requirements, back stories, whatever, here...

- *[ [URL][Link Name] ]*

- *[ [][] ]*

- *[ [][] ]*

- *[ [][] ]*

- *[ [][] ]*

* Begin Log:
:PROPERTIES:
:CUSTOM_ID: HAP-general-log-notebook-skeleton-1
:END:
** 2021:

*** NEW log: <2021-05-13 Thu> Entry Title /(template)/

:README:

- Since you created this new log entry you are probably in the middle of a task related to it right now!  Go ahead and punch the clock right now as well, to start recording your time! The following Commands are defined below for you to remember and use to track your time:

  + *C-c C-x C-i* - Start Clock /(Begin OR Resume Clocking Current task)/

      This creates a new :CLOCKING: Time Card Entry that looks like this:

      Do this now... Start recording your time girl!  Be in control of your life!

     After doing the above, you can go away and do some work, leaving this log note to visit other files and work on them etc. The clock will be recording your time all the while... You will see in your mode line the elapsed clock time as you work...

  + *C-c C-x C-j* - Return back to the Heading where you started the clock...
      You do this after you have worked on a task for a while and you need to come back to the time card /(this Log Entry Heading)/ and stop the clock before going off to do something unrelated to the log entry...

  + *C-c C-x C-o* - *Stop the Clock* /(to stop clocking your time on task)/
       This *Finalizes the Time Card Entry* within ~:CLOCKING:~ /(created earlier when you started the clock)/... The completed time card entry looks like this:

       The above entry shows start timestamp, end timestamp, and total time worked during this segment...  As you can see from the example above I left the clock running all day by accident.  If you do something like that you can always come back and directly edit the clock times by hand to amend them...  After changing clock times or dates, etc. type the following to *Update the Time Card Entry*:
            *C-c C-c*
       and the total time will change at the end showing your new calculated time...

       If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

       When you are all done with this Log Entry mark it *DONE*

  + *C-c C-x C-q* - Cancel Current Clock /(in case you accidentally started it)/

       This removes currently running clock and forgets it...

 + *C-c C-x C-d* - Display Clocking Info: /This will show elapsed times to the right of headings.../

- Once all of this has become routine for you, go ahead and remove this ~README~ drawer from this template... That way it does not get copied when you need to clone new log entries...

:END:

**** Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW Summary: [0/3]

This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...  

Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...

1. [ ] 

2. [ ] 

3. [ ]

\newpage

**** NEW Details:

***** NEW New Item 1 /(placeholder)/ [0/1]

- [ ]

\newpage

***** NEW New Item 2 /(placeholder)/ [0/1]

- [ ]

\newpage

***** NEW New Item 3 /(placeholder)/ [0/1]

- [ ]

\newpage

* HowTo:                                        :noexport:
** Introduction:

Use this Standard Log /(template)/ as a multi purpose time card/log entry vehicle...

Use one for work, one for home, one for play, for creative projects, for pretty much anything that needs to be recorded with time and events in a log... I am honing this new scheme to be the General Purpose Log Note Template for everything that I ever dreamed of having.  And for you too!

I stopped using Markdown files for this purpose... This makes total sense as *Org-Mode* was designed exclusively for such things! Using *Markdown* after the fact for such things would be like going back to a /"*Dec VT220* green screen *dumb terminal*"/ after experiencing *X Windows* on a Big *HP-UX Workstation*

Yeah, that's a personal story from the past, lol... All you Mac users out there, please realize that your beautiful Apple desktop is in fact an *HP-UX Motif X-Windows widget set clone*!  That's what Steve Jobs believed to be the best X-Windows tool-kit of the day /(when he was building the NeXT computer)/...  So... Yup he copied that! The Applications Doc at the bottom of your screen is a dead giveaway. Hewlet Packard was first to use such UI concepts... /(back before the dawning of the web we loved those HPUX Workstations!)/

\newpage

*** Emacs Shorthand Command Key Notation:

The command key conventions used in the instructions below, /(as well as all *Harmonic Alchemy Productions* docs)/, follow *Standard Emacs* command key naming conventions.

Official GNU Emacs documentation uses a shorthand notation to indicate the *Ctrl* key as an upper case *C-* (/with minus appended/). Upper case *M-* (/with minus appended/) is the shorthand notation for the Emacs *META* key...

*** Important Note For Mac Users:

On Mac OS, *Modular Emacs* maps your *Ctrl* key to the *Apple Command* key. Emacs *META* is mapped to both *Alt* and *Ctrl* keys... Outside of Emacs all those keys function normally.  

Therefore, for Mac users, anytime you either see *C-* or *Ctrl* below, use your *Apple Command* key for that when using Modular Emacs.  Anytime you see either *M-* or *META* below, use *Alt* or *Ctrl* keys for that when using Modular Emacs. 

Anytime you are using Modular Emacs following instructions from standard vanilla Emacs docs, keep in mind your ~Ctrl~ and ~META~ keys are not /"standard"/ anymore and you must make a mental translation.  Beyond that, you will be fine following other emacs tutorials etc.  Hey... you Mac enthusiasts are used to that kind of /"being different"/ stuff anyway, right? Being one of /"the rest of us"/ that is... What the heck does that mean anyway? LOL

The above key assignments were done to get the *Emacs C-* key closer to the space bar where it can be activated with your left thumb instead of contorting to get at it with your pinkie finger. This makes using *Xah Fly Keys* even easier to use and less stressful on your fingers...

In the Official Emacs documentation you will commonly find key command notations such as *C-x* or *M-x*... This means: Hold the *Ctrl* /(or *META*)/ key down while typing the *x* key.  

Any time you see this notation, regardless of what key may be connected to it with a dash /(e.g., *C-c*, *M-5*, etc.)/, this means to hold the *Ctrl*-or-*META* key down while you press the other key connected to it with the dash... If you have a command that includes many *C-key* or *M-key* commands in succession simply hold the *Ctrl*-or-*META* key down the entire time you type the other keys and then let go...

If you see other keys alone separated by a space after the *C-x* or *M-x* /(e.g., C-x *d*, M-x *b*, etc.)/ this means to type that key /AFTER/ letting go of the *Ctrl*-or-*META* key...

*Got that?* That's the key notation system we use here... It is all standard Emacs...  The above paragraphs are mostly for the benefit of new Emacs users! And there is more to learn below. If you are an Emacs/Org-Mode veteran please bear with us...

\newpage

*** Org Mode Timestamps and Clocking:

This Template utilizes the default *Org-Mode:* "*C-c* ." command /(i.e., That's Ctrl-c and then type a dot. This Enters a timestamp range at the cursor position)/. The command employs *org-evaluate-time-range* to compute time on task.  This is useful for timesheets etc. 

In addition, the *Log Entry (template)* stores and tracks *Org-Mode :CLOCKING:* entries and displays results in a *Time Card Table* with total time computed... 

Common time clocking commands are defined within the *Log Entry (template)* itself. Any time you need to look up clocking commands, open the *:README:* drawer under the *Log Entry (template)* heading by placing your cursor over it and hitting *TAB*.

Additional commands for using *Org-Mode* with Modular Emacs will be explained here if needed, as well as other *Harmonic Alchemy Modular Emacs Templates* that get produced in the future...

\newpage

** Instructions:

This Log Notebook is being designed as these docs are being written...  At first much of the design is being done /manually/ while formats, concepts, are tried and tested.  Eventually much of the instructions below will become much simpler as there will be capture templates, and processes in place that replace the need to manually copy/paste things as we are doing initially below...  

Please bear with the author/architect as she makes up her mind about how to do things in here...  The Org-mode, LaTeX options are vast! Not to mention a sea of extra packages that could be tried out... /I feel like I am re-inventing wheels within rabbit holes!/ lol

*Note:* If you are making your very first log entry within a brand new clone of this template, DON'T use a clone from the *Log Entry (template)* just yet.  Instead use the dummy boilerplate placeholder Log Entry /(with timestamp)/ already in place as your first heading under the *Begin Log Notebook:* heading. 

That first boilerplate log entry is there only as an example to show you what a completed log book entry might look like.  You may rename/commandeer it for your purposes now... Otherwise you will end up deleting it later... /Don't be wasteful... Recycle!/ lol ;-)

Also for first time entry within your brand new log book, Skip the next two headings below /(copy and paste instructions)/ and continue following instructions under the: *Edit-Compose your new Log Entry:* heading /(as you will be commandeering the dummy boilerplate log entry as your first log entry)/.  Instructions for working on a new Cloned Log Entry are the same as for updating/emending an existing one from that point on...

*Otherwise*, if you already have one or more existing log entries from before, continue following instructions immediately below beginning with: *Copy/Clone Log Entry (template)*

\newpage

*** Copy/Clone - Entry: /<timestamp>/ (template)

- Place your cursor on the *Entry: /<timestamp>/ (template)* heading and type *TAB* to collapse all of its contents into the heading alone. Then move your cursor to the first column on the empty line above the heading and type the "*t*" key to set the mark for selection, /(xah-fly-keys Command Mode)/.

- Now, move your cursor down one single line by typing the "*k*" key /(xah-fly-keys Command Mode)/, to move down one single line, selecting-highlighting the text in the process.

- Leave your cursor on the first /(leftmost)/ column of the very next line. Do not advance it any more columns to the right! Otherwise, anything else selected on the next line will also be copied!

  *Note:* Selected text will be highlighted, but your cursor at the end of it will not be part of that selection. Placing your cursor on the first column of the next line will include the invisible new-line character which is what you want, but any text directly under the cursor will not be copied...  Later, after pasting this text somewhere else, your cursor will end up sitting on the first column of a blank line under the pasted text.  /(exactly as intended)/

- To complete the copy operation, type "*c*" /(xah-fly-keys Command Mode)/. This will save the selection for pasting later, /(the highlighted text will go back to normal)/... You should have gotten only the Entry: /<timestamp>/  and not anything from the heading below it. 

   *Note:* If you type: "*spacebar t*" /(xah-fly-keys leader key command)/ it will show you the contents of your paste buffer...  You can see what you copied in there...  To get out of the paste buffer view, type: "*spacebar u*" and it will return you to where you were before...

\newpage

*** Paste your Cloned Log Entry:

- *To Paste:* Advance your cursor to a blank line just below the main heading: *Begin Log Notebook:* and then press *enter* a couple times to get your cursor on a fresh clean line with some extra space above and below it... /(above any previously time stamped entries you may already have placed)/...

- Press "*v*" /(xah-fly-keys Command Mode)/ to paste your cloned Log Entry template... If you find out that what you copied also included some unwanted text directly below it, no problems... Just delete that part now... 

   *Note:* If you accidentally copied one or more previously invisible bullets to column one on a blank line they will create an invisible "ghost" heading that you will now need to delete... You will know this if you see an org-ellipsis "⤵" symbol on a line by itself indicating a heading but no text... Simply delete that whole line and it will go away... Now you are ready to compose your new log entry...

\newpage

*** Edit-Compose your New Log Entry:

Note:* If this is your first time using this log, you will be editing the dummy boilerplate placeholder *Entry:* /<with timestamp>/ already in place as your first log entry heading under the main *Begin Log Notebook:* heading.  

Conversely, If you just pasted a new cloned copy of the: *Entry:* /<timestamp>/ *(template)* under the main *Begin Log Notebook:* heading, you will be editing that instead.

The instructions below for working on a new Cloned Log Entry are pretty much the same as for updating-reusing an existing log entry... /(differences will be noted in instructions below)/

- Place your cursor directly on the existing timestamp of your new Log Entry, and enter the key binding:  *C-c .* /(i.e., press *Ctrl* key while holding "*c*", and then type a dot)/ A date chooser panel will pop up...

- At this point, type one more *dot* to force the calendar selection to the current time and date and then, Press *ENTER* to accept your choice... /This will update the existing older timestamp with the current date/time.../ Check to make sure the timestamp was properly updated and then move on to the next step... This timestamp will not be updated after that.  It records the initial time of your new log entry to the Day and time you first created it...

- You are now at the top of the list, (a few lines below the main "*Begin Log Notebook:"* heading), on a fresh new Log Entry Heading... Your timestamp indicates the present, /-and-/ You are ready to record a log of your current activities! This way, your most recent log entries will be on the top and descend down historically from there...

- Follow the ~:README:~ directions within the Time Card section contained within your fresh new log entry to learn how to /"clock in"/ and /"clock out"/ of your log entry as you are on the task of entering your log data...

\newpage

*** Enter New Log Entry Details:

Two sub headings have been provided for your use /(if you need them)/. However, you may structure your log entries any way you wish.  The two provided headings:  *Summary* and *Details* are simply suggestions to help make your log entries a bit more organized...

The *Summary* heading could be used to log the main executive summary points, /(which you would include in the exported PDF as a report to give to your boss or clients)/. 

Conversely, the *Details* heading could contain a complete, thorough log of your work, which would be excluded from the final PDF report.  Everything under *Details* heading would be extra information that you don't want to bother your clients or boss with /(unless they ask for more detail of course)/. In that case, you will have it all recorded and organized for easy access later if needed...

Place the *:noexport:* tag at the end of any org outline heading to exclude it and all its children from the PDF upon export...  You can add as much detail as you need within these excluded sections without cluttering up your final PDF.  The entire main heading: *How to Use this Template:* is already excluded from the final PDF, so it can be left in and your PDF will only include the *Begin Log Notebook:* section...

*** Export your Log as a PDF Report:

Anytime you need to see your Log Notebook as a nicely printed PDF report, you can export it using the following custom key command: *spacebar e p* /(i.e., press *spacebar*, type "*e*" and then "*p*" - *Xah-Fly-Keys Command Mode* extended leader key sequence)/

\newpage
** Templates:

*** NEW log: <2021-03-29 Mon> Entry Title /(template)/

:README:

- Since you created this new log entry you are probably in the middle of a task related to it right now!  Go ahead and punch the clock right now as well, to start recording your time! The following Commands are defined below for you to remember and use to track your time:

  + *C-c C-x C-i* - Start Clock /(Begin OR Resume Clocking Current task)/

      This creates a new :CLOCKING: Time Card Entry that looks like this:

      Do this now... Start recording your time girl!  Be in control of your life!

     After doing the above, you can go away and do some work, leaving this log note to visit other files and work on them etc. The clock will be recording your time all the while... You will see in your mode line the elapsed clock time as you work...

  + *C-c C-x C-j* - Return back to the Heading where you started the clock...
      You do this after you have worked on a task for a while and you need to come back to the time card /(this Log Entry Heading)/ and stop the clock before going off to do something unrelated to the log entry...

  + *C-c C-x C-o* - *Stop the Clock* /(to stop clocking your time on task)/
       This *Finalizes the Time Card Entry* within ~:CLOCKING:~ /(created earlier when you started the clock)/... The completed time card entry looks like this:

       The above entry shows start timestamp, end timestamp, and total time worked during this segment...  As you can see from the example above I left the clock running all day by accident.  If you do something like that you can always come back and directly edit the clock times by hand to amend them...  After changing clock times or dates, etc. type the following to *Update the Time Card Entry*:
            *C-c C-c*
       and the total time will change at the end showing your new calculated time...

       If you need to go away and do something else before finishing this task, you can do so after clocking out... When you come back simply clock back in again to start another Time Card Entry just as before... The new time card entry will appear above the earlier one within the ~:CLOCKING:~ drawer... When you clock out of this task it will look just like the entry below it with a total time worked tagged on the end...

       When you are all done with this Log Entry mark it *DONE*

  + *C-c C-x C-q* - Cancel Current Clock /(in case you accidentally started it)/

       This removes currently running clock and forgets it...

 + *C-c C-x C-d* - Display Clocking Info: /This will show elapsed times to the right of headings.../

- Once all of this has become routine for you, go ahead and remove this ~README~ drawer from this template... That way it does not get copied when you need to clone new log entries...

:END:

**** Time Card:

#+BEGIN: clocktable :scope tree2 :maxlevel 4 :tstart "<-1d>" :tend "<+1m>" :step week :stepskip0  t :emphasize t :level t :tcolumns 3
#+END:

\newpage

**** NEW Summary: [0/3]

This Summary is mostly to help you find things later when you cannot remember when or where is was done... If you go to the top of this file and expand all headings to show ALL content, then do a search on "~Summary:~" you will be able to quickly scroll through and scan these summaries quickly to find what you were looking for... 

Also the *Time Card* /displayed above/ each search hit will give more clues by showing important headings you worked on...  

Below is an optional list /(that could also provide links)./ This list could be used to itemize things you worked on, but I personally find it easier to simply write a short one or two line description containing important keywords right here and nothing more. I think that is more useful...

1. [ ] 

2. [ ] 

3. [ ]

\newpage

**** NEW Details: [0/3]

***** NEW New Item 1 /(placeholder)/ [0/1]

- [ ]

\newpage

***** NEW New Item 2 /(placeholder)/ [0/1]

- [ ]

\newpage

***** NEW New Item 3 /(placeholder)/ [0/1]

- [ ]

\newpage
