#+TITLE: HAP - General LOG (template)
#+AUTHOR: Alisha Awen - Harmonic Alchemy Productions
#+EMAIL: Siren1@disroot.org
#+CATEGORY: templates
#+STARTUP: overview
#+STARTUP: inlineimages
#+DESCRIPTION: HAP - Emacs Org Mode General Log Template.  This is the replacement for the Markdown Mode templates I was using previously, which were in turn replacements for templates I made originally for Evernote...
#+EXPORT_FILE_NAME: General-Log-Template.pdf
#+OPTIONS: date:nil
#+OPTIONS: c:t
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: inline:nil
#+OPTIONS: d:nil
#+KEYWORDS:
#+FILETAGS:

* How To Use This Template: :noexport:

- [Add Link to Autofocus Notebook Here]

Use this Standard Log (template) as a multi purpose time card/log entry vehicle...
Use it for work, home, play, creative projects, pretty much anything that needs to be recorded with time and events in a log...

This Template utilizes the basic "Ctrl-C ." command (i.e., enter a timestamp range at cursor position, and uses org-evaluate-time-range command to compute time on task, (for timesheets etc.) 

Once I get this new scheme working well it will become my new General Purpose Log Note Template for everything... I will stop using Markdown files for this purpose... This makes total sense as Org-Mode was designed exclusively for such things!

** Instructions:

*** Copy/Clone heading below titled: Log Entry (template)

- *Note:* If this is the first time using this log, Don't copy the template.  Instead edit the dummy boilerplate placeholderlog entry already in place.  That was just for example and can be changed/commandeered for your purposes...

- Otherwise Copy the Log Entry (template) and all of its sub-contents to your paste buffer... 

   + To do this, place your cursor alone on one blank line above the "Log Entry (template) heading and then type the "t" key to set the mark for selection, (xah-fly-keys Command Mode)

   + Next, move your cursor down one single line (i.e., use the "k" key, xah-fly-keys Command Mode) to select the entire heading down so that your cursor is left on the first bullet of the next heading line.   Make sure your cursor is only on the first bullet in the first column of the next heading line... Otherwise, anything else selected on the next heading line will also be copied!

- Type "c" (xah-fly-keys Command Mode) to copy this selection for pasting later... (You should have gotten only the Log Entry and not anything from the heading below it)

*** Paste your Cloned Log Entry:

- *Note:* If this is your first time using this log, simply use the existing dummy boilerplate placeholder log entry already in place. Change its headings and content to suit your needs.  It was just for example and can be changed/commandeered for your purposes... Don't paste a new clone as in the next two steps, but do follow the steps after that...

- Advance your cursor on a blank line just below the main heading: "Begin Log Notebook:" and then press enter a couple times to get your cursor on a fresh clean line with some extra space above and below it... (above any previously time stamped entries you may already have placed)...

- Press "v" (xah-fly-keys Command Mode) to paste your cloned Log Entry template... If you find out that what you copied also copied some of the heading below it, no problems... Just delete that part now... (realize that if you accidentally copied one or more invisible bullets to column one on a blank line they will create an invisible heading that you will need to delete... You will know this if you see an org-ellipsis "⤵" symbol on a line by itself indicating a heading but no text... Simply delete that whole line and it will go away... Now you are ready to do your new log entry...

- Place your cursor to the right of your newly cloned Log Entry heading by one space, (or directly on the existing timestamp if using the dummy placeholder entry the very first time) and then use the key binding:  C-c . (i.e., press ctrl key while holding "c", and then type a period) A date chooser panel will pop up... *Note:* If this is the first time there will already be a date time stamp... In that case put your cursor inside of it before typing C-c .





- Press ENTER to auto accept today's date and time... This will create a new timestamp, or update the existing timestamp to the current date/time...

- You are now at the top of the list, (a few lines below the main "*Begin Log Notebook:"* heading), on a fresh new Log Entry Heading... Your timestamp indicates the present, -and- You are ready to record a log of your current activities! This way, your most recent log entries will be on the top and descend down from there...






- Follow the directions within the Time Card section to learn how to "clock in" and "clock out" of your log entry as you are on the task of entering your log data...

- Continue to fill in your log data and when you are done go back to the Log Entry Heading and "clock out"

** Log Entry (template)

:README:

- With your cursor still sitting on your new Log Entry Heading, Start the time clock for this log entry by typing:   C-c C-x C-i
   + A new drawer named *:CLOCKING:* will appear where all your clocked times for this heading will be recorded...

- Later When you are finished adding your log entry and ready to go do something else, place your cursor back on the *Log-Entry* heading and Stop the clock (clock out) by typing:  C-c C-x C-o

- Once all of this has become routine for you, go ahead and remove this README drawer from this template... That way it does not get copied when you need to clone new log entries... 
:END:

**** Time Card: <2020-07-30 Thu>

**** Main Points:

1. Yadda Yadda Yadda
2. Yadda Yadda Yadda
3. Yadda yadda yadda

**** Details:

Yadda, Yadda, Yadda... etc...

* Begin Log Notebook:
** Log Entry <2020-07-30 Thu>
:CLOCKING:
CLOCK: [2020-07-30 Thu 21:51]--[2020-07-30 Thu 22:06] =>  0:15
:END:

**** Time Card:

|--------+-------+--------|
| *Start:* | *Stop:* | *Hours:* |
|--------+-------+--------|
|        |       |        |


|-------------------+--------|
| Start: / Stop:    | Hours: |
|-------------------+--------|
| -07-24 Fri>- |        |
|-------------------+--------|
| *Total Time:*       |        |
|-------------------+--------|

**** TODO Main Points:

1. Yadda Yadda Yadda
2. Yadda Yadda Yadda
3. Yadda yadda yadda

**** Details:

***** DONE First sub-task
CLOSED: [2020-07-30 Thu 18:14]
:LOGBOOK:
- State "DONE"       from              [2020-07-30 Thu 18:14]
:END:

Yadda, Yadda, Yadda... etc...

***** WAITING Second sub-task
:LOGBOOK:
- State "WAITING"    from              [2020-07-30 Thu 18:15] \\
  Waiting for First sub-task to be final tested...
:END:

Yadda, Yadda, Yadda... etc...
***** 

